import {visibleAd,selectAds,safeUrl,createRecorder,pageSection,ANALYTICS_RELEASE_ENABLED,publicAdWindow,publicAdQuery} from './commercial-model.js';
export async function installCommercialPublic(api){
 const {db,collection,doc,getDoc,getDocs,query,where,orderBy,startAfter,limit,setDoc,serverTimestamp}=api;let recorder=null,ads=[],observer,timer,index=0,paused=false,lastMove=Date.now();
 try{if(ANALYTICS_RELEASE_ENABLED){const config=await getDoc(doc(db,'platformTelemetry','config'));if(config.data()?.enabled===true&&!navigator.globalPrivacyControl&&navigator.doNotTrack!=='1'){
 recorder=createRecorder({storage:sessionStorage,random:()=>crypto.randomUUID().replaceAll('-',''),write:async s=>{const ref=doc(db,'analyticsSessions',s.id);await setDoc(ref,{startedAt:new Date(s.start||s.last),updatedAt:serverTimestamp(),pageViews:s.pageViews,pages:s.pages,views:s.views,clicks:s.clicks});},now:Date.now});
 recorder.record('page',document.querySelector('#home')?pageSection(location.hash):'other');window.addEventListener('souq-pageview',event=>recorder.record('page',event.detail));window.addEventListener('hashchange',()=>recorder.record('page',document.querySelector('#home')?pageSection(location.hash):'other'));document.addEventListener('visibilitychange',()=>{if(document.hidden)recorder.flush();});
 }}}catch{/* Collection disabled/unavailable: no invented counts and no retry loop. */}
 if(!document.querySelector('#home'))return {recorder};
 const root=document.createElement('section');root.className='commercial-home';root.setAttribute('aria-label','إعلانات تجارية');document.querySelector('#home')?.before(root);
 const middle=document.createElement('section'),footer=document.createElement('section');middle.className='commercial-middle';footer.className='commercial-footer';document.querySelector('#sell')?.before(middle);document.querySelector('.launch-footer')?.before(footer);
 const hovered=new Set();for(const box of [root,middle,footer]){box.addEventListener('pointerenter',()=>hovered.add(box));box.addEventListener('pointerleave',()=>hovered.delete(box));}
 function card(ad,eager=false,heroCard=false){const a=document.createElement('a');a.className='commercial-card';a.href=safeUrl(ad.targetUrl);a.target='_blank';a.rel='noopener noreferrer sponsored';a.dataset.ad=ad.id;const img=document.createElement('img');img.src=safeUrl(ad.imageUrl,true).replace('/image/upload/','/image/upload/f_auto,q_auto,w_'+(heroCard?1200:480)+'/');img.alt=ad.title;img.width=heroCard?1200:480;img.height=heroCard?500:240;if(eager)img.fetchPriority='high';img.loading=eager?'eager':'lazy';img.decoding='async';a.append(img);const badge=document.createElement('span');badge.className='commercial-label';badge.textContent='إعلان';a.append(badge);const text=document.createElement('div');const title=document.createElement('strong');title.textContent=ad.title;text.append(title);if(ad.description){const p=document.createElement('p');p.textContent=ad.description;text.append(p);}const cta=document.createElement('span');cta.className='commercial-cta';cta.textContent=ad.cta||'تعرف على المزيد';text.append(cta);a.append(text);a.onclick=()=>{recorder?.record('views',ad.id);recorder?.record('clicks',ad.id);recorder?.flush();};img.onerror=()=>{ads=ads.filter(item=>item.id!==ad.id);render();};observer?.observe(a);return a;}
 observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting&&e.intersectionRatio>=.5&&!document.hidden){recorder?.record('views',e.target.dataset.ad);observer.unobserve(e.target);}},{threshold:.5});
 function render(){const focusLabel=root.contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;observer.disconnect();root.replaceChildren();middle.replaceChildren();footer.replaceChildren();const hero=selectAds(ads,'hero');if(hero.length){const stage=document.createElement('div');stage.className='commercial-hero';stage.setAttribute('aria-roledescription','عارض إعلانات');index%=hero.length;stage.append(card(hero[index],index===0,true));stage.setAttribute("aria-label","الإعلانات الرئيسية");const nav=document.createElement('nav');nav.setAttribute('aria-label','تنقل الإعلانات');const button=(text,fn,label=text)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',label);b.onclick=()=>{lastMove=Date.now();fn();};return b;};nav.append(button('→',()=>{index=(index-1+hero.length)%hero.length;render();},'الإعلان السابق'));hero.forEach((ad,i)=>{const b=button('•',()=>{index=i;render();},'الإعلان '+(i+1));b.setAttribute('aria-current',String(i===index));nav.append(b);});nav.append(button('←',()=>{index=(index+1)%hero.length;render();},'الإعلان التالي'));nav.append(button(paused?'تشغيل':'إيقاف',()=>{paused=!paused;render();}));const counter=document.createElement('span');counter.className='commercial-counter';counter.setAttribute('aria-label','رقم الإعلان');counter.textContent=(index+1)+' / '+hero.length;nav.append(counter);stage.append(nav);let touch;stage.addEventListener('touchstart',e=>{touch=e.touches[0]&&[e.touches[0].clientX,e.touches[0].clientY];},{passive:true});stage.addEventListener('touchend',e=>{if(!touch)return;const end=e.changedTouches[0],dx=end.clientX-touch[0],dy=end.clientY-touch[1];touch=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.5){index=(index+(dx>0?1:-1)+hero.length)%hero.length;lastMove=Date.now();render();}},{passive:true});root.append(stage);}const side=document.createElement('div');side.className='commercial-side';for(let i=1;i<=3;i++){const ad=selectAds(ads,'hero_side_'+i)[0];if(ad)side.append(card(ad));}if(side.children.length)root.append(side);const mid=selectAds(ads,'middle')[0];if(mid)middle.append(card(mid));for(let i=1;i<=5;i++){const ad=selectAds(ads,'footer_'+i)[0];if(ad)footer.append(card(ad));}root.hidden=!root.children.length;middle.hidden=!middle.children.length;footer.hidden=!footer.children.length;if(focusLabel){const target=[...root.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===focusLabel);(target||root.querySelector('nav button:last-child'))?.focus();}}
 try{const window=publicAdWindow();let cursor;do{const snap=await getDocs(publicAdQuery(api,window,cursor));ads.push(...snap.docs.map(d=>({...d.data(),id:d.id})).filter(a=>safeUrl(a.imageUrl,true)&&safeUrl(a.targetUrl)));if(snap.size<100)break;cursor=snap.docs.at(-1);}while(true);render();timer=setInterval(()=>{if(document.hidden)return;const expired=ads.some(a=>!visibleAd(a));if(expired){ads=ads.filter(a=>visibleAd(a));render();}if([root,middle,footer].some(box=>hovered.has(box)||box.matches(':hover')||box.contains(document.activeElement)))return;if(!paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&Date.now()-lastMove>=6000){index++;lastMove=Date.now();render();}},1000);}catch{root.hidden=middle.hidden=footer.hidden=true;}
 return {dispose(){clearInterval(timer);observer.disconnect();},recorder};
}
