import {PLACEMENTS,STATUSES,LABELS,millis,adStatus,visibleAd,placementState,validateAd,summarize,dayKey,ANALYTICS_RELEASE_ENABLED} from './commercial-model.js';
export function installCommercialAdmin(api){
 const {db,auth,collection,doc,getDoc,getDocs,query,where,orderBy,startAfter,limit,runTransaction,serverTimestamp,setDoc,getAccess}=api;
 const owner=()=>getAccess().role==='super_admin'&&getAccess().ready;const esc=api.escapeHtml;let generation=0;
 const button=(text,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>Promise.resolve(fn()).catch(()=>alert('تعذر تنفيذ العملية. تحقق من الصلاحيات والاتصال.'));return b;};
 async function all(name){const rows=[];let cursor;do{const snap=await getDocs(query(collection(db,name),orderBy('__name__'),...(cursor?[startAfter(cursor)]:[]),limit(250)));rows.push(...snap.docs.map(d=>({...d.data(),id:d.id})));if(snap.size<250)break;cursor=snap.docs.at(-1);}while(true);return rows;}
 const date=v=>Number.isFinite(millis(v))?new Date(millis(v)).toLocaleDateString('ar-AE'):'';
 const stats=(host,entries)=>{const wrap=document.createElement('div');wrap.className='admin-stats';wrap.innerHTML=entries.map(([label,n])=>`<article><span>${esc(label)}</span><strong>${n===null?'لا توجد بيانات بعد':esc(String(n))}</strong></article>`).join('');host.append(wrap);};
 async function todayCount(){if(!owner())return null;try{const start=new Date(dayKey()+'T00:00:00+04:00');const snap=await getDocs(query(collection(db,'analyticsSessions'),where('startedAt','>=',start)));return snap.size||null;}catch{return null;}}
 async function render(host,kind){const token=++generation;if(!owner()){host.textContent='غير مصرح';return;}host.classList.add('commercial-admin');host.textContent='جاري تحميل البيانات…';const [ads,sessions]=await Promise.all([kind==='commercialAds'?all('commercialAds'):Promise.resolve([]),all('analyticsSessions')]);if(token!==generation||!host.isConnected)return;host.replaceChildren();const summary=summarize(sessions);
 if(kind==='visitorAnalytics'){
 stats(host,[['جلسات اليوم',sessions.length?summary.today:null],['جلسات آخر 7 أيام',sessions.length?summary.seven:null],['جلسات آخر 30 يومًا',sessions.length?summary.thirty:null],['إجمالي مشاهدات الصفحات',sessions.length?summary.pageViews:null]]);
 const note=document.createElement('p');note.textContent='من البيانات الفعلية المسجلة · الجلسة: استخدام متصل في تبويب واحد، تنتهي بعد 30 دقيقة خمول. مشاهدة الصفحة: فتح الصفحة أو الانتقال بين أقسامها. لا نحدد أشخاصًا فريدين ولا نستخدم معرفًا دائمًا أو IP. التوقيت: الإمارات. البيانات تقديرية من المتصفح ولا تثبت نقرات مدفوعة.';host.append(note);
 const config=await getDoc(doc(db,'platformTelemetry','config'));if(!host.isConnected)return;const enabled=config.data()?.enabled===true;if(ANALYTICS_RELEASE_ENABLED)host.append(button(enabled?'إيقاف جمع الإحصاءات':'تفعيل جمع الإحصاءات',async()=>{if(!owner()||!ANALYTICS_RELEASE_ENABLED)return;await setDoc(doc(db,'platformTelemetry','config'),{enabled:!enabled,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid});return render(host,kind);}));
 const chart=document.createElement('div');chart.className='commercial-analytics-chart';chart.setAttribute('role','img');chart.setAttribute('aria-label','مشاهدات الصفحات آخر 30 يومًا');const dates=Array.from({length:30},(_,i)=>dayKey(Date.now()-(29-i)*86400000)),max=Math.max(1,...dates.map(d=>summary.days[d]?.pageViews||0));for(const d of dates){const n=summary.days[d]?.pageViews||0,bar=document.createElement('div');bar.style.height=(n/max*90)+'%';bar.title=d+': '+n;bar.innerHTML='<span>'+n+'</span>';chart.append(bar);}if(sessions.length)host.append(chart);else host.append(document.createTextNode('لا توجد بيانات بعد'));
 const daily=document.createElement('details');daily.innerHTML='<summary>عرض البيانات اليومية</summary><table><caption>مشاهدات الصفحات حسب اليوم — توقيت الإمارات</caption><thead><tr><th>التاريخ</th><th>المشاهدات</th></tr></thead><tbody>'+dates.map(d=>'<tr><td>'+d+'</td><td>'+(sessions.length?(summary.days[d]?.pageViews||0):'لا توجد بيانات بعد')+'</td></tr>').join('')+'</tbody></table>';host.append(daily);
 const names={home:'الرئيسية',market:'السوق',services:'الخدمات',admin:'الإدارة',other:'أقسام أخرى'};const table=document.createElement('table');table.innerHTML='<caption>أكثر الأقسام زيارة</caption><thead><tr><th>القسم</th><th>مشاهدات الصفحات</th></tr></thead><tbody>'+Object.entries(summary.pages).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<tr><td>${names[p]}</td><td>${sessions.length?n:'لا توجد بيانات بعد'}</td></tr>`).join('')+'</tbody>';host.append(table);return;
 }
 const totals=ads.reduce((t,a)=>{const c=summary.ads[a.id];t[0]+=c?.views||0;t[1]+=c?.clicks||0;return t;},[0,0]);stats(host,[['إجمالي الإعلانات',ads.length],['النشطة الآن',ads.filter(a=>visibleAd(a)).length],['المعلقة',ads.filter(a=>a.status==='pending').length],['المنتهية',ads.filter(a=>adStatus(a)==='expired').length],['المشاهدات المسجلة',sessions.length?totals[0]:null],['النقرات المسجلة',sessions.length?totals[1]:null]]);
 const tools=document.createElement('div');tools.className='commercial-tools';tools.innerHTML='<input aria-label="بحث باسم الإعلان أو المعلن" placeholder="اسم الإعلان أو المعلن"><select aria-label="حالة الإعلان"><option value="">كل الحالات</option>'+STATUSES.map(s=>`<option value="${s}">${LABELS[s]}</option>`).join('')+'</select><select aria-label="مكان الإعلان"><option value="">كل الأماكن</option>'+PLACEMENTS.map(p=>`<option value="${p}">${LABELS[p]}</option>`).join('')+'</select><label>نشط في تاريخ<input type="date" aria-label="تاريخ الإعلان"></label>';tools.append(button('إضافة إعلان جديد',()=>form(host,null)));host.append(tools);
 const map=document.createElement('div');map.className='commercial-map';map.setAttribute('aria-label','خريطة الإعلانات');const tableWrap=document.createElement('div');tableWrap.className='commercial-table-wrap';host.append(button('خريطة الإعلانات',()=>{map.hidden=!map.hidden;}),map,tableWrap);
 for(const place of PLACEMENTS){const candidates=ads.filter(a=>a.placement===place).sort((a,b)=>Number(visibleAd(b))-Number(visibleAd(a))||b.priority-a.priority);const a=candidates[0],slot=document.createElement('article');slot.dataset.state=placementState(a);slot.innerHTML=`<h3>${LABELS[place]}</h3><p>${a?esc(a.title):'فارغ'}</p><p>${a?(visibleAd(a)?'نشط':placementState(a)==='scheduled'?'مجدول':LABELS[adStatus(a)])+' · '+date(a.endAt):'لا يوجد إعلان'}</p>`;slot.append(button('تغيير الإعلان',()=>{tools.querySelectorAll('select')[1].value=place;draw();tableWrap.scrollIntoView({block:'nearest'});}));slot.append(button('إضافة لهذا المكان',()=>form(host,null,place)));map.append(slot);}
 let page=0;const [search,status,placement,dateInput]=tools.querySelectorAll('input,select');
 function draw(){const term=search.value.trim().toLowerCase(),at=dateInput.value?Date.parse(dateInput.value+'T12:00:00+04:00'):null;const rows=ads.filter(a=>(!term||(a.title+' '+a.advertiserName).toLowerCase().includes(term))&&(!status.value||adStatus(a)===status.value)&&(!placement.value||a.placement===placement.value)&&(!at||millis(a.startAt)<=at&&millis(a.endAt)>at)).sort((a,b)=>b.priority-a.priority);page=Math.min(page,Math.max(0,Math.ceil(rows.length/20)-1));tableWrap.innerHTML='<table><caption>قائمة الإعلانات التجارية — '+rows.length+'</caption><thead><tr>'+['الصورة','الإعلان / المعلن','المكان','الحالة','البداية','النهاية','المشاهدات','النقرات','الإجراءات'].map(t=>'<th>'+t+'</th>').join('')+'</tr></thead><tbody></tbody></table>';const body=tableWrap.querySelector('tbody');for(const a of rows.slice(page*20,(page+1)*20)){const row=document.createElement('tr'),c=summary.ads[a.id];row.innerHTML=`<td><img src="${esc(a.imageUrl)}" alt="${esc(a.title)}" loading="lazy" width="76" height="48"></td><td>${esc(a.title)}<br><small>${esc(a.advertiserName)}</small></td><td>${LABELS[a.placement]}</td><td>${LABELS[adStatus(a)]}${a.status==='active'&&millis(a.startAt)>Date.now()?' — مجدول':''}</td><td>${date(a.startAt)}</td><td>${date(a.endAt)}</td><td>${sessions.length?c?.views||0:'لا توجد بيانات بعد'}</td><td>${sessions.length?c?.clicks||0:'لا توجد بيانات بعد'}</td><td></td>`;row.lastElementChild.append(button('تعديل',()=>form(host,a)),button(a.status==='active'?'إيقاف':'تفعيل',()=>form(host,{...a,status:a.status==='active'?'paused':'active'})));body.append(row);}const prev=button('السابق',()=>{page--;draw();}),next=button('التالي',()=>{page++;draw();});prev.disabled=page===0;next.disabled=(page+1)*20>=rows.length;tableWrap.append(prev,document.createTextNode(' '+(page+1)+' '),next);}
 for(const el of [search,status,placement,dateInput])el.oninput=()=>{page=0;draw();};draw();
 }
 async function form(host,ad,placement='hero'){
 if(!owner())return;const contact=ad?(await getDoc(doc(db,'commercialAdContacts',ad.id))).data()||{}:{};if(!host.isConnected)return;const restoreFocus=document.activeElement;const dialog=document.createElement('dialog');dialog.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const nodes=[...dialog.querySelectorAll('button,input,select')].filter(x=>!x.disabled&&x.getClientRects().length);if(event.shiftKey&&document.activeElement===nodes[0]){event.preventDefault();nodes.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===nodes.at(-1)){event.preventDefault();nodes[0]?.focus();}});dialog.setAttribute('aria-label',ad?'تعديل الإعلان':'إضافة إعلان جديد');const close=button('إغلاق',()=>dialog.close());dialog.append(close);const form=document.createElement('form');form.className='commercial-ad-form';const defaults={title:'',advertiserName:'',description:'',cta:'تعرف على المزيد',imageUrl:'',targetUrl:'',placement,status:'draft',priority:0,...ad,...contact};
 for(const [key,label,type] of [['title','اسم الإعلان','text'],['advertiserName','اسم المعلن','text'],['advertiserEmail','بريد المعلن — خاص بالإدارة','email'],['advertiserPhone','هاتف المعلن — خاص بالإدارة','tel'],['imageUrl','رابط صورة Cloudinary المضغوطة','url'],['targetUrl','رابط الهدف HTTPS','url'],['description','وصف مختصر','text'],['cta','نص الزر','text'],['startAt','تاريخ البداية','datetime-local'],['endAt','تاريخ النهاية','datetime-local'],['priority','الأولوية','number']]){const labelNode=document.createElement('label');labelNode.textContent=label;const input=document.createElement('input');input.name=key;input.type=type;input.required=!['advertiserEmail','advertiserPhone','description'].includes(key);input.maxLength=key==='description'?300:key==='cta'?40:key.includes('Url')?2000:120;if(type==='number'){input.min=0;input.max=999;}input.value=type==='datetime-local'&&defaults[key]?new Date(millis(defaults[key])-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):defaults[key]??'';labelNode.append(input);form.append(labelNode);}
 for(const [key,values] of [['placement',PLACEMENTS],['status',STATUSES]]){const label=document.createElement('label');label.textContent=key==='placement'?'المكان':'الحالة';const select=document.createElement('select');select.name=key;select.innerHTML=values.map(v=>`<option value="${v}">${LABELS[v]}</option>`).join('');select.value=defaults[key];label.append(select);form.append(label);}
 const save=document.createElement('button');save.type='submit';save.textContent='حفظ الإعلان';const error=document.createElement('p');error.setAttribute('role','alert');form.append(save,error);dialog.append(form);host.append(dialog);dialog.addEventListener('close',()=>{dialog.remove();if(restoreFocus?.isConnected)restoreFocus.focus();});dialog.showModal();close.focus();
 form.onsubmit=async event=>{event.preventDefault();if(!owner())return;const values=Object.fromEntries(new FormData(form));const next={title:values.title.trim(),advertiserName:values.advertiserName.trim(),description:values.description,cta:values.cta,imageUrl:values.imageUrl,targetUrl:values.targetUrl,placement:values.placement,status:values.status,priority:Number(values.priority),startAt:new Date(values.startAt),endAt:new Date(values.endAt)};if(!validateAd(next)){error.textContent='تحقق من رابط الصورة والهدف HTTPS والتواريخ والحقول.';return;}save.disabled=true;try{const ref=ad?doc(db,'commercialAds',ad.id):doc(collection(db,'commercialAds'));await runTransaction(db,async tx=>{const old=await tx.get(ref);if(!owner())throw Error('denied');tx.set(ref,{...next,createdAt:old.exists()?old.data().createdAt:serverTimestamp(),createdBy:old.exists()?old.data().createdBy:auth.currentUser.uid,updatedAt:serverTimestamp(),updatedBy:auth.currentUser.uid,approvedBy:['active','approved'].includes(next.status)?auth.currentUser.uid:'',approvedAt:['active','approved'].includes(next.status)?serverTimestamp():null});tx.set(doc(db,'commercialAdContacts',ref.id),{advertiserEmail:values.advertiserEmail,advertiserPhone:values.advertiserPhone});});dialog.close();await render(host,'commercialAds');}catch{error.textContent='تعذر الحفظ. لم يتم تأكيد العملية.';save.disabled=false;}};
 }
 return {render,todayCount};
}
