import assert from 'node:assert/strict';
import {accessModel,can,canDelegate,PERMISSIONS} from '../admin-permissions.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS | '+name);};
const config={enabled:true,superAdminUids:['owner']};
const record={role:'admin_assistant',adminStatus:'active',permissions:['users_view','assistants_create']};
const assistant=accessModel('helper',{}, {},record,config);
const owner=accessModel('owner',{admin:true},{},null,config);
test('21 distinct permissions',()=>assert.equal(new Set(PERMISSIONS).size,21));
test('ordinary user denied',()=>assert.equal(can(accessModel('normal'),'dashboard_view'),false));
test('legacy claim retains Super Admin without migration',()=>assert.equal(accessModel('owner',{admin:true}).role,'super_admin'));
test('migration disabled prevents delegation',()=>assert.equal(accessModel('owner',{admin:true},{},null,{...config,enabled:false}).ready,false));
test('assistant needs initialized config',()=>assert.equal(accessModel('helper',{},{},record).role,null));
test('active assistant has only explicit permission',()=>assert.equal(can(assistant,'users_block'),false));
test('view permission allowed',()=>assert.equal(can(assistant,'users_view'),true));
test('suspended assistant denied',()=>assert.equal(accessModel('helper',{},{},{...record,adminStatus:'suspended'},config).role,null));
test('blocked account denied',()=>assert.equal(accessModel('helper',{}, {status:'blocked'},record,config).role,null));
test('null account status fails closed like Rules',()=>assert.equal(accessModel('owner',{admin:true},{status:null}).role,null));
test('document cannot grant Super Admin',()=>assert.equal(accessModel('normal',{},{},{role:'super_admin'},config).role,null));
test('self elevation denied',()=>assert.equal(canDelegate(assistant,'helper',record,record.permissions,'assistants_create'),false));
test('owner modification denied',()=>assert.equal(canDelegate(assistant,'owner',null,[],'assistants_create'),false));
test('unknown permission denied',()=>assert.equal(canDelegate(owner,'other',null,['fake'],'assistants_create'),false));
test('higher privilege grant denied',()=>assert.equal(canDelegate(assistant,'other',null,['users_block'],'assistants_create'),false));
test('higher privilege target downgrade denied',()=>assert.equal(canDelegate(assistant,'other',{permissions:['users_block']},[],'assistants_create'),false));
test('explicit subset grant allowed',()=>assert.equal(canDelegate(assistant,'other',null,['users_view'],'assistants_create'),true));
test('owner can grant all permissions to assistant',()=>assert.equal(canDelegate(owner,'other',null,PERMISSIONS,'assistants_create'),true));
console.log(`SUMMARY | ${n}/${n} passed`);
