const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');let n=0;const pass=s=>{n++;console.log('PASS '+s)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname!=='notify.test')throw Error('External traffic');if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:'<html dir="rtl"><link rel="stylesheet" href="/admin-dashboard.css"><body><div class="admin-v3"><header class="admin-header-tools" id="host"></header></div></body></html>'});return r.fulfill({contentType:u.pathname.endsWith('.js')?'text/javascript':'text/css',body:fs.readFileSync(path.join(root,u.pathname))});});await page.goto('https://notify.test/');
await page.evaluate(async()=>{const {installAdminNotifications}=await import('./admin-notifications.js');window.rows={};window.reads=[];window.role='super_admin';window.uid='owner';window.allowed=['reports'];window.opened=[];const api={db:{},auth:{get currentUser(){return {uid:window.uid}}},getAccess:()=>({role:window.role,permissions:window.allowed}),requireAdminClaim:async()=>true,collection:(db,k)=>k,where:(f,op,v)=>v,limit:n=>n,query:(k,status,limit)=>({k,status,limit}),getDocs:async q=>{window.reads.push(q);if(window.fail===q.k)throw Error('offline');return {docs:(window.rows[q.k]||[]).filter(d=>d.status===q.status).slice(0,q.limit).map(d=>({id:d.id,data:()=>d}))}}};window.inbox=installAdminNotifications(api,k=>window.role==='super_admin'||window.allowed.includes(k),async k=>window.opened.push(k));window.mount=()=>{document.getElementById('host').replaceChildren();window.inbox.mount(document.getElementById('host'))};window.mount();});
const refresh=async()=>{await page.locator('[data-refresh]').click();await page.waitForFunction(()=>!document.querySelector('[data-refresh]').disabled)};
await page.locator('.admin-notification-bell').click();await page.getByText('لا توجد إشعارات جديدة',{exact:true}).waitFor();assert.equal(await page.locator('[data-count]').isVisible(),false);pass('zero notifications');
await page.evaluate(()=>window.rows.purchaseRequests=[{id:'buy',status:'pending',createdAt:new Date()}]);await refresh();assert.equal(await page.locator('[data-count]').innerText(),'1');await page.locator('.admin-notification-item').click();assert.equal(await page.locator('[data-count]').isVisible(),false);assert.deepEqual(await page.evaluate(()=>window.opened),['purchaseRequests']);pass('one purchase, open destination, immediate seen');
await page.evaluate(()=>{window.rows.serviceRequests=[{id:'service',status:'pending'},{id:'featured',status:'pending',serviceType:'featured'}];window.rows.reports=[{id:'report',status:'open'}];window.rows.commercialAds=[{id:'ad',status:'pending'}];});await refresh();assert.equal(await page.locator('[data-count]').innerText(),'4');for(const title of ['طلب خدمة جديد','طلب تمييز إعلان','بلاغ جديد','إعلان تجاري قيد المراجعة']){assert.equal(await page.locator('.admin-notification-item').filter({hasText:title}).count(),1);pass(title)}
for(const [title,tab]of [['طلب خدمة جديد','services'],['طلب تمييز إعلان','services'],['بلاغ جديد','reports'],['إعلان تجاري قيد المراجعة','commercialAds']]){await page.locator('.admin-notification-item').filter({hasText:title}).click();assert.equal(await page.evaluate(()=>window.opened.at(-1)),tab);}pass('all linked destinations');
await page.evaluate(()=>{window.rows.reports.push({id:'new',status:'open'});});await refresh();await page.locator('[data-all]').click();assert.equal(await page.locator('[data-count]').isVisible(),false);await page.evaluate(()=>window.mount());await page.locator('.admin-notification-bell').click();assert.equal(await page.locator('[data-count]').isVisible(),false);pass('mark all and UID-local persistence');
for(const width of [1366,768,430,390,360]){await page.setViewportSize({width,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('[data-refresh]').focus();await page.keyboard.press('Escape');assert.equal(await page.locator('section').isVisible(),false);assert.equal(await page.locator('.admin-notification-bell').evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('section').isVisible(),true);pass('responsive RTL keyboard '+width)}
await page.evaluate(()=>{window.role='admin_assistant';window.uid='helper';window.reads=[];window.mount()});await page.locator('.admin-notification-bell').click();await page.waitForFunction(()=>!document.querySelector('[data-refresh]').disabled);assert.equal(await page.locator('.admin-notification-item').count(),2);assert.ok((await page.evaluate(()=>window.reads)).every(q=>q.k==='reports'&&q.limit===20));assert.equal(await page.locator('[data-count]').innerText(),'2');pass('assistant reads and sees reports only, distinct seen state');
await page.evaluate(()=>window.fail='reports');await refresh();await page.getByText('تعذر تحميل بعض الأقسام. أعد التحديث.',{exact:true}).waitFor();pass('read failures do not report false empty success');
assert.deepEqual(errors,[]);pass('zero JavaScript errors');console.log('SUMMARY '+n+'/'+n+' PASS');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
