const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {installMock,seedMock}=require('./user-seller-fixture.cjs');
const root=path.resolve(__dirname,'..'),shots=path.join(require('os').tmpdir(),'souq-featured-visual');fs.mkdirSync(shots,{recursive:true});
const names=[...fs.readFileSync(path.join(root,'app.js'),'utf8').matchAll(/import\s*\{([^}]+)\}/g)].flatMap(m=>m[1].split(',').map(s=>s.trim()));
let count=0;const pass=n=>{count++;console.log('PASS | '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(installMock);
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:names.map(n=>`export const ${n}=window.__mock.api.${n};`).join('\n')});if(u.hostname!=='ux.test')return route.abort();const file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain',body:fs.readFileSync(file)});});
await page.goto('https://ux.test/');await page.waitForFunction(()=>typeof window.selectMarketCountry==='function');await page.evaluate(seedMock);
await page.evaluate(async()=>{const m=window.__mock;m.admin=true;m.docs.set('adminSecurity/config',{enabled:true,superAdminUids:['owner']});m.docs.set('adminAccess/owner',{role:'super_admin',adminStatus:'active'});await m.setUser({uid:'owner',displayName:'مالك تجريبي'});for(const key of [...m.docs.keys()])if(key.startsWith('serviceRequests/'))m.docs.delete(key);for(const pay of ['paid','unpaid'])m.docs.set('serviceRequests/'+pay,{userId:'seller',targetId:'direct',targetType:'animal',serviceType:'featured',country:'AE',status:'pending',paymentStatus:pay,createdAt:new Date(),updatedAt:new Date()});await window.openAdminServices();});
const primary=page.locator('button[data-brand=primary]:enabled').filter({hasText:'اعتماد مدفوع'}),secondary=page.getByRole('button',{name:'اعتماد بدون دفع'}),danger=page.getByRole('button',{name:'رفض',exact:true}).first(),disabled=page.locator('button[data-brand=primary]:disabled');
const colors=async el=>el.evaluate(e=>{const s=getComputedStyle(e);return [s.backgroundColor,s.color,s.borderTopColor,s.minHeight,s.borderRadius]});
assert.deepEqual((await colors(primary)).slice(0,2),['rgb(18, 83, 64)','rgb(255, 255, 255)']);pass('primary green');assert.deepEqual((await colors(secondary)).slice(0,2),['rgb(241, 228, 197)','rgb(102, 72, 23)']);pass('soft gold');assert.deepEqual((await colors(danger)).slice(0,2),['rgb(255, 255, 255)','rgb(161, 47, 56)']);pass('danger outline');assert.equal((await colors(disabled))[0],'rgb(237, 240, 238)');pass('disabled gray');
for(const el of [primary,secondary,danger,disabled])assert.deepEqual((await colors(el)).slice(3),['44px','10px']);pass('consistent dimensions');await primary.hover();await page.waitForTimeout(180);assert.notEqual(await primary.evaluate(e=>getComputedStyle(e).filter),'none');pass('hover');await primary.focus();assert.equal(await primary.evaluate(e=>getComputedStyle(e).outlineStyle),'solid');pass('keyboard focus');
for(const width of [1366,768,430,390,360]){await page.setViewportSize({width,height:1100});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await primary.evaluate(e=>getComputedStyle(e).direction),'rtl');pass('responsive RTL '+width);if(width===1366||width===360)await page.screenshot({path:path.join(shots,'admin-buttons-'+width+'.png'),fullPage:true});}
assert.deepEqual(errors,[]);pass('zero JavaScript errors');console.log('SUMMARY | '+count+'/'+count+' PASS');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
