import assert from 'node:assert/strict';
import {heroSlots,selectAds,visibleAd,adStatus,safeUrl,validateAd,summarize,createRecorder,pageSection,placementState} from '../commercial-model.js';
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS | '+name);};const now=Date.UTC(2026,8,12,12),ad={id:'ad1',title:'تجربة',advertiserName:'معلن',description:'',cta:'المزيد',imageUrl:'https://res.cloudinary.com/demo/image/upload/sample.jpg',targetUrl:'https://example.com/',placement:'hero',status:'active',priority:1,startAt:new Date(now-1000),endAt:new Date(now+1000)};
test('valid commercial schema',()=>assert.ok(validateAd(ad)));
test('hero cap ten with priority',()=>{const rows=selectAds(Array.from({length:14},(_,i)=>({...ad,id:'ad'+i,priority:i})),'hero',now);assert.equal(rows.length,10);assert.equal(rows[0].priority,13);});
for(const status of ['pending','paused','rejected','draft','approved','expired'])test(status+' hidden',()=>assert.equal(visibleAd({...ad,status},now),false));
test('inclusive expiry boundary',()=>assert.equal(visibleAd({...ad,endAt:new Date(now)},now),true));
test('future start hidden',()=>assert.equal(visibleAd({...ad,startAt:new Date(now+1)},now),false));
test('inclusive start boundary',()=>assert.equal(visibleAd({...ad,startAt:new Date(now)},now),true));
test('effective expired state',()=>assert.equal(adStatus({...ad,endAt:new Date(now-1)},now),'expired'));
for(const placement of ['hero_side_1','hero_side_2','hero_side_3','middle','footer_1','footer_2','footer_3','footer_4','footer_5'])test(placement+' single slot',()=>assert.equal(selectAds([{...ad,placement},{...ad,id:'b',placement}],placement,now).length,1));
for(const url of ['javascript:alert(1)','data:text/html,x','http://example.com','https://user:pass@example.com'])test('unsafe URL rejected '+url.split(':')[0],()=>assert.equal(safeUrl(url),''));
test('arbitrary image host rejected',()=>assert.equal(safeUrl('https://example.com/x.jpg',true),''));
test('invalid schedule rejected',()=>assert.equal(!!validateAd({...ad,endAt:ad.startAt}),false));
const sessions=[{startedAt:new Date(now),pageViews:3,pages:{home:2,market:1},views:['ad1'],clicks:['ad1']},{startedAt:new Date(now-6*86400000),pageViews:1,pages:{home:1},views:['ad1'],clicks:[]},{startedAt:new Date(now-29*86400000),pageViews:1,pages:{home:1},views:[],clicks:[]}];
test('session windows and totals',()=>{const s=summarize(sessions,now);assert.deepEqual([s.today,s.seven,s.thirty,s.pageViews],[1,2,3,5]);});
test('ad counts from sessions',()=>assert.deepEqual(summarize(sessions,now).ads.ad1,{views:2,clicks:1}));
test('empty data no invented visits',()=>assert.equal(summarize([],now).sessions,0));
let persisted=null;const storage={getItem:()=>persisted,setItem:(k,v)=>persisted=v},writes=[];const r=createRecorder({storage,random:()=> 'a'.repeat(32),write:async s=>writes.push(s),now:()=>now,schedule:()=>1});
test('page counted not render',()=>{assert.equal(r.record('page','home'),true);assert.equal(r.state.pageViews,1);assert.equal(writes.length,0);});
test('view session dedupe',()=>{assert.equal(r.record('views','ad1'),true);assert.equal(r.record('views','ad1'),false);});
test('click session dedupe',()=>{assert.equal(r.record('clicks','ad1'),true);assert.equal(r.record('clicks','ad1'),false);});
await r.flush();test('one batch write',()=>assert.equal(writes.length,1));
test('reload preserves dedupe',()=>{const again=createRecorder({storage,random:()=> 'b'.repeat(32),write:async()=>{},now:()=>now,schedule:()=>1});assert.equal(again.record('views','ad1'),false);});
test('no user or device fields',()=>assert.deepEqual(Object.keys(r.state).sort(),['clicks','created','id','last','pageViews','pages','start','views'].sort()));
test('privacy opt-out',()=>assert.equal(createRecorder({storage,random:()=>'',write:async()=>{},blocked:true}).record('page','home'),false));
let clock=now;const changing=createRecorder({storage:{getItem:()=>null,setItem:()=>{}},random:()=>String(clock),write:async()=>{},now:()=>clock,schedule:()=>1});changing.record('page','home');const first=changing.state.id;clock+=1800001;test('idle expires session',()=>{changing.record('page','home');assert.notEqual(changing.state.id,first);assert.equal(changing.state.pageViews,1);});
for(const [hash,expected] of [['','home'],['#home','home'],['#market','market'],['#direct','market'],['#auction','market'],['#services','services'],['#contact','other'],['#unknown','other']])test('section attribution '+hash,()=>assert.equal(pageSection(hash),expected));
for(const [entry,expected] of [[null,'empty'],[ad,'soon'],[{...ad,endAt:new Date(now+5*86400000)},'active'],[{...ad,endAt:new Date(now-1)},'expired'],[{...ad,status:'paused'},'paused'],[{...ad,startAt:new Date(now+1)},'scheduled']])test('map state '+expected,()=>assert.equal(placementState(entry,now),expected));
for(const patch of [{startAt:undefined},{endAt:undefined},{startAt:null},{endAt:null}])test('missing date denied '+Object.keys(patch)[0],()=>assert.equal(visibleAd({...ad,...patch},now),false));
console.log(`SUMMARY | ${n}/${n} passed`);

test('hero requested slots and safe duplicate allocation',()=>{const rows=[{...ad,id:'a',priority:10},{...ad,id:'b',priority:10},{...ad,id:'c',priority:7}];const plan=heroSlots(rows);assert.equal(plan[0].ad.id,'a');assert.equal(plan[1].ad.id,'b');assert.equal(plan[3].ad.id,'c');assert.equal(plan[1].relocated,true);assert.equal(new Set(plan.filter(Boolean).map(x=>x.slot)).size,3);assert.deepEqual(heroSlots([...rows].reverse()),plan);});
test('hero overflow selection excludes lower priorities',()=>{const plan=heroSlots(Array.from({length:11},(_,i)=>({...ad,id:String(i),priority:11-i}))).filter(Boolean);assert.equal(plan.length,10);assert.equal(plan.some(x=>x.ad.id==='10'),false);});
console.log(`FINAL SUMMARY | ${n}/${n} passed`);