const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');let count=0;const pass=name=>{count++;console.log('PASS | '+name)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage();const errors=[],external=[];let configured=false,mode='success',uploads=0,signs=0;
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const u=new URL(route.request().url());
  if(u.pathname==='/sign-image'){signs++;assert.equal(route.request().postDataJSON().purpose,'commercial_ad');if(mode==='denied')return route.fulfill({status:403,body:''});return route.fulfill({json:{cloudName:'demo',apiKey:'fixture-key',signature:'fixture-signature',resourceType:'image',expiresAt:Math.floor(Date.now()/1000)+3600,params:{timestamp:Math.floor(Date.now()/1000),folder:'souq-alhalal/commercial-ads',public_id:'12345678-1234-4123-8123-123456789abc',overwrite:false,upload_preset:'commercial_ads_signed_v1',transformation:'c_limit,w_1600,h_1600',allowed_formats:'jpg,jpeg,png,webp'}}});}
  if(u.hostname==='api.cloudinary.com'){uploads++;if(mode==='upload-failure')return route.fulfill({status:500,body:''});return route.fulfill({json:{resource_type:'image',public_id:'souq-alhalal/commercial-ads/12345678-1234-4123-8123-123456789abc',format:'jpg',bytes:1024,width:1600,height:800,secure_url:mode==='invalid-url'?'https://evil.test/image.jpg':'https://res.cloudinary.com/demo/image/upload/souq-alhalal/commercial-ads/12345678-1234-4123-8123-123456789abc.jpg'}});}
  if(u.hostname!=='image.test'){external.push(u.origin);return route.abort();}
  if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/commercial.css"><form id="form"><select aria-label="المكان"><option value="hero">رئيسي</option><option value="middle">وسط</option><option value="footer_1">أسفل</option></select><div id="host"></div><button id="save" type="submit">حفظ</button></form><script type="module">import {createAdImagePicker} from "/commercial-image.js";window.saves=0;window.picker=createAdImagePicker({host:document.querySelector("#host"),placement:()=>document.querySelector("select").value,user:()=>({getIdToken:async()=>"fixture-token"}),onChange:s=>document.querySelector("#save").disabled=s.busy||!s.imageUrl});document.querySelector("select").onchange=()=>picker.placementChanged();document.querySelector("form").onsubmit=e=>{e.preventDefault();if(!picker.getState().busy&&picker.getState().imageUrl)saves++;};</script></html>'});
  const file=path.join(root,u.pathname);if(!file.startsWith(root)||!fs.existsSync(file))return route.fulfill({status:404,body:''});let body=fs.readFileSync(file);if(u.pathname==='/trusted-backend-client.js'&&configured)body=body.toString().replace('TRUSTED_BACKEND_ENABLED = false','TRUSTED_BACKEND_ENABLED = true').replace("signingEndpoint:''","signingEndpoint:'https://image.test/sign-image'");return route.fulfill({contentType:u.pathname.endsWith('.css')?'text/css':'text/javascript',body});
 });
 const open=async()=>{await page.goto('https://image.test/');await page.waitForFunction(()=>!!window.picker);};
 const photo=async(type='image/png',width=1600,height=800)=>Buffer.from(await page.evaluate(({type,width,height})=>{const c=document.createElement('canvas');c.width=width;c.height=height;const ctx=c.getContext('2d');ctx.fillStyle='#007d69';ctx.fillRect(0,0,width,height);return c.toDataURL(type).split(',')[1];},{type,width,height}),'base64');
 const pick=async(buffer,name='test.png',mimeType='image/png')=>{await page.locator('input[type=file]').setInputFiles({name,mimeType,buffer});await page.waitForFunction(()=>!picker.getState().busy);};
 const status=()=>page.locator('[role=status]').textContent();
 await open();assert.equal(await page.locator('input[type=url]').count(),0);assert.ok((await page.locator('.image-guidance').textContent()).includes('1600'));assert.equal(await page.locator('#save').isDisabled(),true);pass('manual URL removed, guidance shown before choosing');
 const png=await photo();await pick(png);assert.equal(await page.locator('img').isVisible(),true);assert.match(await page.locator('.image-info').textContent(),/test.png.*1600 × 800.*بعد الضغط/);pass('picker preview filename size dimensions compression');
 assert.equal(await page.getByRole('button',{name:'رفع الصورة',exact:true}).isDisabled(),true);assert.equal(await page.locator('#save').isDisabled(),true);assert.equal(signs+uploads,0);pass('unconfigured backend blocks uploads and save without network');
 await page.getByRole('button',{name:'إزالة',exact:true}).click();assert.equal(await page.locator('img').isVisible(),false);assert.equal(await page.evaluate(()=>picker.getState().imageUrl),'');pass('remove revokes selection and blocks save');
 await pick(Buffer.from('not image'),'bad.svg','image/svg+xml');assert.match(await status(),/JPG/);pass('unsupported type rejected');
 await pick(Buffer.alloc(10*1024*1024+1),'big.jpg','image/jpeg');assert.match(await status(),/10 MB/);pass('large file rejected before decode');
 await pick(Buffer.from('bad png'));assert.match(await status(),/تعذر قراءة/);pass('invalid bytes rejected');
 await pick(await photo('image/png',200,100));assert.match(await status(),/الحد الأدنى/);pass('placement minimum dimensions checked');
 await pick(await photo('image/png',1000,1000));assert.match(await status(),/بنسبة/);pass('placement ratio checked');
 configured=true;await open();for(const [name,type] of [['photo.jpg','image/jpeg'],['photo.jpeg','image/jpeg'],['photo.webp','image/webp'],['photo.png','image/png']]){await pick(await photo(type),name,type);assert.equal(await page.locator('img').isVisible(),true);pass('supported '+name);}
 assert.equal(await page.locator('#save').isDisabled(),true);await page.evaluate(()=>document.querySelector('form').requestSubmit());assert.equal(await page.evaluate(()=>saves),0);pass('save cannot run before upload');
 mode='denied';await page.getByRole('button',{name:'رفع الصورة',exact:true}).click();await page.waitForFunction(()=>!picker.getState().busy);assert.match(await status(),/فشل/);assert.equal(await page.locator('#save').isDisabled(),true);pass('signing failure leaves save blocked');
 mode='upload-failure';await page.getByRole('button',{name:'رفع الصورة',exact:true}).click();await page.waitForFunction(()=>!picker.getState().busy);assert.equal(await page.locator('#save').isDisabled(),true);pass('provider upload failure leaves save blocked');
 mode='invalid-url';await page.getByRole('button',{name:'رفع الصورة',exact:true}).click();await page.waitForFunction(()=>!picker.getState().busy);assert.equal(await page.locator('#save').isDisabled(),true);pass('invalid provider URL rejected');
 mode='success';await page.getByRole('button',{name:'رفع الصورة',exact:true}).click();await page.waitForFunction(()=>!!picker.getState().imageUrl);assert.equal(await page.locator('#save').isDisabled(),false);await page.locator('#save').click();assert.equal(await page.evaluate(()=>saves),1);pass('signed fixture upload unlocks save only on valid image URL');
 await pick(png,'replacement.png');assert.equal(await page.evaluate(()=>picker.getState().imageUrl),'');assert.equal(await page.locator('#save').isDisabled(),true);pass('changing image invalidates prior upload');
 await page.getByLabel('المكان').selectOption('middle');await page.waitForFunction(()=>!picker.getState().busy);assert.match(await status(),/بنسبة/);assert.equal(await page.locator('#save').isDisabled(),true);pass('changing placement revalidates ratio');
 const wide=await photo('image/png',1600,400);await page.evaluate(base64=>{const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([bytes],'drop.png',{type:'image/png'}));document.querySelector('fieldset').dispatchEvent(new DragEvent('drop',{dataTransfer:dt,bubbles:true,cancelable:true}));},wide.toString('base64'));await page.waitForFunction(()=>!picker.getState().busy);assert.match(await page.locator('.image-info').textContent(),/drop.png/);pass('desktop drag and drop');
 for(const width of [1440,390,360]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);pass('responsive picker '+width);}
 const chooserPromise=page.waitForEvent('filechooser');await page.getByRole('button',{name:'تغيير الصورة',exact:true}).click();const chooser=await chooserPromise;assert.equal(chooser.isMultiple(),false);pass('mobile device picker uses native single-file chooser');
 assert.equal(await page.locator('img').getAttribute('alt'),'معاينة صورة الإعلان');assert.equal(await page.locator('[aria-live=polite]').count(),1);await page.getByRole('button',{name:'تغيير الصورة',exact:true}).focus();assert.equal(await page.evaluate(()=>document.activeElement.textContent),'تغيير الصورة');pass('accessible naming status and keyboard controls');
 for(const file of ['commercial-image.js','commercial-admin.js','image-provider.js'])assert.doesNotMatch(fs.readFileSync(path.join(root,file),'utf8'),/api_secret\s*[:=]|BEGIN (?:RSA )?PRIVATE KEY/i);assert.match(fs.readFileSync(path.join(root,'image-provider.js'),'utf8'),/signingEndpoint: ''/);pass('client contains no signing secret and real endpoint remains unconfigured');
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);pass('zero critical JS errors and zero live network');console.log(`SUMMARY | ${count}/${count} passed`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
