const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {installMock,seedMock}=require('./user-seller-fixture.cjs');
const root=path.resolve(__dirname,'..'),shots=path.join(require('os').tmpdir(),'souq-featured-visual');fs.mkdirSync(shots,{recursive:true});
const names=[...fs.readFileSync(path.join(root,'app.js'),'utf8').matchAll(/import\s*\{([^}]+)\}/g)].flatMap(m=>m[1].split(',').map(s=>s.trim()));
let count=0;const pass=n=>{count++;console.log('PASS | '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(installMock);
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:names.map(n=>`export const ${n}=window.__mock.api.${n};`).join('\n')});if(u.hostname!=='ux.test')return route.abort();const file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain',body:fs.readFileSync(file)});});
await page.goto('https://ux.test/');await page.waitForFunction(()=>typeof window.selectMarketCountry==='function');await page.evaluate(seedMock);

await page.evaluate(async()=>{const d=window.__mock.docs,base=d.get('animals/direct');for(const k of [...d.keys()])if(k.startsWith('animals/'))d.delete(k);for(const id of ['normal','featured','pending','rejected','expired'])d.set('animals/'+id,{...base,name:id==='featured'?'ناقة مميزة':id==='normal'?'ناقة للبيع':id,featuredUntil:id==='featured'?new Date(Date.now()+3600000):id==='expired'?new Date(0):undefined,createdAt:new Date(id==='normal'?Date.now():0)});d.set('serviceRequests/pending',{targetId:'pending',status:'pending',serviceType:'featured'});d.set('serviceRequests/rejected',{targetId:'rejected',status:'rejected',serviceType:'featured'});d.set('animals/auction-animal',{...base,saleType:'auction',auctionId:'auction'});d.get('auctions/auction').featuredUntil=new Date(Date.now()+3600000);await window.applyMarketFilters()});
await page.waitForFunction(()=>document.querySelector('[data-animal-id="featured"]'));
const card=id=>page.locator('[data-animal-id="'+id+'"]').first();
assert.equal(await card('featured').locator('.listing-featured-badge').innerText(),'إعلان مميز');pass('approved active listing uses actual promotion expiry');
for(const id of ['normal','pending','rejected','expired']){assert.equal(await card(id).locator('.listing-featured-badge').count(),0);pass(id+' normal style');}
assert.equal(await page.locator('#direct-sales .v2-card').first().getAttribute('data-animal-id'),'featured');pass('featured-first sorting');
assert.equal(await card('auction-animal').locator('.listing-featured-badge').count(),1);pass('auction uses its own approved promotion');
const photo=fs.readFileSync(path.join(root,'hero-livestock.png')).toString('base64');await page.evaluate(async photo=>{const img=new Image();img.src='data:image/png;base64,'+photo;await img.decode();const c=document.createElement('canvas');c.width=640;c.height=400;c.getContext('2d').drawImage(img,0,0,640,400);const src=c.toDataURL('image/jpeg');for(const id of ['normal','featured'])window.__mock.docs.get('animals/'+id).images=id==='featured'?[src,src,src]:[src];await window.applyMarketFilters()},photo);
await page.waitForFunction(()=>document.querySelector('[data-animal-id="featured"] .v2-thumbnails'));
await card('featured').locator('[data-dot="1"]').click();assert.equal(await card('featured').locator('.v2-gallery').getAttribute('data-index'),'1');pass('three-image gallery swaps main image');assert.equal(await card('normal').locator('.v2-thumbnails').count(),0);pass('single-image gallery');
for(const width of [1366,768,430,390,360]){await page.setViewportSize({width,height:1000});await card('featured').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const info=await card('featured').evaluate(el=>{const s=getComputedStyle(el),a=el.querySelector('.listing-featured-badge').getBoundingClientRect(),b=el.querySelector('.v2-badge').getBoundingClientRect();return{border:s.borderTopColor,bg:s.backgroundImage,shadow:s.boxShadow,separate:a.bottom<=b.top,dir:s.direction}});assert.equal(info.border,'rgb(187, 135, 31)');assert.notEqual(info.bg,'none');assert.notEqual(info.shadow,'none');assert.equal(info.separate,true);assert.equal(info.dir,'rtl');const font=await card('featured').locator('h3').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));const normalFont=await card('normal').locator('h3').evaluate(el=>parseFloat(getComputedStyle(el).fontSize));assert.ok(width>=1024?font/normalFont>=1.049&&font/normalFont<=1.08:font===normalFont);pass('gold style, separate badges, RTL and no overflow '+width);}
await card('featured').locator('.v2-favorite').click();assert.equal(await card('featured').locator('.v2-favorite').getAttribute('aria-pressed'),'true');pass('favorite remains functional');
await card('featured').locator('.v2-favorite').focus();assert.equal(await card('featured').locator('.v2-favorite').evaluate(el=>el===document.activeElement),true);assert.equal(await card('featured').locator('.listing-featured-badge svg').getAttribute('aria-hidden'),'true');pass('accessible text, decorative icon, keyboard control');
await page.setViewportSize({width:1366,height:1000});await page.evaluate(()=>{for(const el of document.querySelectorAll('#direct-sales .v2-card'))if(!['normal','featured'].includes(el.dataset.animalId))el.style.setProperty('display','none','important');const grid=document.getElementById('direct-sales');grid.style.setProperty('grid-template-columns','repeat(2,minmax(0,1fr))','important');grid.style.maxWidth='1000px';});await page.locator('#direct-sales').screenshot({path:path.join(shots,'normal-and-featured.png')});
await page.evaluate(async()=>{const a=window.__mock.docs.get('animals/featured');a.images=a.images.slice(0,1);await window.applyMarketFilters()});await page.waitForFunction(()=>!document.querySelector('[data-animal-id="featured"] .v2-thumbnails'));assert.equal(await card('featured').locator('.listing-featured-badge').count(),1);pass('featured single-image card');
await page.evaluate(async()=>{window.__mock.docs.get('animals/featured').featuredUntil=new Date(Date.now()+1500);await window.applyMarketFilters()});await page.waitForFunction(()=>!document.querySelector('[data-animal-id="featured"]').classList.contains('listing-card--featured'),{},{timeout:7000});assert.equal(await card('featured').locator('.listing-featured-badge').count(),0);pass('expiry removes style and badge without refresh');
assert.deepEqual(errors,[]);pass('zero JavaScript errors');console.log('SUMMARY | '+count+'/'+count+' PASS; '+shots);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
