import assert from 'node:assert/strict';
import fs from 'node:fs';
import {safeImage,validateImageCount} from '../image-provider.js';
import {CATEGORIES,PETS,gallery,activeFeatured} from '../marketplace-v2.js';
import {planOwnerEmailLink} from '../admin-tools/owner-email-dry-run.mjs';
globalThis.document={documentElement:{lang:'ar'}};
let count=0;const test=(name,fn)=>{fn();console.log('PASS | '+name);count++;};
const jpeg='data:image/jpeg;base64,YWJj',url='https://res.cloudinary.com/demo/image/upload/v1/livestock.jpg';
test('minimum one photo',()=>assert.throws(()=>validateImageCount([]),/IMAGE_REQUIRED/));
test('one to three photos',()=>{for(const length of [1,2,3])validateImageCount(Array(length));});
test('four photos rejected',()=>assert.throws(()=>validateImageCount(Array(4)),/TOO_MANY_IMAGES/));
test('old JPEG and Cloudinary HTTPS preserved',()=>{assert.equal(safeImage(jpeg),jpeg);assert.equal(safeImage(url),url);});
test('unsafe image schemes and quote injection rejected',()=>{for(const value of ['javascript:alert(1)','https://evil.test/a.jpg',url+'" onerror="x','data:image/svg+xml;base64,YWJj'])assert.equal(safeImage(value),'');});
test('one-image no arrows or dots',()=>{const html=gallery([jpeg]);assert.ok(!html.includes('data-slide'));assert.ok(!html.includes('data-dot'));});
test('three-image arrows dots lazy loading',()=>{const html=gallery([jpeg,jpeg,jpeg]);assert.equal((html.match(/data-slide=/g)||[]).length,2);assert.equal((html.match(/data-dot=/g)||[]).length,3);assert.equal((html.match(/loading="lazy"/g)||[]).length,3);});
test('legacy six images remain visible in gallery',()=>assert.equal((gallery(Array(6).fill(jpeg)).match(/<img /g)||[]).length,6));
test('malformed legacy image field does not crash',()=>assert.match(gallery({}),/لا توجد صورة/));
test('all nine existing categories preserved',()=>{for(const type of ['ناقة','غنم','ماعز','بقر','دجاج','صقور','غزال','نعام','حمام'])assert.ok(CATEGORIES.some(c=>c[0]===type));});
test('pets other and six optional pet subcategories',()=>{assert.ok(CATEGORIES.some(c=>c[0]==='حيوانات أليفة'));assert.ok(CATEGORIES.some(c=>c[0]==='أخرى'));assert.equal(PETS.length,6);});
const animals={one:{id:'one',country:'AE',status:'active',images:[jpeg]},two:{id:'two',country:'AE',images:[url]},three:{id:'three',country:'EG',images:[url]},hidden:{id:'hidden',status:'hidden',images:[url]}};
const slot=(animalId,priority=0)=>({animalId,active:true,priority,startAt:new Date(100),endAt:new Date(1000)});
test('Hero static mode and absent settings fall back',()=>{assert.deepEqual(activeFeatured(null,animals,'AE',500),[]);assert.deepEqual(activeFeatured({mode:'static',featured:[slot('one')]},animals,'AE',500),[]);});
test('Hero expiry inactive hidden country and missing image filters',()=>{const settings={mode:'featured',featured:[slot('one'),slot('three'),slot('hidden'),{...slot('two'),active:false},slot('missing')]};assert.equal(activeFeatured(settings,animals,'AE',500).length,1);assert.equal(activeFeatured(settings,animals,'AE',1000).length,0);});
test('Hero order and cap of three',()=>{const settings={mode:'featured',featured:[slot('one',2),slot('two',1),slot('one',3),slot('two',4)]};const result=activeFeatured(settings,animals,'AE',500);assert.equal(result.length,3);assert.equal(result[0].animal.id,'two');});
test('owner migration is pure dry-run with zero writes',()=>{const result=planOwnerEmailLink({uid:'owner',expectedUid:'owner',claims:{admin:true},profile:{status:'active'},providers:['phone']});assert.equal(result.mode,'dry-run');assert.equal(result.writes,0);assert.equal(result.changesUid,false);assert.equal(result.unlinksPhone,false);assert.equal(result.createsUser,false);});
test('owner migration refuses changed UID occupied email and wrong role',()=>{const base={uid:'owner',expectedUid:'owner',claims:{admin:true},providers:['phone']};assert.throws(()=>planOwnerEmailLink({...base,expectedUid:'other'}),/UID_MISMATCH/);assert.throws(()=>planOwnerEmailLink({...base,emailInUse:true}),/EMAIL_ALREADY_IN_USE/);assert.throws(()=>planOwnerEmailLink({...base,claims:{}}),/OWNER_REQUIRED/);});
test('no production migration code in app',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');assert.ok(!source.includes('linkWithCredential('));assert.ok(!source.includes('deleteUser('));});
console.log(`SUMMARY | ${count}/${count} passed`);
