import test from 'node:test';
import assert from 'node:assert/strict';
import {phase1Views} from '../melkak/phase1-views.js';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
function harness(ads=[],rows=[]){let dialog='';const s={country:'AE',city:'',lang:'en',hero:0,signedIn:true,adminCountry:'AE',commercialTab:'active'};const c={s,preview:false,writable:true,store:{state:{ads,publicAds:ads.filter(a=>a.publicEligible),services:[],reports:[],listings:[],users:[]}},countries:{AE:{name:'الإمارات',english:'UAE'}},t:(_ar,en)=>en,esc,icon:()=>'',link:(label,route)=>`<a href="#/${route}">${label}</a>`,button:(label,action,attrs='')=>`<button data-action="${action}" ${attrs}>${label}</button>`,cards:items=>items.map(a=>`<article>${a.id}</article>`).join(''),categories:()=>'',searchbar:()=>'',actor:()=>({role:'super_admin'}),can:()=>true,date:String,render:()=>{},openDialog:(_title,html)=>dialog=html,toast:()=>{},asset:x=>x,publicRows:()=>rows,featured:()=>false,noData:x=>x};return {v:phase1Views(c),s,store:c.store,get dialog(){return dialog;}};}
const ad=(id,placement='hero',extra={})=>({id,title:id,advertiserName:id,description:'Text',cta:'Visit',asset:'https://example.com/ad.jpg',targetUrl:'https://example.com',countryTarget:'AE',placement,priority:10,status:'approved',startAt:Date.now()-1000,endAt:Date.now()+86400000,sourceCollection:'marketplaceRequests',publicEligible:true,...extra});
test('live bump dialog opens and home respects bump time with every footer placement',()=>{const h=harness([1,2,3,4,5].map(i=>ad('footer'+i,'footer_'+i)),[{id:'old-bumped',country:'AE',createdAt:1,bumpedAt:100},{id:'new',country:'AE',createdAt:20}]);h.v.serviceDialog('x','bump');assert.match(h.dialog,/service-request-form/);assert.doesNotMatch(h.dialog,/local preview|live-site writes/);const html=h.v.home();assert.ok(html.indexOf('<article>old-bumped')<html.indexOf('<article>new'));for(let i=1;i<=5;i++)assert.match(html,new RegExp('data-commercial="footer'+i+'"'));});
test('map picks live priority winner and legacy campaigns never receive mutation controls',()=>{const h=harness([ad('expired','hero_side_1',{endAt:1}),ad('lower','hero_side_1',{priority:1}),ad('winner','hero_side_1'),ad('legacy','hero',{sourceCollection:'commercialAds'})]);const html=h.v.commercialMap(),map=html.split('class="placement-map"')[1].split('class="campaign-list"')[0];assert.match(map,/<span>winner<\/span>/);assert.doesNotMatch(map,/<span>expired<\/span>|<span>lower<\/span>/);assert.doesNotMatch(html,/data-action="(?:review-commercial|commercial-edit)" data-id="legacy"/);assert.match(html,/data-action="commercial-edit" data-id="winner"/);});
test('live request copy and edit dialog contain persisted fields and meaningful image picker',()=>{const h=harness([ad('editable')]);const request=h.v.requestCommercial();assert.doesNotMatch(request,/never uploaded to Production|Local request only/);assert.match(request,/Choose image from device/);assert.equal(typeof h.v.commercialEdit,'function');const edit=h.v.commercialEdit('editable');assert.match(edit,/id="commercial-edit-form" data-id="editable"/);assert.match(edit,/name="title"[^>]*value="editable"/);assert.match(edit,/name="reason"/);assert.match(edit,/name="countryTarget"/);});
test('middle placement stays empty when only side campaigns exist',()=>{const h=harness([ad('side','hero_side_1')]);assert.match(h.v.home(),/<div class="middle-promo"><\/div>/);});
test('empty side slots show MELKAK house branding without commercial identities and admin remains empty',()=>{const h=harness();const before=JSON.stringify(h.s);for(let i=1;i<=3;i++){const html=h.v.adBlock('hero_side_'+i);assert.match(html,/house-ad/);assert.match(html,/MELKAK/);assert.match(html,/Advertising space/);assert.match(html,/#\/commercial-request/);assert.doesNotMatch(html,/data-commercial|target="_blank"/);}assert.match(h.v.commercialMap(),/EMPTY/);assert.doesNotMatch(h.v.home(),/class="home-section featured-section"/);});
test('side eligibility replaces house only during eligible dates and country',()=>{for(const extra of [{endAt:1},{startAt:Date.now()+100000},{countryTarget:'SA'},{cityTarget:'other'},{status:'pending'}])assert.match(harness([ad('bad','hero_side_1',extra)]).v.adBlock('hero_side_1'),/house-ad/);assert.match(harness([ad('real','hero_side_1')]).v.adBlock('hero_side_1'),/data-commercial="real"/);});
test('commercial tabs distinguish pending rejected and scheduled with full request details',()=>{const h=harness([ad('pending','hero_side_1',{status:'pending'}),ad('rejected','hero',{status:'rejected'}),ad('scheduled','hero',{startAt:Date.now()+10000})]);h.s.commercialTab='pending';let html=h.v.commercialMap();assert.match(html,/Pending \(1\)/);assert.match(html,/Rejected \(1\)/);assert.match(html,/Scheduled \(1\)/);const list=html.split('class="campaign-list"')[1];assert.match(list,/campaign-image/);assert.match(list,/Side ad 1/);assert.match(list,/Text/);assert.match(list,/https:\/\/example.com/);assert.doesNotMatch(list,/<h3>rejected|<h3>scheduled/);h.s.commercialTab='scheduled';assert.match(h.v.commercialMap(),/<h3>scheduled/);});
test('featured management has own clickable counters without commercial metrics or ambiguous requests',()=>{const html=harness().v.featuredManagement([]);assert.match(html,/data-action="featured-tab"/);assert.match(html,/Pending \(0\)/);assert.doesNotMatch(html,/Commercial|Service requests|service requests/);});
test('request form uses understandable placement and link labels',()=>{const html=harness().v.requestCommercial();assert.match(html,/Link when the ad is clicked/);assert.match(html,/https:\/\/example.com/);assert.doesNotMatch(html,/>hero_side_1<|HTTPS destination|Hero order/);});

test('no destination campaign has no fake navigation',()=>{const html=harness([ad('no-link','hero_side_1',{targetUrl:''})]).v.adBlock('hero_side_1');assert.doesNotMatch(html,/href=|target="_blank"/);});

test('admin campaign artwork exposes real ID to existing image loader',()=>{const html=harness([ad('artwork')]).v.commercialMap();assert.match(html,/<img class="campaign-image" data-commercial="artwork"/);});

test('featured pending counter opens only featured listing requests',()=>{const h=harness([],[{id:'listing',title:'A listing'}]);h.store.state.services=[{id:'feature',type:'featured',listingId:'listing',status:'pending'},{id:'bump',type:'bump',listingId:'listing',status:'pending'},{id:'commercial',type:'commercial',status:'pending'}];h.s.featuredTab='pending';const html=h.v.featuredManagement([{id:'listing',title:'A listing'}]);assert.match(html,/Pending \(1\)/);assert.match(html,/data-action="approve-service" data-id="feature"/);assert.doesNotMatch(html.split('class="bump-management"')[0],/data-id="bump"|data-id="commercial"/);});
test('bump requests retain a separate actionable queue without changing featured counters',()=>{const h=harness();const rows=[{id:'listing',title:'A listing'}];h.store.state.services=[{id:'feature',type:'featured',listingId:'listing',status:'pending'},{id:'bump',type:'bump',listingId:'listing',status:'pending'}];let html=h.v.featuredManagement(rows);assert.match(html,/Pending \(1\)/);assert.match(html,/Bump requests \(1\)/);assert.match(html,/data-action="approve-service" data-id="bump"/);assert.match(html,/data-action="reject-service" data-id="bump"/);assert.match(html,/data-action="bump-tab"/);h.s.bumpTab='rejected';html=h.v.featuredManagement(rows);assert.doesNotMatch(html,/data-action="approve-service" data-id="bump"/);assert.match(html,/data-action="approve-service" data-id="feature"/);});
