import fs from 'node:fs';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails} from '@firebase/rules-unit-testing';
import * as sdk from 'firebase/firestore';
import {attachProductionListingAdmin} from '../melkak/production-listing-admin.js';
import {attachProductionServices} from '../melkak/production-services.js';
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080')throw Error('Local emulator 127.0.0.1:8080 required');
sdk.setLogLevel('silent');
const env=await initializeTestEnvironment({projectId:'demo-melkak-listing-admin',firestore:{rules:fs.readFileSync(new URL('../melkak/firestore.proposed.rules',import.meta.url),'utf8')}});
const failures=[];let passed=0;
async function check(name,fn){try{await fn();passed++;console.log('PASS',name);}catch(error){failures.push(name);console.error('FAIL',name,error.code||error.message);}}
const bossDb=env.authenticatedContext('boss',{admin:true}).firestore(),normalDb=env.authenticatedContext('other').firestore();
function service(db,uid,role){const options={sdk,db,auth:{state:{actor:{uid,role,status:'active',ready:true}}},config:{writesEnabled:true}};const store=attachProductionServices({state:{listings:[],categories:[]},refresh:async()=>{}},options);return attachProductionListingAdmin(store,options);}
const boss=service(bossDb,'boss','super_admin'),normal=service(normalDb,'other',null);
const read=async(collection,id)=>{let result;await env.withSecurityRulesDisabled(async c=>{const snap=await sdk.getDoc(sdk.doc(c.firestore(),collection,id));result=snap.exists()?snap.data():undefined;});return result;};
try{
 await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();for(const uid of ['boss','seller','other'])await sdk.setDoc(sdk.doc(db,'users',uid),{status:'active'});await sdk.setDoc(sdk.doc(db,'adminSecurity','config'),{enabled:true,superAdminUids:['boss']});for(const id of ['priority','clean','history','expired'])await sdk.setDoc(sdk.doc(db,'marketplaceListings',id),{schemaVersion:1,ownerUid:'seller',country:'AE',region:'Dubai',city:'Dubai',category:'cars',title:'Local test listing',description:'Local emulator listing for admin verification',currency:'AED',price:1,attributes:{},contact:{phone:'+971500000000',consent:true,call:true,whatsapp:false,showNumber:false},images:['data:image/jpeg;base64,/9j/AA=='],status:'active',hasHistory:id==='history',createdAt:sdk.Timestamp.fromMillis(1000),updatedAt:sdk.Timestamp.fromMillis(1000),featured:true,featuredStatus:'approved',featuredStartAt:Date.now()-1000,featuredEndAt:id==='expired'?Date.now()-1:Date.now()+86400000});});
 await check('registered owner priority range preserves createdAt',async()=>{for(const priority of [0,50,100]){await boss.setFeaturedPriority('marketplace-priority',priority,'Reviewed ordering');const item=await read('marketplaceListings','priority');assert.equal(item.featuredPriority,priority);assert.equal(item.createdAt.toMillis(),1000);assert.equal((await read('marketplaceAuditLogs',item.auditId)).action,'featured-priority');}await assert.rejects(()=>boss.setFeaturedPriority('priority',101,'Invalid ordering'),{code:'FIELDS'});});
 await check('normal user and forged role priority denied',async()=>{await assert.rejects(()=>normal.setFeaturedPriority('priority',1,'No privilege'),{code:'PERMISSION'});await assert.rejects(()=>service(normalDb,'other','super_admin').setFeaturedPriority('priority',1,'Forged privilege'));});
 await check('blank and expired priority denied',async()=>{await assert.rejects(()=>boss.setFeaturedPriority('priority',1,'  '),{code:'REASON'});await assert.rejects(()=>boss.setFeaturedPriority('expired',1,'Expired item'),{code:'STATE'});});
 await check('clean deletion removes inline image body and retains tombstone and audit',async()=>{const result=await boss.adminDeleteListing('marketplace-clean','Delete clean listing');assert.equal(result.deleted,true);assert.equal(await read('marketplaceListings','clean'),undefined);const tomb=await read('marketplaceDeletions','clean');assert.deepEqual(Object.keys(tomb).sort(),['listingId','ownerUid','actorUid','reason','auditId','timestamp'].sort());assert.equal(tomb.ownerUid,'seller');assert.equal(tomb.images,undefined);const log=await read('marketplaceAuditLogs',tomb.auditId);assert.equal(log.action,'listing-deleted');assert.equal(log.targetId,'clean');assert.equal(log.result,'deleted');});
 await check('historical deletion archives and preserves images',async()=>{const result=await boss.adminDeleteListing('marketplace-history','Preserve historical listing');assert.equal(result.archived,true);const item=await read('marketplaceListings','history');assert.equal(item.status,'archived');assert.equal(item.images[0],'data:image/jpeg;base64,/9j/AA==');assert.equal(await read('marketplaceDeletions','history'),undefined);});
 await check('normal SDK cannot delete another owners listing',async()=>{await assertFails(sdk.deleteDoc(sdk.doc(normalDb,'marketplaceListings','priority')));});
 await check('forged tombstone without deleting listing denied',async()=>{await assertFails(sdk.setDoc(sdk.doc(bossDb,'marketplaceDeletions','priority'),{listingId:'priority',ownerUid:'seller',actorUid:'boss',reason:'Forged delete record',auditId:'forged',timestamp:sdk.serverTimestamp()}));});
 await check('lone deletion audit without tombstone denied',async()=>{await assertFails(sdk.setDoc(sdk.doc(bossDb,'marketplaceAuditLogs','orphan'),{actorUid:'boss',action:'listing-deleted',targetCollection:'marketplaceListings',targetId:'priority',reason:'Orphan deletion audit',timestamp:sdk.serverTimestamp(),result:'deleted'}));});
 console.log(`Listing admin emulator: ${passed} passed, ${failures.length} failed`);if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}
}finally{await env.cleanup();}
