const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});let external=0;try{const page=await browser.newPage();await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname!=='commercial-image.test'){external++;return route.abort();}if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Local commercial image tests</title>'});const filename=path.resolve(root,'.'+url.pathname);if(!filename.startsWith(root+path.sep)||!fs.existsSync(filename))return route.fulfill({status:404,body:'Missing module'});return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(filename,'utf8')});});await page.goto('https://commercial-image.test/');
 const results=await page.evaluate(async()=>{
  const {commercialImageData}=await import('/melkak/commercial-image.js');const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=1000;const ctx=canvas.getContext('2d'),pixels=ctx.createImageData(canvas.width,canvas.height);let seed=3;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;pixels.data[i]=seed&255;pixels.data[i+1]=(seed>>>8)&255;pixels.data[i+2]=(seed>>>16)&255;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const rows=[];
  for(const type of ['image/jpeg','image/png','image/webp']){const blob=await new Promise(resolve=>canvas.toBlob(resolve,type,.95)),file=new File([blob],'noise.'+type.split('/')[1],{type});const result=await commercialImageData([file],{uid:'seller'});const img=new Image();img.src=result[0];await img.decode();rows.push({type,count:result.length,length:result[0].length,jpeg:result[0].startsWith('data:image/jpeg;base64,'),width:img.naturalWidth,height:img.naturalHeight});}
  const reject=async(fn)=>{try{await fn();return '';}catch(error){return error.code||error.message;}};
  const good=new File([await new Promise(resolve=>canvas.toBlob(resolve,'image/png'))],'noise.png',{type:'image/png'});
  return {rows,errors:{anonymous:await reject(()=>commercialImageData([good],null)),empty:await reject(()=>commercialImageData([],{uid:'seller'})),many:await reject(()=>commercialImageData([good,good],{uid:'seller'})),invalid:await reject(()=>commercialImageData([new File(['text'],'bad.txt',{type:'text/plain'})],{uid:'seller'})),corrupt:await reject(()=>commercialImageData([new File(['text'],'bad.png',{type:'image/png'})],{uid:'seller'})),oversized:await reject(()=>commercialImageData([new File([new Uint8Array(30*1024*1024+1)],'large.jpg',{type:'image/jpeg'})],{uid:'seller'}))}};
 });
 for(const row of results.rows){assert.equal(row.count,1);assert.ok(row.jpeg);assert.ok(row.length<=110000,JSON.stringify(row));assert.ok(row.width<=1400&&row.height<=800);assert.ok(row.width>=640,'retain readable landscape size');assert.ok(Math.abs(row.width/row.height-1.6)<.02);console.log('PASS | noisy '+row.type+' -> '+row.width+'x'+row.height+' JPEG '+row.length+' chars');}
 assert.deepEqual(results.errors,{anonymous:'AUTH_REQUIRED',empty:'IMAGE_REQUIRED',many:'TOO_MANY_IMAGES',invalid:'INVALID_IMAGE',corrupt:'IMAGE_LOAD_ERROR',oversized:'IMAGE_TOO_LARGE'});assert.equal(external,0);console.log('PASS | invalid, corrupt, oversized, unauthenticated and multiple selections rejected');console.log('PASS | zero external requests');console.log('SUMMARY | 5/5 PASS');
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
