import test from 'node:test';
import assert from 'node:assert/strict';
import {phase1Views} from '../melkak/phase1-views.js';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
function harness(ads=[],rows=[]){let dialog='';const s={country:'AE',city:'',lang:'en',hero:0,signedIn:true,adminCountry:'AE',commercialTab:'active'};const c={s,preview:false,writable:true,store:{state:{ads,publicAds:ads.filter(a=>a.publicEligible),services:[],reports:[],listings:[],users:[]}},countries:{AE:{name:'الإمارات',english:'UAE'}},t:(_ar,en)=>en,esc,icon:()=>'',link:(label,route)=>`<a href="#/${route}">${label}</a>`,button:(label,action,attrs='')=>`<button data-action="${action}" ${attrs}>${label}</button>`,cards:items=>items.map(a=>`<article>${a.id}</article>`).join(''),categories:()=>'',searchbar:()=>'',actor:()=>({role:'super_admin'}),can:()=>true,date:String,render:()=>{},openDialog:(_title,html)=>dialog=html,toast:()=>{},asset:x=>x,publicRows:()=>rows,featured:()=>false,noData:x=>x};return {v:phase1Views(c),s,get dialog(){return dialog;}};}
const ad=(id,placement='hero',extra={})=>({id,title:id,advertiserName:id,description:'Text',cta:'Visit',asset:'https://example.com/ad.jpg',targetUrl:'https://example.com',countryTarget:'AE',placement,priority:10,status:'approved',startAt:Date.now()-1000,endAt:Date.now()+86400000,sourceCollection:'marketplaceRequests',publicEligible:true,...extra});
test('live bump dialog opens and home respects bump time with every footer placement',()=>{const h=harness([1,2,3,4,5].map(i=>ad('footer'+i,'footer_'+i)),[{id:'old-bumped',country:'AE',createdAt:1,bumpedAt:100},{id:'new',country:'AE',createdAt:20}]);h.v.serviceDialog('x','bump');assert.match(h.dialog,/service-request-form/);assert.doesNotMatch(h.dialog,/local preview|live-site writes/);const html=h.v.home();assert.ok(html.indexOf('<article>old-bumped')<html.indexOf('<article>new'));for(let i=1;i<=5;i++)assert.match(html,new RegExp('data-commercial="footer'+i+'"'));});
test('map picks live priority winner and legacy campaigns never receive mutation controls',()=>{const h=harness([ad('expired','hero_side_1',{endAt:1}),ad('lower','hero_side_1',{priority:1}),ad('winner','hero_side_1'),ad('legacy','hero',{sourceCollection:'commercialAds'})]);const html=h.v.commercialMap(),map=html.split('class="placement-map"')[1].split('class="campaign-list"')[0];assert.match(map,/<span>winner<\/span>/);assert.doesNotMatch(map,/<span>expired<\/span>|<span>lower<\/span>/);assert.doesNotMatch(html,/data-action="(?:review-commercial|commercial-edit)" data-id="legacy"/);assert.match(html,/data-action="commercial-edit" data-id="winner"/);});
test('live request copy and edit dialog contain persisted fields and meaningful image picker',()=>{const h=harness([ad('editable')]);const request=h.v.requestCommercial();assert.doesNotMatch(request,/never uploaded to Production|Local request only/);assert.match(request,/Choose image from device/);assert.equal(typeof h.v.commercialEdit,'function');const edit=h.v.commercialEdit('editable');assert.match(edit,/id="commercial-edit-form" data-id="editable"/);assert.match(edit,/name="title"[^>]*value="editable"/);assert.match(edit,/name="reason"/);assert.match(edit,/name="countryTarget"/);});
test('middle placement stays empty when only side campaigns exist',()=>{const h=harness([ad('side','hero_side_1')]);assert.match(h.v.home(),/<div class="middle-promo"><\/div>/);});
