const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.MELKAK_QA||path.join(require('os').tmpdir(),'melkak-complete-screenshots');fs.mkdirSync(out,{recursive:true});let n=0;const pass=name=>{n++;console.log('PASS | '+name);};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8786/'))remote.push(r.url())});
await page.goto('http://127.0.0.1:8786');await page.waitForFunction(()=>window.__melkak);await page.evaluate(()=>document.fonts.ready);
const nav=async hash=>{await page.evaluate(h=>location.hash='#/'+h,hash);await page.waitForTimeout(100);};const shot=async name=>{await page.waitForFunction(()=>!document.querySelector('#toast').textContent);await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});};
assert.equal(await page.locator('.world-countries button').count(),6);assert.match(await page.locator('.world-copy').innerText(),/MELKAK/);assert.ok((await page.locator('.side-ads').boundingBox()).x>(await page.locator('.market-main').boundingBox()).x);pass('six-country hero and right-side desktop commercial blocks');
assert.equal(await page.locator('#search-form select').count(),3);await shot('country-selector');pass('search exposes country city category');
const featureBox=await page.locator('.featured-section .listing').first().boundingBox(),normalBox=await page.locator('.latest-section .listing').first().boundingBox();assert.ok(featureBox.width>normalBox.width);pass('featured cards larger within independent aligned grid');
const originalAds=await page.evaluate(()=>structuredClone(window.__melkak.store.state.ads));
for(const count of [0,1,10,11]){await page.evaluate(({ads,count})=>{const w=window.__melkak;w.state.hero=0;w.store.state.ads=Array.from({length:count},(_,i)=>({...ads[0],status:'active',id:'hero-check-'+i,priority:10-i}));w.render();},{ads:originalAds,count});assert.equal(await page.locator('.world-hero').count(),1);assert.equal(await page.locator('.hero-art').count(),count?1:0);if(count)assert.match(await page.locator('.hero-controls').innerText(),new RegExp('1 / '+Math.min(count,10)));else assert.equal(await page.locator('.default-hero-note').count(),1);pass('browser Hero '+count+' with single active commercial image');}
await page.evaluate(ads=>{window.__melkak.store.state.ads=ads;window.__melkak.render();},originalAds);
await page.evaluate(()=>{const w=window.__melkak;w.store.state.ads.forEach(a=>a.countryTarget='SA');w.state.country='AE';w.render();});assert.equal(await page.locator('.promo-block,.commercial-slider').count(),0);await page.locator('[data-action=world-country][data-id=SA]').click();assert.equal(await page.locator('.side-ads .promo-block').count(),3);pass('wrong-country promotional ads absent from all placements');await page.evaluate(ads=>{window.__melkak.store.state.ads=ads;window.__melkak.state.country='AE';window.__melkak.render();},originalAds);
assert.ok(await page.locator('.tag').first().innerText());await page.locator('[data-commercial]:visible').first().click();assert.match(await page.locator('#toast').innerText(),/تجريبي/);pass('commercial label and safe local demo click');
for(const route of ['about','contact','featured']){await nav(route);assert.ok(await page.locator('h1').innerText());pass('public route '+route);}
await nav('market/phones');await page.locator('[name="attr:capacity"]').fill('حالة ممتازة');await page.getByRole('button',{name:'تطبيق الفلاتر',exact:true}).click();assert.ok(await page.locator('.listing').count()>0);await shot('phones');pass('phone capacity filter');
await nav('home');await page.locator('[data-action=favorite]').first().click();await nav('favorites');await shot('favorites');pass('favorites screenshot');
await page.locator('#preview-role').selectOption('super_admin');await nav('admin');const sidebar=await page.locator('.admin-sidebar').evaluate(e=>getComputedStyle(e).backgroundImage);assert.match(sidebar,/237, 249, 255/);await shot('admin-home');assert.equal(await page.locator('.stat').count(),7);pass('light admin identity with seven focused counters');
for(const route of ['listings','categories','featured','commercial']){await nav('admin/'+route);await shot(route==='featured'?'featured-management':route==='commercial'?'commercial-ads-map':'admin-'+route);pass('admin screenshot '+route);}
assert.equal(await page.locator('.hero-map .map-slot').count(),10);assert.equal(await page.locator('.side-map .map-slot').count(),3);assert.ok(await page.locator('.map-slot').first().innerText());pass('commercial map 10 Hero / 3 sides / middle / footer with metadata');
await page.locator('#preview-role').selectOption('user');await nav('manage/AE-cars');await page.getByRole('button',{name:'تمييز الإعلان',exact:true}).click();await page.locator('#duration-days').selectOption('custom');await page.locator('[name=customDays]').fill('11');await page.locator('#service-request-form button[type=submit]').click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.services[0].featuredDurationDays),11);pass('custom featured request UI stores 11 days');
await page.locator('#preview-role').selectOption('super_admin');await nav('admin/featured');await page.getByRole('button',{name:'اعتماد بدون دفع',exact:true}).click();await page.locator('#approve-form textarea').fill('Local review only');await page.locator('#approve-form button[type=submit]').click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.listings.find(a=>a.id==='AE-cars').featuredDurationDays),11);await shot('featured-management');pass('admin approval applies start end and duration locally');
await page.evaluate(()=>{const a=window.__melkak.store.state.listings.find(a=>a.id==='AE-cars');a.featuredEndAt=Date.now()-1;});await nav('market/cars');assert.equal(await page.locator('.listing.featured').count(),0);assert.equal(await page.locator('.listing').count(),1);pass('expired featured loses styling without deleting listing');
await page.locator('#preview-role').selectOption('user');await nav('commercial-request');assert.ok(await page.locator('#commercial-save').isDisabled());await page.locator('[name=advertiserName]').fill('معلن محلي للمراجعة');await page.locator('[name=title]').fill('إعلان ترويجي لاختبار مِلكك');await page.locator('[name=targetUrl]').fill('https://example.test/promotion');await page.locator('[name=countryTarget]').selectOption('AE');await page.locator('[name=placement]').selectOption('middle');
await page.locator('#commercial-image-picker').setInputFiles({name:'not-image.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});await page.waitForTimeout(100);assert.ok(await page.locator('#commercial-save').isDisabled());pass('commercial image mandatory; invalid file blocked');
const imageFile=fs.readFileSync('melkak/assets/world-hero.webp');await page.locator('#commercial-image-picker').setInputFiles({name:'world-hero.webp',mimeType:'image/webp',buffer:imageFile});await page.waitForFunction(()=>!document.querySelector('#commercial-save').disabled);assert.ok((await page.locator('#commercial-preview img').getAttribute('src')).startsWith('data:image/jpeg;base64,'));pass('device commercial image compressed preview');await page.locator('[data-action=commercial-remove]').click();assert.ok(await page.locator('#commercial-save').isDisabled());pass('remove commercial image blocks save');await page.locator('#commercial-image-picker').setInputFiles({name:'hero.webp',mimeType:'image/webp',buffer:imageFile});await page.waitForFunction(()=>!document.querySelector('#commercial-save').disabled);await shot('commercial-request');await page.locator('#commercial-save').click();await page.waitForFunction(()=>location.hash==='#/account');assert.equal(await page.evaluate(()=>window.__melkak.store.state.ads[0].status),'pending');pass('promotion request saved separately as pending');
await page.locator('#preview-role').selectOption('super_admin');await nav('admin/commercial');const req=page.locator('.campaign').filter({hasText:'إعلان ترويجي لاختبار مِلكك'});await req.getByRole('button',{name:'اعتماد',exact:true}).click();await page.locator('#commercial-review-form textarea').fill('Local approval');await page.locator('#commercial-review-form button[type=submit]').click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.ads[0].status),'approved');pass('owner approves promotional request');
await page.locator('[data-action=campaign-tab][data-id=active]').click();await req.getByRole('button',{name:'إيقاف',exact:true}).click();await page.locator('#commercial-review-form textarea').fill('Pause test');await page.locator('#commercial-review-form button[type=submit]').click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.ads[0].status),'paused');pass('owner pauses local promotion');
await page.locator('#preview-role').selectOption('assistant');await nav('admin/commercial');assert.match(await page.locator('#main').innerText(),/غير متاحة/);pass('assistant commercial route denied by existing policy');
await page.locator('#preview-role').selectOption('user');await nav('listing/AE-cars');await page.getByRole('button',{name:'الإبلاغ عن المستخدم',exact:true}).click();await page.locator('#user-report-form textarea').fill('بلاغ مستخدم محلي');await page.locator('#user-report-form button[type=submit]').click();pass('user report entry and local record');await page.locator('#preview-role').selectOption('super_admin');await nav('admin/reports');await page.getByRole('button',{name:'مراجعة وإجراءات',exact:true}).first().click();await page.locator('#report-action-form select').selectOption('suspend');await page.locator('#report-action-form textarea').fill('Owner protection test');await page.locator('#report-action-form button[type=submit]').click();assert.match(await page.locator('#toast').innerText(),/لا تملك الصلاحية/);await page.locator('[data-action=close-dialog]').click();pass('owner suspension rejected through report UI');
for(const width of [360,390,430,768,1024,1280,1440]){await page.setViewportSize({width,height:950});for(const route of ['home','admin','admin/commercial','admin/featured','commercial-request']){await nav(route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+route+' '+width);}pass('complete responsive paths '+width);}
await page.setViewportSize({width:390,height:900});await nav('home');assert.equal(await page.locator('.side-ads').isVisible(),false);assert.equal(await page.locator('.middle-promo .promo-block:visible').count(),1);assert.equal(await page.locator('#search-form select:visible').count(),0);await shot('mobile-commercial-placements');pass('bounded inline ad density and compact mobile filter modal');
await page.locator('[data-action=language]').click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('new home LTR mobile');
assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.equal(await page.evaluate(()=>window.__melkak.flags.payments||window.__melkak.flags.analytics||window.__melkak.flags.productionWrites),false);pass('0 critical JS errors / 0 remote requests / flags disabled');console.log(`SUMMARY | ${n}/${n} PASS`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
