import test from 'node:test';
import assert from 'node:assert/strict';
const module = await import('../melkak/auth-adapter.js').catch(()=>({}));
function harness({claims={}, profile={status:'active'}, record=null, config={enabled:true,superAdminUids:['owner']}, user={uid:'owner',displayName:'Owner',email:'admin@example.com'}, failure=null}={}) {
  let listener; const app={name:'[DEFAULT]',options:{projectId:'souq-al-halal-9e3e8'}}, auth={currentUser:user};
  const docs={['users/'+user?.uid]:profile,['adminAccess/'+user?.uid]:record,'adminSecurity/config':config};
  const calls=[];
  const sdk={getApps:()=>[app],getApp:()=>app,initializeApp:()=>{throw Error('must reuse app')},getAuth:a=>{assert.equal(a,app);return auth},getFirestore:()=>({}),doc:(_db,...path)=>path.join('/'),getDoc:async path=>{calls.push(path);if(failure===path)throw Error('permission-denied');return {data:()=>docs[path],exists:()=>docs[path]!=null}},getIdTokenResult:async()=>({claims}),GoogleAuthProvider:class {},signInWithPopup:async(a,p)=>{assert.equal(a,auth);assert.ok(p instanceof sdk.GoogleAuthProvider);return {user}},signOut:async()=>{auth.currentUser=null;await listener(null)},onAuthStateChanged:(_a,fn)=>{listener=fn;return ()=>{listener=null}}};
  return {sdk,auth,calls,docs,emit:async next=>{auth.currentUser=next;await listener(next)},user};
}
async function create(options){assert.equal(typeof module.createFirebaseAuthAdapter,'function','real auth adapter must exist');const h=harness(options);const adapter=await module.createFirebaseAuthAdapter({sdk:h.sdk});await h.emit(h.user);return {h,adapter};}
test('existing Firebase UID and verified registry yield SuperAdmin',async()=>{const {h,adapter}=await create({claims:{admin:true}});assert.equal(adapter.state.actor.uid,'owner');assert.equal(adapter.state.actor.role,'super_admin');assert.equal(adapter.state.actor.ready,true);assert.ok(h.calls.includes('users/owner'));assert.ok(h.calls.includes('adminSecurity/config'));});
test('email never grants access and active assistants receive only allowed permissions',async()=>{const {adapter}=await create({record:{role:'admin_assistant',adminStatus:'active',permissions:['dashboard_view','invented']}});assert.equal(adapter.state.actor.role,'admin_assistant');assert.deepEqual(adapter.state.actor.permissions,['dashboard_view']);const other=await create();assert.equal(other.adapter.state.actor.role,null);});
test('suspended and blocked profiles cannot receive administrative access',async()=>{for(const status of ['suspended','blocked']){const {adapter}=await create({claims:{admin:true},profile:{status}});assert.equal(adapter.state.actor.active,false);assert.equal(adapter.state.actor.status,status);assert.equal(adapter.state.actor.role,null);assert.deepEqual(adapter.state.actor.permissions,[]);}});
test('failed registry reads never fall back to claim-only SuperAdmin',async()=>{const {adapter}=await create({claims:{admin:true},failure:'adminSecurity/config'});assert.equal(adapter.state.actor.role,null);assert.equal(adapter.state.actor.ready,false);});
test('profile read failure denies authenticated actions',async()=>{const {adapter}=await create({failure:'users/owner'});assert.equal(adapter.state.status,'error');assert.equal(adapter.state.actor.active,false);assert.equal(adapter.state.actor.role,null);});
test('Google popup preserves returned UID and logout clears access',async()=>{const {adapter}=await create({claims:{admin:true}});const result=await adapter.signInGoogle();assert.equal(result.user.uid,'owner');await adapter.signOut();assert.equal(adapter.state.status,'signed_out');assert.equal(adapter.state.actor.uid,null);});
test('subscriber sees role cleared while a different user resolves',async()=>{const {h,adapter}=await create({claims:{admin:true}});const states=[];const stop=adapter.subscribe(state=>states.push(state));await h.emit(null);assert.equal(states.at(-1).actor.role,null);assert.equal(states.at(-1).user,null);stop();adapter.dispose();});

test('unregistered claims and inactive assistants never grant roles',async()=>{for(const options of [{claims:{admin:true},config:{enabled:true,superAdminUids:['someone-else']}},{record:{role:'admin_assistant',adminStatus:'suspended',permissions:['users_manage']}},{claims:{admin:true},config:null},{profile:null}]){const {adapter}=await create(options);assert.equal(adapter.state.actor.role,null);assert.deepEqual(adapter.state.actor.permissions,[]);}});
test('stale profile resolution cannot restore a logged-out administrator',async()=>{const h=harness({claims:{admin:true}});let finish;const original=h.sdk.getDoc;h.sdk.getDoc=path=>path==='users/owner'?new Promise(resolve=>{finish=()=>resolve({data:()=>({status:'active'})})}):original(path);const adapter=await module.createFirebaseAuthAdapter({sdk:h.sdk});const pending=h.emit(h.user);await h.emit(null);finish();await pending;assert.equal(adapter.state.status,'signed_out');assert.equal(adapter.state.actor.role,null);});
test('popup cancellation propagates without creating a demo identity',async()=>{const {h,adapter}=await create();h.sdk.signInWithPopup=async()=>{throw Object.assign(Error('closed'),{code:'auth/popup-closed-by-user'})};await assert.rejects(adapter.signInGoogle(),{code:'auth/popup-closed-by-user'});assert.equal(adapter.state.actor.uid,'owner');assert.equal(adapter.state.actor.role,null);});
test('new default app uses the existing Firebase project and mismatched apps fail closed',async()=>{const h=harness();h.sdk.getApps=()=>[];h.sdk.initializeApp=config=>({name:'[DEFAULT]',options:config});h.sdk.getAuth=app=>{assert.equal(app.options.projectId,'souq-al-halal-9e3e8');return h.auth};const adapter=await module.createFirebaseAuthAdapter({sdk:h.sdk});await h.emit(h.user);assert.equal(adapter.state.actor.uid,'owner');const wrong=harness();wrong.sdk.getApp=()=>({name:'[DEFAULT]',options:{projectId:'other'}});await assert.rejects(module.createFirebaseAuthAdapter({sdk:wrong.sdk}),/AUTH_PROJECT_MISMATCH/);});
test('profile with missing status fails closed to match production rules',async()=>{const {adapter}=await create({claims:{admin:true},profile:{displayName:'Owner'}});assert.equal(adapter.state.actor.active,false);assert.equal(adapter.state.actor.status,'unknown_status');assert.equal(adapter.state.actor.role,null);assert.deepEqual(adapter.state.actor.permissions,[]);});

async function bootstrapHarness({profile=null,registry={enabled:true,superAdminUids:['owner']},writesEnabled=true,failWrite=false}={}){
 const h=harness({profile,config:registry,user:{uid:'new-user',displayName:'New Google user',email:'new@example.com',providerData:[{providerId:'google.com'}]}});let writes=0;
 h.sdk.serverTimestamp=()=>123;
 h.sdk.runTransaction=async(_db,fn)=>{const staged=[];await fn({get:path=>h.sdk.getDoc(path),set:(path,data)=>staged.push([path,data])});if(failWrite)throw Error('permission-denied');for(const [path,data]of staged){h.docs[path]=data;writes++;}};
 const adapter=await module.createFirebaseAuthAdapter({sdk:h.sdk,config:{writesEnabled}});await h.emit(h.user);return {h,adapter,writes};
}
test('runtime writes flag bootstraps Google profile with normal registry lacking writesEnabled',async()=>{const {h,adapter,writes}=await bootstrapHarness();assert.equal(writes,1);assert.equal(adapter.state.status,'authenticated');assert.equal(adapter.state.actor.status,'active');assert.equal(adapter.state.actor.role,null);assert.equal(h.docs['users/new-user'].email,'new@example.com');assert.equal(h.docs['users/new-user'].role,undefined);});
test('read-only runtime cannot be overridden by registry writesEnabled',async()=>{const {adapter,writes}=await bootstrapHarness({writesEnabled:false,registry:{enabled:true,superAdminUids:['owner'],writesEnabled:true}});assert.equal(writes,0);assert.equal(adapter.state.actor.status,'missing_profile');});
test('missing registry does not crash first Google profile bootstrap or grant administration',async()=>{const {adapter,writes}=await bootstrapHarness({registry:null});assert.equal(writes,1);assert.equal(adapter.state.actor.role,null);assert.equal(adapter.state.actor.ready,false);assert.equal(adapter.state.actor.status,'active');});
test('bootstrap never resets suspended or blocked profile and failed bootstrap grants nothing',async()=>{for(const status of ['suspended','blocked']){const {adapter,writes,h}=await bootstrapHarness({profile:{status,displayName:'Existing'}});assert.equal(writes,0);assert.equal(h.docs['users/new-user'].displayName,'Existing');assert.equal(adapter.state.actor.status,status);assert.equal(adapter.state.actor.active,false);}const {adapter,writes}=await bootstrapHarness({failWrite:true});assert.equal(writes,0);assert.equal(adapter.state.status,'error');assert.equal(adapter.state.actor.active,false);});
