const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
const sdk=`let app;export const getApps=()=>app?[app]:[],getApp=()=>app,initializeApp=options=>(app={name:'[DEFAULT]',options}),getAuth=()=>({currentUser:null}),getFirestore=()=>({});
export function onAuthStateChanged(auth,fn){queueMicrotask(()=>fn(null));return()=>{}};
export const collection=(db,name)=>name,query=(name,...constraints)=>({name,constraints}),where=(...args)=>args,orderBy=(...args)=>args,limit=n=>n;
export async function getDocs(q){window.reads.push(q.name);return {docs:q.name==='marketplaceListings'?[{id:'existing',data:()=>({title:'Existing MELKAK listing',country:'AE',status:'active',ownerUid:'existing-owner',category:'livestock',images:[],region:'الشارقة',city:'الذيد',price:400,type:'غنم',description:'Existing public animal',createdAt:Date.now()})}]:[]};}
export const doc=(db,...p)=>p.join('/'),getDoc=async()=>({data:()=>null});`;
(async()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'melkak-pages-live-'));const built=cp.spawnSync(process.execPath,['scripts/build-site.mjs','--mode','production','--out',out],{encoding:'utf8'});assert.equal(built.status,0,built.stderr);
 const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage(),errors=[],missing=[],requests=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>window.reads=[]);
 await page.route('**/*',async r=>{const u=new URL(r.request().url());requests.push(u.href);if(u.origin==='https://www.gstatic.com')return r.fulfill({contentType:'text/javascript',body:u.pathname.endsWith('/firebase-app.js')?sdk:'export {};',headers:{'access-control-allow-origin':'*'}});if(u.origin!=='https://iso9090.github.io')return r.abort();const f=path.resolve(out,'.'+u.pathname+(u.pathname==='/'?'index.html':''));if(!f.startsWith(out+path.sep)||!fs.existsSync(f)){missing.push(u.pathname);return r.fulfill({status:404,body:''})}return r.fulfill({body:fs.readFileSync(f),contentType:({'.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.ttf':'font/ttf','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});});
 await page.goto('https://iso9090.github.io/');await page.getByText('Existing MELKAK listing',{exact:true}).first().waitFor();assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);assert.equal(await page.locator('#preview-role').count(),0);assert.equal(await page.locator('.preview').count(),0);assert.equal((await page.evaluate(()=>window.reads)).includes('animals'),false);assert.ok((await page.evaluate(()=>window.reads)).includes('marketplaceListings'));
 assert.equal(requests.some(u=>/\/(fixtures|datasource|demo-auth)\.js/.test(u)),false);
 console.log('PASS actual production artifact / -> entry -> shared Firebase auth -> real datasource -> app with mocked SDK, modern schema and no legacy dependency');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
