const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});let n=0;try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!=='http://127.0.0.1:8817')return r.abort();const name=u.pathname.slice(1)||'index.html';if(name==='melkak/runtime-config.js')return r.fulfill({contentType:'text/javascript',body:'export default {mode:"local",datasource:"demo",reviewOrigin:""}'});if(name==='melkak/vendor/moderation/runtime.js')return r.fulfill({contentType:'text/javascript',body:`export async function loadLocalModel(){if(window.scanMode==='failure')throw Error('offline');return {async classify(){window.scanCalls=(window.scanCalls||0)+1;await new Promise(r=>setTimeout(r,100));if(window.scanMode==='failure')throw Error('offline');const k=window.scanMode==='reject'||window.scanMode==='borderline'?'Porn':'Neutral',p=window.scanMode==='borderline'?.7:.99;return ['Porn','Hentai','Sexy','Neutral','Drawing'].map(className=>({className,probability:className===k?p:(1-p)/4}));}}}`});const f=path.resolve(name);if(!f.startsWith(process.cwd()+path.sep)||!fs.existsSync(f))return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.ttf':'font/ttf'})[path.extname(f)]||'application/octet-stream'});});await page.goto('http://127.0.0.1:8817');await page.waitForFunction(()=>window.__melkak);await page.locator('#preview-role').selectOption('user');
await page.evaluate(()=>location.hash='#/add');await page.waitForFunction(()=>window.__melkak.state.draft);await page.evaluate(()=>{window.__melkak.state.step=3;window.__melkak.render()});
const file=path.resolve('melkak/assets/world-hero.webp');
for(const mode of ['reject','borderline','failure']){await page.evaluate(m=>window.scanMode=m,mode);await page.locator('#photo-picker').setInputFiles(file);await page.waitForFunction(()=>!window.__melkak.state.busy&&window.__melkak.state.error);assert.equal(await page.evaluate(()=>window.__melkak.state.draft.images.length),0);n++;}
assert.equal(await page.locator('[data-action=retry-image-scan]').count(),1);await page.evaluate(()=>window.scanMode='allow');await page.locator('[data-action=retry-image-scan]').click();await page.waitForFunction(()=>!window.__melkak.state.busy&&window.__melkak.state.draft.images.length===1);n++;
for(const width of [360,390,430,768,1024,1440])for(const lang of ['ar','en']){await page.setViewportSize({width,height:900});await page.evaluate(lang=>{window.__melkak.state.lang=lang;window.__melkak.render()},lang);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);n++;}
// Fresh safe images are all scanned before direct publication; no upload happens while scan is pending.
await page.evaluate(()=>{const w=window.__melkak;w.state.draft.title='Safe listing';w.state.draft.description='A valid safe description';w.state.draft.price=100;w.state.draft.contact={phone:'+971501234567',call:true,whatsapp:true,consent:true,showNumber:false};w.state.step=6;w.render();window.beforeListings=w.store.state.listings.length;});await page.locator('#wizard-form').evaluate(f=>{f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});await page.waitForFunction(()=>location.hash.startsWith('#/manage/'));assert.equal(await page.evaluate(()=>window.__melkak.store.state.listings.length-window.beforeListings),1);assert.equal(await page.evaluate(()=>window.__melkak.store.state.listings.find(x=>x.id===location.hash.split('/').at(-1)).status),'active');n++;
await page.locator('#preview-role').selectOption('super_admin');await page.evaluate(()=>location.hash='#/admin/listings');await page.locator('[data-action=moderate]').first().click();assert.equal(await page.locator('#moderate-form option[value=needs_review]').count(),1);await page.locator('#moderate-form select').selectOption('needs_review');await page.locator('#moderate-form textarea').fill('مراجعة صورة الإعلان');await page.locator('#moderate-form button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);assert.match(await page.locator('main').innerText(),/Needs review|يتطلب مراجعة/);n++;assert.deepEqual(errors,[]);n++;console.log('SUMMARY | '+n+'/'+n+' PASS');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
