import fs from 'node:fs';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails} from '@firebase/rules-unit-testing';
import * as sdk from 'firebase/firestore';
import {composeTransitionRules} from '../scripts/build-melkak-transition-rules.mjs';
import {composeReleaseRules} from '../scripts/build-melkak-release-rules.mjs';
import {ensureMarketplaceProfile} from '../melkak/profile-bootstrap.js';
import {attachProductionAdmin} from '../melkak/production-admin.js';
import {attachProductionSettings} from '../melkak/production-settings.js';
import {attachProductionServices} from '../melkak/production-services.js';
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080')throw Error('Local emulator 127.0.0.1:8080 required');
sdk.setLogLevel('silent');
const localRules=fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8'),proposedRules=fs.readFileSync(new URL('../melkak/firestore.proposed.rules',import.meta.url),'utf8');
const rules=process.env.MELKAK_BASELINE_RULES?composeReleaseRules(fs.readFileSync(process.env.MELKAK_BASELINE_RULES,'utf8'),localRules,proposedRules):composeTransitionRules(localRules,proposedRules);
if(process.env.MELKAK_EXPECTED_RELEASE_RULES)assert.equal(rules,fs.readFileSync(process.env.MELKAK_EXPECTED_RELEASE_RULES,'utf8'),'Emulator must test the exact generated release Rules');
const env=await initializeTestEnvironment({projectId:'demo-melkak-transition-admin',firestore:{rules}});
const failures=[];let passed=0;
async function check(name,fn){try{await fn();passed++;console.log('PASS',name);}catch(error){failures.push(name);console.error('FAIL',name,error.code||error.message);}}
const google=(uid,email=uid+'@example.com')=>({uid,email,displayName:'Registered '+uid,providerData:[{providerId:'google.com'}]});
const googleDb=uid=>env.authenticatedContext(uid,{email:uid+'@example.com',email_verified:true,firebase:{sign_in_provider:'google.com'}}).firestore();
const bossDb=env.authenticatedContext('boss',{admin:true}).firestore();
const actor=(uid,role='super_admin',permissions=[])=>({uid,role,permissions,status:'active',ready:true,protectedUids:['boss','protected']});
const admin=(db,a)=>attachProductionAdmin({refresh:async()=>{}},{sdk,db,auth:{state:{actor:a}},config:{writesEnabled:true}});
const boss=admin(bossDb,actor('boss'));
const get=async(collection,id)=>(await sdk.getDoc(sdk.doc(bossDb,collection,id))).data();
try{
 await env.clearFirestore();await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();for(const uid of ['boss','protected','member','candidate','scoped','peer','suspended'])await sdk.setDoc(sdk.doc(db,'users',uid),{status:uid==='suspended'?'suspended':'active',displayName:'Original '+uid,email:uid+'@example.com'});await sdk.setDoc(sdk.doc(db,'adminSecurity','config'),{enabled:true,superAdminUids:['boss','protected']});for(const uid of ['scoped','peer'])await sdk.setDoc(sdk.doc(db,'adminAccess',uid),{role:'admin_assistant',adminStatus:'active',permissions:uid==='scoped'?['users_view','users_suspend','users_block','users_manage','assistants_view']:['users_view'],createdByAdminUid:'boss',adminCreatedAt:sdk.Timestamp.now(),adminUpdatedAt:sdk.Timestamp.now(),moderationLogId:'seed'});});
 await check('Google first profile creates active non-admin profile',async()=>{await ensureMarketplaceProfile({sdk,db:googleDb('new-google'),user:google('new-google'),enabled:true});const p=await get('users','new-google');assert.equal(p.status,'active');assert.equal(p.uid,'new-google');assert.equal(p.role,undefined);});
 await check('Google bootstrap preserves suspended existing profile',async()=>{await ensureMarketplaceProfile({sdk,db:googleDb('suspended'),user:google('suspended'),enabled:true});const p=await get('users','suspended');assert.equal(p.status,'suspended');assert.equal(p.displayName,'Original suspended');});
 await check('Google cannot forge admin profile fields',async()=>{await assertFails(sdk.setDoc(sdk.doc(googleDb('forged'),'users','forged'),{uid:'forged',displayName:'Fake',email:'forged@example.com',phone:'',phoneNumber:'',accountType:'buyer',authProvider:'google',status:'active',createdAt:sdk.serverTimestamp(),lastLoginAt:sdk.serverTimestamp(),role:'super_admin'}));});
 await check('user status suspend reactivate block with audit',async()=>{for(const status of ['suspended','active','blocked','active']){await boss.setUserStatus('member',status,'Reviewed user status');const p=await get('users','member');assert.equal(p.status,status);assert.equal(p.displayName,'Original member');const log=await get('adminAuditLogs',p.moderationLogId);assert.equal(log.targetId,'member');assert.equal(log.adminUid,'boss');}});
 await check('scoped assistant can manage normal users but not peer or owners',async()=>{const scoped=admin(env.authenticatedContext('scoped').firestore(),actor('scoped','admin_assistant',['users_view','users_suspend','users_block','users_manage','assistants_view']));await scoped.setUserStatus('member','suspended','Scoped moderation');await scoped.setUserStatus('member','active','Scoped restore');for(const uid of ['peer','boss','protected','scoped'])await assert.rejects(()=>scoped.setUserStatus(uid,'blocked','Forbidden target'));});
 await check('minimal user moderator needs no assistants_view and Rules deny peer owner escalation',async()=>{
  await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await sdk.setDoc(sdk.doc(db,'users','minimal'),{status:'active'});await sdk.setDoc(sdk.doc(db,'adminAccess','minimal'),{role:'admin_assistant',adminStatus:'active',permissions:['users_view','users_suspend']});});
  const minimalDb=env.authenticatedContext('minimal').firestore(),minimal=admin(minimalDb,actor('minimal','admin_assistant',['users_view','users_suspend']));
  await assertFails(sdk.getDoc(sdk.doc(minimalDb,'adminAccess','member')));
  await minimal.setUserStatus('member','suspended','Minimal scoped moderation');assert.equal((await get('users','member')).status,'suspended');
  await assert.rejects(()=>minimal.setUserStatus('peer','suspended','Cannot moderate peer'));
  for(const uid of ['boss','protected','minimal'])await assert.rejects(()=>minimal.setUserStatus(uid,'suspended','Cannot moderate owner or self'));
  await boss.setUserStatus('member','active','Restore after minimal permission test');
 });
 await check('unprivileged and forged owner clients denied',async()=>{const memberDb=env.authenticatedContext('member').firestore();await assert.rejects(()=>admin(memberDb,actor('member')).setUserStatus('candidate','blocked','Forged owner'));await assert.rejects(()=>admin(env.authenticatedContext('boss').firestore(),actor('boss')).grantAssistant('candidate',[],'Missing signed claim'));});
 await check('owner and self cannot be changed',async()=>{for(const uid of ['boss','protected']){await assert.rejects(()=>boss.setUserStatus(uid,'blocked','Protected account'));await assert.rejects(()=>boss.grantAssistant(uid,[],'Protected account'));}});
 await check('assistant full lifecycle preserves existing user identity',async()=>{const before=await get('users','candidate');await boss.grantAssistant('candidate',['dashboard_view','listings_view'],'Assign scoped assistant');assert.equal((await get('adminAccess','candidate')).adminStatus,'active');await boss.updateAssistant('candidate',{permissions:['reports_view']},'Change scoped permissions');assert.deepEqual((await get('adminAccess','candidate')).permissions,['reports_view']);await boss.updateAssistant('candidate',{adminStatus:'suspended'},'Suspend assistant');assert.equal((await get('adminAccess','candidate')).adminStatus,'suspended');await boss.updateAssistant('candidate',{adminStatus:'active'},'Reactivate assistant');await boss.removeAssistant('candidate','Remove assistant role');const record=await get('adminAccess','candidate');assert.equal(record.role,'removed');assert.deepEqual(record.permissions,[]);assert.deepEqual(await get('users','candidate'),before);const log=await get('adminAuditLogs',record.moderationLogId);assert.equal(log.action,'assistant_role_removed');assert.deepEqual(log.metadata.oldPermissions,['reports_view']);});
 await check('assistant self escalation via direct SDK denied',async()=>{const db=env.authenticatedContext('scoped').firestore();await assertFails(sdk.updateDoc(sdk.doc(db,'adminAccess','scoped'),{role:'super_admin',permissions:['assistants_create']}));await assertFails(sdk.updateDoc(sdk.doc(db,'users','scoped'),{role:'super_admin'}));});
 await check('category create and update audited atomically',async()=>{const store=attachProductionServices({state:{categories:[{id:'cars'}],listings:[]},refresh:async()=>{}},{sdk,db:bossDb,auth:{state:{actor:actor('boss')}},config:{writesEnabled:true}});await store.configureCategory('cars',{enabled:true,order:1,featured:false,icon:'car'});let data=await get('marketplaceCategories','cars');assert.equal((await get('marketplaceAuditLogs',data.auditId)).action,'category-update');await store.configureCategory('cars',{enabled:false});data=await get('marketplaceCategories','cars');assert.equal(data.enabled,false);});
 await check('settings and city create update with immutable audit',async()=>{const settings=attachProductionSettings({refresh:async()=>{}},{sdk,db:bossDb,auth:{state:{actor:actor('boss')}},config:{writesEnabled:true}});await settings.configureSettings({enabledCountries:['AE','SA'],supportText:'Contact support'},'Initial settings');await settings.configureSettings({enabledCountries:['AE'],supportText:'Updated support'},'Update settings');await settings.configureCity('dubai',{country:'AE',region:'Dubai',name:'Dubai',enabled:true},'Add city');await settings.configureCity('dubai',{country:'AE',region:'Dubai',name:'Dubai',enabled:false},'Disable city');const city=await get('marketplaceCities','dubai');assert.equal(city.enabled,false);const log=await get('marketplaceAuditLogs',city.auditId);assert.equal(log.action,'city-update');await assertFails(sdk.updateDoc(sdk.doc(bossDb,'marketplaceAuditLogs',city.auditId),{reason:'Edited history'}));});
 await check('blank legacy audit denied even for owner direct SDK',async()=>{await assertFails(sdk.setDoc(sdk.doc(bossDb,'adminAuditLogs','blank'),{adminUid:'boss',action:'إعادة التفعيل',targetType:'users',targetId:'member',reason:'   ',timestamp:sdk.serverTimestamp(),metadata:{}}));});
 await check('blank marketplace linked audit denied direct SDK',async()=>{const batch=sdk.writeBatch(bossDb);batch.set(sdk.doc(bossDb,'marketplaceSettings','public'),{enabledCountries:['AE'],supportText:'',updatedAt:sdk.serverTimestamp(),auditId:'blank'});batch.set(sdk.doc(bossDb,'marketplaceAuditLogs','blank'),{actorUid:'boss',action:'settings-update',targetCollection:'marketplaceSettings',targetId:'public',reason:'   ',timestamp:sdk.serverTimestamp(),result:'updated'});await assertFails(batch.commit());});
 console.log(`Transition admin emulator: ${passed} passed, ${failures.length} failed`);if(failures.length){console.error(failures.join('\n'));process.exitCode=1;}
}finally{await env.cleanup();}
