const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
(async()=>{const {CATEGORIES}=await import('../melkak/config.js');const browser=await chromium.launch({channel:'chrome',headless:true});let count=0;
try{const page=await browser.newPage({hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!=='http://127.0.0.1:8817')return r.abort();const name=u.pathname.slice(1)||'index.html';if(name==='melkak/runtime-config.js')return r.fulfill({contentType:'text/javascript',body:'export default {mode:"local",datasource:"demo",reviewOrigin:""}'});const file=path.resolve(name);if(!file.startsWith(process.cwd()+path.sep)||!fs.existsSync(file))return r.fulfill({status:404,body:''});return r.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.ttf':'font/ttf'})[path.extname(file)]||'application/octet-stream'});});
await page.goto('http://127.0.0.1:8817');await page.waitForFunction(()=>window.__melkak);await page.locator('#preview-role').selectOption('user');

for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:950});for(const lang of ['ar','en']){await page.evaluate(lang=>{window.__melkak.state.lang=lang;window.__melkak.render()},lang);const select=page.locator(width<=800?'.mobile-location [data-country]':'.top-location [data-country]');assert.ok(await select.isVisible());if(width>800){const bounds=await page.locator(".top-location").boundingBox(),row=await page.locator("header.topbar>div.wrap").boundingBox();assert.ok(bounds.y>=row.y&&bounds.y+bounds.height<=row.y+row.height,"Location controls must fit within header row");}assert.equal(await select.evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(232, 246, 252)','Country selector must be light blue');await select.focus();assert.notEqual(await select.evaluate(el=>getComputedStyle(el).outlineStyle),'none');await select.selectOption('EG');assert.equal(await select.inputValue(),'EG');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));count++;}}
await page.locator('#preview-role').selectOption('super_admin');await page.evaluate(()=>location.hash='#/admin');await page.locator('#admin-country').waitFor();assert.equal(await page.locator('#admin-country').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(232, 246, 252)');assert.equal(errors.length,0);console.log('SUMMARY | '+(count+2)+'/'+(count+2)+' PASS');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
