const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',route=>{const url=new URL(route.request().url());const file=path.resolve('.'+url.pathname);if(url.origin!=='https://mock.test'||!file.startsWith(path.resolve('.')+path.sep)||!fs.existsSync(file))return route.abort();return route.fulfill({contentType:file.endsWith('.css')?'text/css':'text/javascript',body:fs.readFileSync(file)});});
 await page.route('https://mock.test/',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><link rel="stylesheet" href="/melkak/phase1.css"><style>body{margin:16px;font-family:Arial}dialog{max-width:calc(100vw - 64px)}textarea,input,select{max-width:100%;box-sizing:border-box}label{display:block}button{min-height:40px}</style></head><body><main></main><dialog id="dialog"></dialog><script type="module">
 import {phase1Views} from '/melkak/phase1-views.js';import {reportReasonFields,serializeReportReason} from '/melkak/reporting.js';
 window.calls=[];window.lang='en';window.permissions=['reports_view','reports_manage','listings_view','listings_manage','users_view'];
 const image='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="60" height="40"%3E%3Crect width="60" height="40" fill="green"/%3E%3C/svg%3E';
 const state={reports:[{id:'r1',listingId:'l1',reason:'[image] Reported photograph',status:'open',reporterUid:'SECRET_REPORTER'}],listings:[{id:'l1',ownerUid:'u1',title:'Example listing',description:'Saved description',status:'active',images:[image,image+'#two']}],users:[{uid:'u1',displayName:'Seller',status:'active'}]};
 const c={store:{state,reportUser:async(id,reason)=>{window.calls.push(['report',reason]);await new Promise(resolve=>setTimeout(resolve,100))},removeListingImage:async(...a)=>window.calls.push(['image',...a]),actOnReport:async(...a)=>window.calls.push(['action',...a])},s:{},render:()=>window.render(),toast:()=>{},errorText:e=>e.message,actor:()=>({uid:'admin'}),can:(_,p)=>window.permissions.includes(p),t:(ar,en)=>window.lang==='ar'?ar:en,esc:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),button:(text,action,attrs='')=>'<button data-action="'+action+'" '+attrs+'>'+text+'</button>',asset:s=>s,noData:s=>s,openDialog:(_,html)=>{const d=document.querySelector('dialog');d.innerHTML=html;if(!d.open)d.showModal()}};
 window.reportContext=c;const v=phase1Views(c);v.bind();window.render=()=>{document.documentElement.dir=window.lang==='ar'?'rtl':'ltr';document.querySelector('main').innerHTML=v.reports()};window.openReport=()=>c.openDialog('', '<form id="user-report-form">'+reportReasonFields(c)+'<button type="submit">Submit</button></form>');window.render();
 </script></body></html>`}));
 await page.goto('https://mock.test/');await page.locator('[data-action=report-actions]').waitFor();assert.ok(!(await page.locator('body').innerText()).includes('SECRET_REPORTER'));
 await page.evaluate(()=>window.openReport());assert.equal(await page.locator('select[name=category] option').count(),9);await page.locator('select[name=category]').selectOption('fraud');await page.locator('dialog button[type=submit]').click();assert.deepEqual(await page.evaluate(()=>window.calls.pop()),['report','[fraud]']);
 await page.locator('dialog').waitFor({state:'hidden'});await page.evaluate(()=>window.openReport());await page.locator('select[name=category]').selectOption('image');await page.evaluate(()=>{const f=document.querySelector('dialog form');f.requestSubmit();f.requestSubmit()});await page.locator('dialog').waitFor({state:'hidden'});assert.deepEqual(await page.evaluate(()=>window.calls.splice(0)),[['report','[image]']]);
 await page.locator('[data-action=report-actions]').click();await page.locator('select[name=action]').selectOption('needs_review');await page.locator('textarea').fill('   ');await page.locator('#report-action-form').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(await page.evaluate(()=>window.calls.length),0);await page.locator('textarea').fill('Reviewed evidence');await page.locator('button[type=submit]').click();assert.deepEqual((await page.evaluate(()=>window.calls.pop())).slice(0,4),['action','r1','needs_review','Reviewed evidence']);
 await page.locator('[data-action=report-listing]').click();await page.locator('[data-action=report-remove-image]').nth(1).click();assert.ok((await page.locator('.report-remove-preview').getAttribute('src')).endsWith('#two'));await page.locator('textarea').fill('Remove reported photo');await page.locator('button[type=submit]').click();const removed=await page.evaluate(()=>window.calls.pop());assert.equal(removed[0],'image');assert.ok(removed[2].endsWith('#two'));
 for(const lang of ['ar','en'])for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.evaluate(l=>{window.lang=l;window.render()},lang);await page.locator('[data-action=report-listing]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,lang+' '+width);await page.evaluate(()=>document.querySelector('dialog').close())}
 await page.evaluate(()=>{const c=window.reportContext,s=c.store.state,a=s.listings[0];s.listings=[];s.users=[];c.store.loadListing=async id=>{await new Promise(r=>setTimeout(r,20));s.listings.push(a);return a};c.store.loadUser=async uid=>({uid,displayName:'Lazy seller',status:'active'});window.render()});
 await page.locator('[data-action=report-listing]').click();await page.locator('.report-listing-detail').waitFor();assert.ok((await page.locator('dialog').innerText()).includes('Example listing'));await page.evaluate(()=>document.querySelector('dialog').close());await page.locator('[data-action=report-target-user]').click();await page.getByRole('heading',{name:'Lazy seller'}).waitFor();await page.evaluate(()=>document.querySelector('dialog').close());
 await page.evaluate(()=>{window.permissions=['reports_view'];window.render()});assert.equal(await page.locator('main [data-action]').count(),0);assert.deepEqual(errors,[]);console.log('PASS report mock browser: category, optional detail, decisions, exact photo, scoped actions, RTL/LTR six widths');
 }finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
