import assert from 'node:assert/strict';
import * as module from '../melkak/report-moderation-view.js';
assert.equal(typeof module.createReportModerationViews,'function','moderation controller exists');
let dialog='',permissions=['reports_view','reports_manage','listings_view','listings_manage','users_view'];const calls=[];
const listing={id:'l1',ownerUid:'u1',title:'<unsafe>',description:'Details',status:'hidden',images:['data:image/jpeg;base64,AAA','data:image/jpeg;base64,BBB']};
const store={state:{reports:[{id:'r1',listingId:'l1',reason:'fraud',status:'open',reporterUid:'private'}],listings:[listing],users:[{uid:'u1',displayName:'Seller',status:'active'}]},removeListingImage:async(...args)=>calls.push(args),actOnReport:async(...args)=>calls.push(args)};
const c={s:{},store,actor:()=>({uid:'a'}),can:(_,p)=>permissions.includes(p),t:(_,en)=>en,esc:s=>String(s??'').replaceAll('<','&lt;').replaceAll('"','&quot;'),button:(text,action,attrs='')=>`<button data-action="${action}" ${attrs}>${text}</button>`,asset:s=>s,openDialog:(_,html)=>dialog=html,noData:s=>s};
const view=module.createReportModerationViews(c);
assert.ok(view.reports().includes('report-listing'));assert.ok(!view.reports().includes('private'));
assert.equal(view.handleClick({dataset:{action:'report-actions',id:'r1'}}),true);assert.ok(dialog.includes('needs_review'));assert.ok(dialog.includes('value="resolve"'));assert.ok(dialog.includes('minlength="3"'));
view.handleClick({dataset:{action:'report-listing',id:'r1'}});assert.ok(dialog.includes('&lt;unsafe>'));assert.ok(dialog.includes('report-remove-image'));assert.ok(dialog.includes('AAA'));
view.handleClick({dataset:{action:'report-remove-image',id:'r1',index:'1'}});assert.ok(dialog.includes('report-image-form'));
const form={id:'report-image-form',dataset:{id:'r1'}};
await view.handleSubmit(form,new Map([['reason','offending image']]));assert.deepEqual(calls.pop(),['l1',listing.images[1],'offending image']);
await assert.rejects(()=>view.handleSubmit({id:'report-action-form',dataset:{id:'r1'}},new Map([['action','hide'],['reason','  ']])),{code:'REASON'});
permissions=['reports_view','reports_manage'];view.handleClick({dataset:{action:'report-actions',id:'r1'}});assert.ok(!dialog.includes('needs_review'));assert.ok(!view.reports().includes('report-listing'));
assert.throws(()=>view.handleClick({dataset:{action:'report-remove-image',id:'r1',index:'0'}}),{code:'PERMISSION'});
console.log('PASS private reports, scoped details, exact-image removal and audited decision UI');
permissions=['reports_view','reports_manage','listings_view','listings_manage','users_view'];
store.state.listings=[];store.state.users=[];
store.loadListing=async id=>{assert.equal(id,'l1');store.state.listings.push(listing);return listing};
store.loadUser=async uid=>({uid,displayName:'Late seller',status:'active'});
await view.handleClick({dataset:{action:'report-listing',id:'r1'}});assert.ok(dialog.includes('AAA'));
await view.handleClick({dataset:{action:'report-target-user',id:'r1'}});assert.ok(dialog.includes('Late seller'));
store.state.listings=[];let finish;store.loadListing=()=>new Promise(resolve=>finish=resolve);
const pending=view.handleClick({dataset:{action:'report-listing',id:'r1'}});permissions=[];finish(listing);const previous=dialog;await pending;assert.equal(dialog,previous,'permission revocation must not open private dialog');
permissions=['reports_view','listings_view'];store.loadListing=async()=>null;await view.handleClick({dataset:{action:'report-listing',id:'r1'}});assert.ok(dialog.includes('unavailable'));
console.log('PASS lazy report listing/user details and revoked permissions');
// Missing records and superseded opens have explicit, non-stale outcomes.
store.state.capabilities={'listing:l1':{status:'empty'}};
await view.handleClick({dataset:{action:'report-listing',id:'r1'}});assert.ok(dialog.includes('no longer exists'));
permissions=['reports_view','listings_view','users_view'];store.state.listings=[listing];store.loadUser=()=>new Promise(resolve=>finish=resolve);
const userPending=view.handleClick({dataset:{action:'report-target-user',id:'r1'}});
await view.handleClick({dataset:{action:'report-listing',id:'r1'}});const latest=dialog;finish({uid:'u1',displayName:'Stale name'});await userPending;assert.equal(dialog,latest);
console.log('PASS missing and superseded report detail reads');
