import fs from 'node:fs';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import * as sdk from 'firebase/firestore';
import {createProductionDatasource} from '../melkak/production-datasource.js';
import {attachProductionServices} from '../melkak/production-services.js';
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080')throw Error('Local emulator 127.0.0.1:8080 required');
sdk.setLogLevel('silent');
const env=await initializeTestEnvironment({projectId:'demo-melkak-production-services',firestore:{rules:fs.readFileSync(new URL('../melkak/firestore.proposed.rules',import.meta.url),'utf8')}});
const countries={AE:{currency:'AED',dial:'971',regions:{Sharjah:['Dhaid']}}};
const draft={category:'cars',country:'AE',region:'Sharjah',city:'Dhaid',title:'Emulator car',description:'Local emulator test vehicle',price:100,images:['data:image/jpeg;base64,/9j/AA=='],attributes:{},contact:{phone:'+971500000000',call:true,whatsapp:false,showNumber:false,consent:true}};
const db=env.authenticatedContext('seller').firestore(),other=env.authenticatedContext('other').firestore(),adminDb=env.authenticatedContext('boss',{admin:true}).firestore();
function service(db,uid,role=null,permissions=[]){return attachProductionServices({state:{listings:[],categories:[{id:'cars',enabled:true}]},refresh:async()=>{}},{sdk,db,auth:{state:{actor:{uid,status:'active',role,permissions,ready:true}}},config:{writesEnabled:true},countries});}
const seller=service(db,'seller'),outsider=service(other,'other'),boss=service(adminDb,'boss','super_admin');
let passed=0;
async function check(name,fn){await fn();passed++;console.log('PASS',name);}
const ref=id=>sdk.doc(db,'marketplaceListings',id.replace(/^marketplace-/,''));
try{
 await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();for(const uid of ['seller','other','boss','assistant','suspended'])await sdk.setDoc(sdk.doc(d,'users',uid),{status:uid==='suspended'?'suspended':'active'});await sdk.setDoc(sdk.doc(d,'marketplaceCategories','cars'),{enabled:true});await sdk.setDoc(sdk.doc(d,'adminSecurity','config'),{enabled:true,superAdminUids:['boss']});await sdk.setDoc(sdk.doc(d,'adminAccess','assistant'),{role:'admin_assistant',adminStatus:'active',permissions:['listings_view','listings_manage','reports_view','reports_manage']});});
 let a;
 await check('create records actual auth UID with bounded inline images',async()=>{a=await seller.create(draft,{uid:'forged',role:'super_admin'});const d=(await sdk.getDoc(ref(a.id))).data();assert.equal(d.ownerUid,'seller');assert.equal(d.hasHistory,false);assert.deepEqual(d.images,draft.images);});
 await check('owner edits, hides, republishes and clean deletes',async()=>{await seller.update(a.id,{title:'Changed title'});await seller.transition(a.id,'hidden');assert.equal((await sdk.getDoc(ref(a.id))).data().hiddenBy,'owner');await seller.transition(a.id,'active');await seller.transition(a.id,'deleted');await env.withSecurityRulesDisabled(async c=>assert.equal((await sdk.getDoc(sdk.doc(c.firestore(),'marketplaceListings',a.id.replace(/^marketplace-/,'')))).exists(),false));});
 a=await seller.create(draft);
 await check('other user cannot update/delete',async()=>{await assert.rejects(()=>outsider.update(a.id,{title:'stolen'}));await assertFails(sdk.deleteDoc(sdk.doc(other,'marketplaceListings',a.id.replace(/^marketplace-/,''))));});
 await check('invalid and excessive images denied',async()=>{await assert.rejects(()=>seller.create({...draft,images:['https://example.org/image.jpg']}),{code:'IMAGES'});await assertFails(sdk.updateDoc(ref(a.id),{images:['data:image/jpeg;base64,'+'A'.repeat(210001)],updatedAt:sdk.serverTimestamp()}));});
 let request;
 await check('featured request atomically adds permanent history',async()=>{request=await seller.requestService(a.id,'featured',null,{days:7});const d=(await sdk.getDoc(ref(a.id))).data();assert.equal(d.hasHistory,true);assert.equal((await sdk.getDoc(sdk.doc(db,'marketplaceRequests',request.id))).data().ownerUid,'seller');await assert.rejects(()=>seller.transition(a.id,'deleted'),{code:'HISTORY'});});
 await check('owner cannot clear history or forge featured approval',async()=>{await assertFails(sdk.updateDoc(ref(a.id),{hasHistory:false,updatedAt:sdk.serverTimestamp()}));await assertFails(sdk.updateDoc(ref(a.id),{featuredStatus:'approved',updatedAt:sdk.serverTimestamp()}));});
 await check('forged caller role cannot approve',async()=>{await assert.rejects(()=>seller.approveService(request.id,'approved by me',{role:'super_admin',uid:'boss'}),{code:'PERMISSION'});});
 await check('admin approval stores bounded schedule and atomic audit',async()=>{await boss.approveService(request.id,'Reviewed featured request');const d=(await sdk.getDoc(ref(a.id))).data();assert.equal(d.featuredStatus,'approved');assert.equal(d.featuredEndAt-d.featuredStartAt,7*86400000);const audit=(await sdk.getDoc(sdk.doc(adminDb,'marketplaceAuditLogs',d.auditId))).data();assert.equal(audit.actorUid,'boss');assert.equal(audit.result,'approved');assert.ok(audit.reason);});
 await check('auditless admin moderation denied',async()=>{await assertFails(sdk.updateDoc(sdk.doc(adminDb,'marketplaceListings',a.id.replace(/^marketplace-/,'')),{status:'hidden',hiddenBy:'admin',moderationLocked:true,hasHistory:true,updatedAt:sdk.serverTimestamp()}));});
 await check('admin moderation locks listing against owner republish',async()=>{await boss.moderate(a.id,'hidden','Policy violation reviewed');await assert.rejects(()=>seller.transition(a.id,'active'),{code:'MODERATED'});});
 let b=await seller.create(draft);
 await check('report by other user atomically protects parent',async()=>{await outsider.report(b.id,'Incorrect listing information');assert.equal((await sdk.getDoc(ref(b.id))).data().hasHistory,true);await assertFails(sdk.deleteDoc(ref(b.id)));});
 await check('request cannot be orphaned or bypass parent history',async()=>{for(const listingId of ['missing',(await seller.create(draft)).id.replace(/^marketplace-/,'')])await assertFails(sdk.setDoc(sdk.doc(other,'marketplaceRequests','orphan-'+listingId),{type:'report',ownerUid:'other',listingId,reason:'Invalid advertisement',status:'open',createdAt:sdk.serverTimestamp()}));});
 await check('legacy mutation explicitly denied',async()=>{await assert.rejects(()=>seller.update('legacy-existing',{title:'changed'}),{code:'LEGACY'});await assertFails(sdk.setDoc(sdk.doc(db,'animals','legacy'),draft));});
 await check('sold listing cannot delete',async()=>{const c=await seller.create(draft);await seller.transition(c.id,'sold');await assert.rejects(()=>seller.transition(c.id,'deleted'),{code:'HISTORY'});});
 await check('unsupported paid services remain explicit',async()=>{await assert.rejects(()=>seller.requestService(b.id,'verification'),{code:'UNSUPPORTED_PRODUCTION_ACTION'});});
 await check('suspended profile cannot create',async()=>{await assert.rejects(()=>service(env.authenticatedContext('suspended').firestore(),'suspended').create(draft));});
 await check('auth supporting reads and self escalation denied',async()=>{await assertSucceeds(sdk.getDoc(sdk.doc(db,'users','seller')));await assertSucceeds(sdk.getDoc(sdk.doc(db,'adminAccess','seller')));await assertSucceeds(sdk.getDoc(sdk.doc(db,'adminSecurity','config')));await assertFails(sdk.setDoc(sdk.doc(db,'adminAccess','seller'),{role:'super_admin'}));await assertFails(sdk.updateDoc(sdk.doc(db,'adminSecurity','config'),{superAdminUids:['seller']}));});

 await check('commercial request and audited approval preserve legacy ads',async()=>{const c=await seller.requestCommercial({title:'Campaign',advertiserName:'Store',description:'Test campaign',cta:'Visit store',image:draft.images[0],targetUrl:'https://example.org/store',countryTarget:'AE',placement:'hero',startAt:Date.now(),endAt:Date.now()+86400000,priority:5});await boss.reviewCommercial(c.id,'approved','Campaign reviewed');const d=(await sdk.getDoc(sdk.doc(db,'marketplaceRequests',c.id))).data();assert.equal(d.status,'approved');await boss.reviewCommercial(c.id,'paused','Campaign paused');await assert.rejects(()=>seller.reviewCommercial(c.id,'approved','Forged approval',{role:'super_admin'}),{code:'PERMISSION'});});
 await check('assistant can moderate and resolve reports but cannot feature',async()=>{const assistant=service(env.authenticatedContext('assistant').firestore(),'assistant','admin_assistant',['listings_manage','reports_manage']);const l=await seller.create(draft);const r=await outsider.report(l.id,'Assistant report test');await assistant.actOnReport(r.id,'hide','Moderation reviewed');await assert.rejects(()=>assistant.approveService(request.id,'No authority'),{code:'PERMISSION'});assert.equal((await sdk.getDoc(ref(l.id))).data().hiddenBy,'admin');});
 await check('unregistered admin claim cannot moderate',async()=>{const imp=service(env.authenticatedContext('other',{admin:true}).firestore(),'other','super_admin');await assert.rejects(()=>imp.moderate(b.id,'hidden','Forged registry claim'));});
 await check('concurrent report/delete cannot leave orphan request',async()=>{const l=await seller.create(draft);const outcomes=await Promise.allSettled([outsider.report(l.id,'Concurrent report'),seller.transition(l.id,'deleted')]);assert.ok(outcomes.some(o=>o.status==='fulfilled'));await env.withSecurityRulesDisabled(async c=>{const d=c.firestore();const rows=await sdk.getDocs(sdk.query(sdk.collection(d,'marketplaceRequests'),sdk.where('listingId','==',l.id.replace(/^marketplace-/,''))));const parent=await sdk.getDoc(sdk.doc(d,'marketplaceListings',l.id.replace(/^marketplace-/,'')));if(rows.size){assert.ok(parent.exists());assert.equal(parent.data().hasHistory,true);}});});
 await check('request rejection and user report audit',async()=>{const l=await seller.create(draft),r=await seller.requestService(l.id,'featured');await boss.rejectService(r.id,'Request declined');assert.equal((await sdk.getDoc(sdk.doc(db,'marketplaceRequests',r.id))).data().status,'rejected');const u=await outsider.reportUser('seller','User report reason');await boss.resolveReport(u.id,'Report resolved');assert.equal((await sdk.getDoc(sdk.doc(other,'marketplaceRequests',u.id))).data().status,'resolved');});
 await check('category configuration requires atomic audit',async()=>{await boss.configureCategory('cars',{enabled:true,order:1,featured:false,icon:'car'});await assertFails(sdk.updateDoc(sdk.doc(adminDb,'marketplaceCategories','cars'),{enabled:false,updatedAt:sdk.serverTimestamp()}));});
 await check('audit records immutable even to registered admin',async()=>{const logs=await sdk.getDocs(sdk.collection(adminDb,'marketplaceAuditLogs'));assert.ok(logs.size>0);await assertFails(sdk.updateDoc(logs.docs[0].ref,{reason:'changed'}));await assertFails(sdk.deleteDoc(logs.docs[0].ref));});

 await check('assistant permissions are read from registry, not client actor',async()=>{const limited=service(env.authenticatedContext('other').firestore(),'other','admin_assistant',['listings_manage','reports_manage']);await assert.rejects(()=>limited.moderate(b.id,'hidden','Fake permission list'));});
 await check('private requests cannot be read by another account',async()=>{await assertFails(sdk.getDoc(sdk.doc(other,'marketplaceRequests',request.id)));await assertFails(sdk.getDocs(sdk.collection(other,'marketplaceAuditLogs')));await assertSucceeds(sdk.getDocs(sdk.query(sdk.collection(db,'marketplaceRequests'),sdk.where('ownerUid','==','seller'))));});
 await check('assistant report query allowed and service query denied',async()=>{const ad=env.authenticatedContext('assistant').firestore();await assertSucceeds(sdk.getDocs(sdk.query(sdk.collection(ad,'marketplaceRequests'),sdk.where('type','==','report'))));await assertFails(sdk.getDocs(sdk.query(sdk.collection(ad,'marketplaceRequests'),sdk.where('type','in',['featured','commercial']))));});
 await check('anonymous can only read active public listings',async()=>{const anon=env.unauthenticatedContext().firestore();await assertSucceeds(sdk.getDoc(sdk.doc(anon,'marketplaceListings',b.id.replace(/^marketplace-/,''))));await assertFails(sdk.getDoc(sdk.doc(anon,'marketplaceListings',a.id.replace(/^marketplace-/,''))));await assertFails(sdk.getDoc(sdk.doc(anon,'marketplaceRequests',request.id)));});
 await check('featured duration and reasons are required and bounded',async()=>{await assert.rejects(()=>seller.requestService(b.id,'featured',null,{days:366}),{code:'DURATION'});await assert.rejects(()=>boss.moderate(b.id,'hidden',''),{code:'REASON'});await assert.rejects(()=>outsider.report(b.id,'x'.repeat(501)),{code:'REASON'});});
 await check('same batch cannot delete parent while creating linked request',async()=>{const l=await seller.create(draft),batch=sdk.writeBatch(db),parent=ref(l.id);batch.delete(parent);batch.set(sdk.doc(db,'marketplaceRequests','malicious-orphan'),{type:'report',ownerUid:'seller',listingId:parent.id,status:'open',reason:'Attempt orphan report',createdAt:sdk.serverTimestamp()});await assertFails(batch.commit());});


 await check('featured request approval cannot omit listing activation',async()=>{const l=await seller.create(draft),r=await seller.requestService(l.id,'featured'),batch=sdk.writeBatch(adminDb),ar=sdk.doc(sdk.collection(adminDb,'marketplaceAuditLogs'));batch.update(sdk.doc(adminDb,'marketplaceRequests',r.id),{status:'approved',auditId:ar.id,updatedAt:sdk.serverTimestamp()});batch.set(ar,{actorUid:'boss',action:'service-approved',targetId:r.id,targetCollection:'marketplaceRequests',reason:'Incomplete activation attempt',timestamp:sdk.serverTimestamp(),result:'approved'});await assertFails(batch.commit());});
 await check('actual adapter guest public query returns active new listings',async()=>{const auth={state:{actor:{}},subscribe(fn){fn(this.state);return()=>{};}};const store=await createProductionDatasource({sdk,db:env.unauthenticatedContext().firestore(),auth,countries,config:{readLimit:60}});assert.equal(store.state.capabilities.marketplaceListings.status,'available');assert.ok(store.state.listings.length);assert.ok(store.state.listings.every(l=>l.status==='active'));store.dispose();});
 await check('actual adapter owner query includes own hidden listings and requests',async()=>{const auth={state:{actor:{uid:'seller',status:'active',ready:true,role:null,permissions:[]},profile:{status:'active'}},subscribe(fn){fn(this.state);return()=>{};}};const store=await createProductionDatasource({sdk,db,auth,countries});await store.loadOwn();assert.equal(store.state.capabilities.marketplaceListings.status,'available');assert.equal(store.state.capabilities.marketplaceRequests.status,'available');assert.ok(store.state.listings.some(l=>l.id===a.id&&l.status==='hidden'));assert.ok(store.state.services.some(r=>r.id===request.id));store.dispose();});
 await check('actual adapter super admin queries read new collections',async()=>{const auth={state:{actor:{uid:'boss',status:'active',ready:true,role:'super_admin',permissions:[]}},subscribe(fn){fn(this.state);return()=>{};}};const store=await createProductionDatasource({sdk,db:adminDb,auth,countries});await store.loadAdmin();for(const key of ['users','marketplaceListings','marketplaceRequests','marketplaceAuditLogs','adminAccess'])assert.notEqual(store.state.capabilities[key]?.status,'denied',key);assert.ok(store.state.audit.length);assert.ok(store.state.services.some(r=>r.type==='featured'));store.dispose();});

 await check('actual adapter assistant loads only delegated administrative data',async()=>{const auth={state:{actor:{uid:'assistant',status:'active',ready:true,role:'admin_assistant',permissions:['listings_view','reports_view']}},subscribe(fn){fn(this.state);return()=>{};}};const store=await createProductionDatasource({sdk,db:env.authenticatedContext('assistant').firestore(),auth,countries});await store.loadAdmin();assert.equal(store.state.capabilities.marketplaceRequests.status,'available');assert.ok(store.state.reports.length);assert.equal(store.state.services.length,0);assert.equal(store.state.audit.length,0);assert.equal(store.state.capabilities.users,undefined);store.dispose();});

 // Direct SDK batches bypass client reasonText(): the Rules must enforce every audit boundary.
 const reasonCases=[['empty','',false],['spaces','   ',false],['tab','\t',false],['newline','\n',false],['mixed-whitespace',' \t\r\n ',false],['unicode-spaces','\u00a0\u2003\u3000',false],['padded-arabic','  سبب صالح  ',true],['arabic','سبب صالح',true],['english','Valid reason',true],['oversized','x'.repeat(501),false]];
 const auditPaths=['approve','reject','hide','featured-approve','featured-reject','commercial-approve','commercial-reject','report-resolve','category-update'];
 for(const path of auditPaths)for(const [name,reason,allowed]of reasonCases){
  await check('direct audit reason '+path+' / '+name,async()=>{
   const id='reason-'+path+'-'+name,listingId=id+'-listing',requestId=id+'-request',now=Date.now();
   await env.withSecurityRulesDisabled(async c=>{const d=c.firestore(),batch=sdk.writeBatch(d);batch.set(sdk.doc(d,'marketplaceListings',listingId),{...draft,schemaVersion:1,ownerUid:'seller',currency:'AED',status:path==='approve'?'hidden':'active',hiddenBy:path==='approve'?'admin':'',moderationLocked:path==='approve',hasHistory:false,createdAt:sdk.serverTimestamp(),updatedAt:sdk.serverTimestamp()});
    if(path.startsWith('featured-'))batch.set(sdk.doc(d,'marketplaceRequests',requestId),{type:'featured',ownerUid:'seller',listingId,status:'pending',reason:'',featuredDurationDays:7,featuredStartAt:now,featuredEndAt:now+7*86400000,createdAt:sdk.serverTimestamp()});
    if(path.startsWith('commercial-'))batch.set(sdk.doc(d,'marketplaceRequests',requestId),{type:'commercial',ownerUid:'seller',status:'pending',createdAt:sdk.serverTimestamp(),data:{title:'Campaign',advertiserName:'Store',description:'Reason test',cta:'Visit',image:draft.images[0],targetUrl:'https://example.org/store',countryTarget:'AE',placement:'hero',startAt:now,endAt:now+86400000,priority:1}});
    if(path==='report-resolve')batch.set(sdk.doc(d,'marketplaceRequests',requestId),{type:'report',ownerUid:'seller',targetType:'user',targetUid:'other',reason:'Original report reason',status:'open',createdAt:sdk.serverTimestamp()});
    if(path==='category-update')batch.set(sdk.doc(d,'marketplaceCategories','cars'),{enabled:true,order:0,featured:false,icon:'car'});
    await batch.commit();
   });
   const batch=sdk.writeBatch(adminDb),logs=[];
   const audited=(collection,target,patch,action,result)=>{const auditId=id+'-audit-'+logs.length;logs.push(auditId);batch.update(sdk.doc(adminDb,collection,target),{...patch,auditId,updatedAt:sdk.serverTimestamp()});batch.set(sdk.doc(adminDb,'marketplaceAuditLogs',auditId),{actorUid:'boss',action,targetId:target,targetCollection:collection,reason,timestamp:sdk.serverTimestamp(),result});};
   if(['approve','reject','hide'].includes(path)){const status={approve:'active',reject:'rejected',hide:'hidden'}[path];audited('marketplaceListings',listingId,{status,hiddenBy:status==='hidden'?'admin':'',moderationLocked:status!=='active',hasHistory:true},'moderate-'+status,status);}
   if(path==='featured-approve'){audited('marketplaceListings',listingId,{featured:true,featuredStatus:'approved',featuredDurationDays:7,featuredStartAt:now,featuredEndAt:now+7*86400000,featuredRequestId:requestId,hasHistory:true},'featured-approved','approved');audited('marketplaceRequests',requestId,{status:'approved'},'service-approved','approved');}
   if(path==='featured-reject')audited('marketplaceRequests',requestId,{status:'rejected'},'service-rejected','rejected');
   if(path.startsWith('commercial-')){const status=path.endsWith('approve')?'approved':'rejected';audited('marketplaceRequests',requestId,{status},'commercial-'+status,status);if(status==='approved'){const data=(await sdk.getDoc(sdk.doc(adminDb,'marketplaceRequests',requestId))).data().data;const {image,...metadata}=data;batch.set(sdk.doc(adminDb,'marketplaceCommercialAds',requestId),{...metadata,ownerUid:'seller',requestId,status,auditId:logs[0],updatedAt:sdk.serverTimestamp()});batch.set(sdk.doc(adminDb,'marketplaceCommercialImages',requestId),{imageData:image,updatedAt:sdk.serverTimestamp()});}}
   if(path==='report-resolve')audited('marketplaceRequests',requestId,{status:'resolved'},'report-resolved','resolved');
   if(path==='category-update')audited('marketplaceCategories','cars',{enabled:false,order:1,featured:false,icon:'car'},'category-update','updated');
   if(allowed){await assertSucceeds(batch.commit());for(const log of logs)assert.equal((await sdk.getDoc(sdk.doc(adminDb,'marketplaceAuditLogs',log))).data().reason,reason,'Rules validate without silently rewriting supplied reason');}
   else {await assertFails(batch.commit());await env.withSecurityRulesDisabled(async c=>{for(const log of logs)assert.equal((await sdk.getDoc(sdk.doc(c.firestore(),'marketplaceAuditLogs',log))).exists(),false,'Rejected batch must not leave audit records');});}
  });
 }
 for(const [name,reason]of reasonCases)await check('user suspension stays unavailable / '+name,async()=>{const batch=sdk.writeBatch(adminDb);batch.update(sdk.doc(adminDb,'users','seller'),{status:'suspended'});batch.set(sdk.doc(adminDb,'marketplaceAuditLogs','suspend-'+name),{actorUid:'boss',action:'suspend',targetCollection:'users',targetId:'seller',reason,timestamp:sdk.serverTimestamp(),result:'suspended'});await assertFails(batch.commit());});
 await check('bump approval preserves creation time and is audited',async()=>{const l=await seller.create(draft),before=(await sdk.getDoc(ref(l.id))).data();const r=await seller.requestService(l.id,'bump');await boss.approveService(r.id,'رفع الإعلان للأعلى');const after=(await sdk.getDoc(ref(l.id))).data();assert.equal(after.createdAt.toMillis(),before.createdAt.toMillis());assert.ok(after.bumpedAt.toMillis()>=before.createdAt.toMillis());await assertFails(sdk.updateDoc(ref(l.id),{bumpedAt:sdk.serverTimestamp(),updatedAt:sdk.serverTimestamp()}));});
 console.log(`SUMMARY ${passed} checks passed`);
}finally{await env.cleanup();}
