const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const out=process.env.MELKAK_QA||path.join(require('os').tmpdir(),'melkak-phase1');fs.mkdirSync(out,{recursive:true});let count=0;function pass(s){count++;console.log('PASS | '+s);}const url='http://127.0.0.1:8786/';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage(),errors=[],consoleErrors=[],network=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('request',r=>network.push(r.url()));const go=async hash=>{await page.goto(url+'#/'+hash);await page.waitForFunction(()=>!!window.__melkak);await page.evaluate(()=>document.fonts.ready);};const nav=async hash=>{await page.evaluate(h=>location.hash='#/'+h,hash);await page.waitForTimeout(70);};
const snapshot=async options=>{await page.waitForFunction(()=>!document.querySelector('#toast').textContent);await page.screenshot(options);};
await page.setViewportSize({width:1440,height:1000});await go('home');assert.match(await page.title(),/مِلكك/);assert.equal(await page.locator('.categories .category').count(),10);pass('MELKAK homepage, clean replaceable logo and 10 categories');
for(const width of [360,390,430,768,1024,1280,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('html').getAttribute('dir'),'rtl');const missing=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.hasAttribute('alt')).length);assert.equal(missing,0);if([390,1440].includes(width))await snapshot({path:path.join(out,'home-'+width+'.png'),fullPage:true});pass('home responsive RTL, no overflow, alt text '+width);}
assert.equal(await page.getByRole('button',{name:'شراء الآن',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'طلب شراء',exact:true}).count(),0);assert.equal(await page.getByRole('link',{name:'الرسائل',exact:true}).count(),0);assert.equal(await page.getByRole('link',{name:'المزادات',exact:true}).count(),0);pass('purchase, messaging, auctions absent from new UX');
await page.getByRole('button',{name:'English',exact:true}).click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.match(await page.locator('h1').innerText(),/MELKAK/);for(const width of [390,1440]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.getByRole('button',{name:'العربية',exact:true}).click();pass('English LTR preserved on mobile and desktop');
await page.locator('.language').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('.language').evaluate(e=>getComputedStyle(e).outlineStyle),'solid');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'الإشعارات');pass('keyboard order and visible focus');
for(const [id,currency]of Object.entries({AE:'AED',SA:'SAR',EG:'EGP',OM:'OMR',JO:'JOD',MA:'MAD'})){await page.locator('.top-location [data-country]').selectOption(id);assert.equal(await page.locator('.listing').first().locator('.price small').innerText(),currency);assert.ok(await page.locator('.top-location [data-city] option').count()>1);pass('country selector, cities and listing currency '+id);}
await page.locator('.top-location [data-country]').selectOption('AE');await page.locator('.top-location [data-city]').selectOption('الذيد');assert.ok(await page.locator('.listing').count()>0);pass('current UAE city selection');await page.locator('.top-location [data-city]').selectOption('');
for(const category of ['livestock','cars','phones','computers','appliances','furniture','tools','sports','children','other']){await nav('market/'+category);assert.ok(await page.locator('h1').innerText());if(category!=='children')assert.ok(await page.locator('.listing').count()>0);if(['livestock','cars'].includes(category))await snapshot({path:path.join(out,category+'.png'),fullPage:true});pass('category page '+category);}
await nav('categories');await snapshot({path:path.join(out,'categories.png'),fullPage:true});assert.equal(await page.locator('.category-grid-large .category').count(),10);pass('category grid navigation');
await nav('market/cars');await page.locator('[name="attr:brand"]').fill('تويوتا');await page.getByRole('button',{name:'تطبيق الفلاتر',exact:true}).click();assert.equal(await page.locator('.listing').count(),1);await page.getByRole('button',{name:'مسح الفلاتر',exact:true}).click();pass('category brand filter and reset');
await page.locator('#search-form input').fill('iPhone');await page.locator('#search-form [name=category]').selectOption('');await page.locator('#search-form button[type=submit]').click();assert.match(await page.locator('.listing h3').first().innerText(),/iPhone/);pass('bounded client search');await page.getByRole('button',{name:'مسح الفلاتر',exact:true}).click();
await nav('home');const favoriteId=await page.locator('.listing').first().getAttribute('data-listing');await page.locator('.listing .favorite').first().click();await nav('favorites');assert.equal(await page.locator('.listing').first().getAttribute('data-listing'),favoriteId);pass('favorites tab stores chosen listing per local user');
await nav('home');await page.evaluate(()=>{window.__melkak.store.state.ads.filter(a=>a.placement==='hero').forEach(a=>a.status='active');window.__melkak.render();});for(let i=0;i<9;i++)await page.getByRole('button',{name:'الإعلان التالي',exact:true}).click();assert.match(await page.locator('.hero-controls').innerText(),/10 \/ 10/);assert.equal(await page.locator('.hero-art').count(),1);assert.equal(await page.locator('.side-ads .small-ad').count(),3);assert.equal(await page.locator('.footer-ads .small-ad').count(),1);pass('Hero 1–10 with one hero image mounted; side/middle/footer retained');
await nav('listing/AE-cars');assert.match(await page.locator('[data-contact="call"]').getAttribute('href'),/^tel:\+/);assert.match(await page.locator('[data-contact="whatsapp"]').getAttribute('href'),/^https:\/\/wa.me\//);await page.locator('[data-contact="call"]').click();assert.match(await page.locator('#toast').innerText(),/تجريبي/);pass('call and WhatsApp URI contracts; demo call cannot trigger a real call');
await nav('listing/legacy-sample');assert.equal(await page.locator('.detail-info [data-contact]').count(),0);assert.ok(!(await page.locator('#main').innerText()).includes('+971512345678'));pass('legacy seller phone remains private without consent');
await nav('add');await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'التالي',exact:true}).click();await page.locator('[name="category"]').selectOption('cars');await page.getByRole('button',{name:'التالي',exact:true}).click();
const files=await page.evaluate(async()=>{const img=new Image();img.src='./melkak/assets/cars.svg';await img.decode();return Array.from({length:4},(_,i)=>{const c=document.createElement('canvas');c.width=1600;c.height=1000;const ctx=c.getContext('2d');ctx.fillStyle=['#eef4ec','#eee8dd','#e0e9ef','#e3dedf'][i];ctx.fillRect(0,0,1600,1000);ctx.drawImage(img,100+i*20,60,1400,900);return c.toDataURL(i===2?'image/webp':i===0?'image/jpeg':'image/png').split(',')[1];});});const upload=(i)=>({name:'car-'+i+(i===2?'.webp':i===0?'.jpg':'.png'),mimeType:i===2?'image/webp':i===0?'image/jpeg':'image/png',buffer:Buffer.from(files[i],'base64')});
await page.locator('#photo-picker').setInputFiles([0,1,2,3].map(upload));await page.waitForTimeout(100);assert.match(await page.locator('.error').innerText(),/3/);assert.equal(await page.evaluate(()=>window.__melkak.state.draft.images.length),0);pass('fourth image blocked before compression');
await page.locator('#photo-picker').setInputFiles([{name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('bad')}]);await page.waitForTimeout(100);assert.match(await page.locator('.error').innerText(),/JPG/);pass('invalid file blocked');
for(const i of [0,1,2]){await page.locator('#photo-picker').setInputFiles(upload(i));await page.waitForFunction(n=>window.__melkak.state.draft.images.length===n&&!window.__melkak.state.busy,i+1);pass((i+1)+' device images with preview and compression');}
assert.ok(await page.evaluate(()=>window.__melkak.state.draft.images.every(x=>x.startsWith('data:image/jpeg;base64,')&&x.length<210000)));await page.locator('[data-action="image-main"]').last().click();await page.locator('[data-action="image-up"]').last().click();assert.equal(await page.locator('.photo-editor img').count(),3);pass('reorder and set main image');
await page.locator('[data-action="image-remove"]').last().click();assert.equal(await page.locator('.photo-editor img').count(),2);await page.locator('#photo-picker').setInputFiles(upload(3));await page.waitForFunction(()=>window.__melkak.state.draft.images.length===3&&!window.__melkak.state.busy);pass('remove and add replacement image');
const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.locator('[data-action="image-replace"]').first().click()]);await chooser.setFiles(upload(0));await page.waitForFunction(()=>!window.__melkak.state.busy&&window.__melkak.state.replaceIndex===null);assert.equal(await page.locator('.photo-editor img').count(),3);pass('device picker replace action retains three photos');
await page.getByRole('button',{name:'التالي',exact:true}).click();await page.locator('[name="title"]').fill('سيارة محلية لمراجعة تصميم مِلكك');await page.locator('textarea[name="description"]').fill('إعلان تجريبي محلي فقط لا يمثل عرض بيع حقيقي، لاختبار المعرض والتواصل المباشر.');await page.locator('[name="price"]').fill('95000');await page.locator('[name="attr:brand"]').fill('تويوتا');await page.locator('[name="attr:model"]').fill('كامري');await page.locator('[name="attr:year"]').fill('2022');await page.getByRole('button',{name:'التالي',exact:true}).click();await page.getByRole('button',{name:'التالي',exact:true}).click();assert.match(await page.locator('.error').innerText(),/وافق/);pass('explicit contact consent required');await page.locator('[name="phone"]').fill('+971500000000');await page.locator('[name="consent"]').check();await page.getByRole('button',{name:'التالي',exact:true}).click();await snapshot({path:path.join(out,'add-listing.png'),fullPage:true});await page.getByRole('button',{name:'نشر الإعلان محليًا',exact:true}).click();await page.waitForFunction(()=>location.hash.includes('/manage/local-'));const id=await page.evaluate(()=>location.hash.split('/').at(-1));pass('seven-step publish creates local listing only');
await snapshot({path:path.join(out,'manage-listing.png'),fullPage:true});await nav('listing/'+id);await snapshot({path:path.join(out,'listing-details.png'),fullPage:true});assert.equal(await page.locator('.thumbs button').count(),2);const before=await page.locator('.detail-stage img').getAttribute('src');await page.locator('.thumbs button').first().click();assert.notEqual(await page.locator('.detail-stage img').getAttribute('src'),before);pass('large main image + two clickable thumbnails and counter');
await nav('my-listings');await snapshot({path:path.join(out,'my-listings.png'),fullPage:true});await nav('manage/'+id);await page.getByRole('button',{name:'إخفاء الإعلان من السوق',exact:true}).click();await page.locator('#dialog button[type="submit"]').click();assert.equal(await page.evaluate(id=>window.__melkak.store.state.listings.find(x=>x.id===id).status,id),'hidden');await nav('listing/'+id);assert.match(await page.locator('#main').innerText(),/غير متاح/);pass('owner hide removes public detail and preserves My Listings');await nav('manage/'+id);await page.getByRole('button',{name:'إعادة نشر الإعلان',exact:true}).click();await page.locator('#dialog button[type="submit"]').click();assert.equal(await page.evaluate(id=>window.__melkak.store.state.listings.find(x=>x.id===id).status,id),'active');pass('owner eligible republish');
await page.locator('[data-action="image-remove"]').last().click();await page.locator('[data-action="image-remove"]').last().click();assert.ok(await page.locator('[data-action="image-remove"]').isDisabled());pass('published listing last image removal disabled');
await nav('listing/'+id);await page.getByRole('button',{name:'الإبلاغ عن الإعلان',exact:true}).click();await page.locator('#dialog textarea').fill('بلاغ محلي لاختبار الصلاحيات');await page.locator('#dialog button[type="submit"]').click();await nav('manage/'+id);assert.equal(await page.getByRole('button',{name:'حذف نهائي',exact:true}).count(),0);pass('report creates retained local history; permanent delete no longer offered');
await page.getByRole('button',{name:'تمييز الإعلان',exact:true}).click();await page.locator('#service-request-form button[type=submit]').click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.services.length),1);pass('listing service request retained with payments disabled');
await nav('account');assert.match(await page.locator('#main').innerText(),/Google Auth/);assert.ok(await page.getByRole('link',{name:'إعلاناتي',exact:true}).count());pass('new account links and preserved Auth boundary');
await page.locator('#preview-role').selectOption('super_admin');await nav('admin');await snapshot({path:path.join(out,'admin-dashboard.png'),fullPage:true});assert.equal(await page.locator('.stat').count(),7);assert.ok(!(await page.locator('.admin-sidebar').innerText()).includes('طلبات الشراء'));pass('seven real-from-fixture dashboard counters; legacy actions excluded');
for(const section of ['users','listings','categories','featured','commercial','reports','assistants','analytics','audit','settings','legacy']){await nav('admin/'+section);assert.ok(await page.locator('.admin-main').count());pass('admin page '+section);}
await nav('admin/categories');const cat=page.locator('[data-category-form="cars"]');await cat.locator('[name="enabled"]').uncheck();await cat.locator('[type="submit"]').click();await nav('categories');assert.equal(await page.locator('.category-grid-large a[href="#/market/cars"]').count(),0);pass('category toggle changes local UX');await nav('admin/categories');await page.locator('[data-category-form="cars"] [name="enabled"]').check();await page.locator('[data-category-form="cars"] [type="submit"]').click();
await page.getByRole('button',{name:'الإشعارات',exact:true}).click();assert.match(await page.locator('#dialog').innerText(),/بلاغ جديد/);await page.getByRole('button',{name:'تعليم الكل كمقروء',exact:true}).click();assert.ok(await page.evaluate(()=>window.__melkak.state.unread.size>=2));pass('permission-filtered local notifications and read state');
await nav('admin/featured');await page.getByRole('button',{name:'اعتماد بدون دفع',exact:true}).click();await page.locator('#dialog textarea').fill('اعتماد استثنائي للمحاكاة');await page.locator('#dialog button[type="submit"]').click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.services[0].status),'approved');pass('Super Admin exceptional local service approval');
await nav('admin/reports');await page.getByRole('button',{name:'تمت المعالجة',exact:true}).click();assert.equal(await page.evaluate(()=>window.__melkak.store.state.reports[0].status),'resolved');pass('Super Admin report resolution');
await page.locator('#preview-role').selectOption('assistant');await nav('admin');assert.equal(await page.locator('.admin-sidebar a[href="#/admin/legacy"]').count(),0);assert.equal(await page.locator('.admin-sidebar a[href="#/admin/categories"]').count(),0);await nav('admin/categories');assert.match(await page.locator('#main').innerText(),/غير متاحة لصلاحيتك/);pass('assistant permission filtering and direct-route denial');
await page.locator('#preview-role').selectOption('user');await nav('admin');assert.match(await page.locator('#main').innerText(),/غير متاحة لصلاحيتك/);pass('normal user admin blocked');
await page.locator('#preview-role').selectOption('super_admin');for(const width of [360,390,430,768,1024,1280,1440]){await page.setViewportSize({width,height:1000});await nav('admin');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await nav('manage/'+id);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('admin/manage responsive '+width);}
await page.setViewportSize({width:390,height:900});await nav('admin');await page.waitForTimeout(3200);await snapshot({path:path.join(out,'admin-mobile.png'),fullPage:true});await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.stat').first().evaluate(e=>getComputedStyle(e).animationName),'none');pass('reduced motion');
await nav('market/livestock');assert.equal(await page.locator('select[name="attr:gender"]').count(),1);await page.locator('.advanced-filters summary').click();await page.locator('select[name="attr:gender"]').selectOption('female');await page.getByRole('button',{name:'تطبيق الفلاتر',exact:true}).click();assert.ok(await page.locator('.listing').count()>0);pass('livestock gender filter');
await nav('account');await page.locator('[data-action="logout"]').click();assert.equal(await page.evaluate(()=>window.__melkak.state.signedIn),false);await nav('admin');assert.match(await page.locator('#main').innerText(),/غير متاحة لصلاحيتك/);await nav('add');assert.equal(await page.locator('#wizard-form').count(),0);await page.locator('[data-action="preview-login"]').click();assert.equal(await page.locator('#wizard-form').count(),1);pass('local logout revokes preview access; local sign-in resumes wizard');
for(const width of [360,390,430,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}pass('wizard responsive widths 360–1440');
const contrast=await page.evaluate(()=>{const rgb=h=>h.match(/[a-f0-9]{2}/gi).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4),lum=h=>rgb(h).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0),ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05),v=getComputedStyle(document.documentElement);return [['--green','#ffffff'],['--muted','#ffffff'],['--ink','#f7f9f7'],['--gold','#fff7e5'],['--red','#ffffff']].map(([a,b])=>ratio(v.getPropertyValue(a).trim(),b));});assert.ok(contrast.every(x=>x>=4.5));assert.equal(await page.locator('input,select,textarea').evaluateAll(es=>es.filter(e=>e.type!=='hidden'&&!e.labels?.length&&!e.getAttribute('aria-label')).length),0);pass('WCAG text color pairs and wizard control accessible names');
assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);assert.ok(network.every(x=>x.startsWith('http://127.0.0.1:8786/')));assert.equal(await page.evaluate(()=>window.__melkak.flags.productionWrites),false);pass('zero JS errors, zero remote requests, Production writes disabled');console.log(`SUMMARY | ${count}/${count} PASS; screenshots ${out}`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
