import fs from 'node:fs';import assert from 'node:assert/strict';import {CATEGORIES,FLAGS,countryConfig} from '../melkak/config.js';import {seed} from '../melkak/fixtures.js';import {normalizeLegacy,phoneNumber,contactLinks,createLocalStore,pageListings,featured,deletionEligibility,validate} from '../melkak/model.js';import {accessModel} from '../admin-permissions.js';import {selectAds} from '../commercial-model.js';
const countries=countryConfig(JSON.parse(fs.readFileSync(new URL('../melkak/legacy-countries.json',import.meta.url),'utf8'))),data=seed(countries),store=createLocalStore(data),user={uid:'demo-owner',name:'Test',role:null,permissions:[]},other={uid:'other',permissions:[]},owner={...user,role:'super_admin'},assistant={uid:'demo-assistant',role:'admin_assistant',permissions:['dashboard_view','listings_view','reports_view']};const img='data:image/jpeg;base64,/9j/AA==';let n=0;function test(name,fn){fn();n++;console.log('PASS | '+name)}const draft=(country='AE',category='livestock')=>{const region=Object.keys(countries[country].regions)[0];return{country,region,city:countries[country].regions[region][0],category,title:'Local listing',description:'Local test description only',price:100,images:[img],attributes:{},contact:{phone:'+'+countries[country].dial+'500000000',call:true,whatsapp:true,showNumber:false,consent:true}};};
for(const [id,currency]of Object.entries({AE:'AED',SA:'SAR',EG:'EGP',OM:'OMR',JO:'JOD',MA:'MAD'}))test('country/currency/region/city '+id,()=>{assert.equal(countries[id].currency,currency);assert.equal(validate(draft(id),countries),true);});
for(const c of CATEGORIES)test('category schema '+c.id,()=>{assert.equal(validate(draft('AE',c.id),countries),true);assert.ok(c.fields.length>=2);});
test('all existing UAE cities retained',()=>{const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');for(const cities of Object.values(countries.AE.regions))for(const city of cities)assert.ok(source.includes('"'+city+'"'));});
for(const count of [1,2,3])test(count+' images accepted',()=>assert.ok(validate({...draft(),images:Array.from({length:count},(_,i)=>'data:image/jpeg;base64,'+Buffer.from('img'+i).toString('base64'))},countries)));
test('fourth image blocked',()=>assert.throws(()=>validate({...draft(),images:['a','b','c','d']},countries)));
test('zero images blocked',()=>assert.throws(()=>validate({...draft(),images:[]},countries)));
test('SVG and external uploads blocked',()=>{for(const image of ['data:image/svg+xml,test','https://evil.test/image.jpg'])assert.throws(()=>validate({...draft(),images:[image]},countries));});
test('oversized inline image blocked',()=>assert.throws(()=>validate({...draft(),images:['data:image/jpeg;base64,'+'A'.repeat(220000)]},countries)));
test('profile phone never copied by legacy adapter',()=>{const a=normalizeLegacy('id',{sellerId:'old',phone:'+971500000000',sellerPhone:'+971500000000',images:[],saleType:'direct'});assert.equal(a.contact,null);assert.equal(a.category,'livestock');assert.deepEqual(contactLinks(a,countries),{});});
test('legacy adapter immutable',()=>{const a={name:'old',images:[img,img,img,img],sellerId:'owner'},old=JSON.stringify(a);normalizeLegacy('id',a);assert.equal(JSON.stringify(a),old);});
test('explicit consent required',()=>assert.throws(()=>validate({...draft(),contact:{...draft().contact,consent:false}},countries)));
test('at least one contact channel required',()=>assert.throws(()=>validate({...draft(),contact:{...draft().contact,call:false,whatsapp:false}},countries)));
test('call and WhatsApp E164 links',()=>{const a=draft(),links=contactLinks(a,countries);assert.equal(links.call,'tel:+971500000000');assert.equal(links.whatsapp,'https://wa.me/971500000000');assert.equal(links.text,null);});
test('explicit text display preference',()=>assert.equal(contactLinks({...draft(),contact:{...draft().contact,showNumber:true}},countries).text,'+971500000000'));
test('invalid contact URI rejected',()=>{assert.equal(phoneNumber('javascript:alert(1)','AE',countries),'');assert.throws(()=>validate({...draft(),contact:{...draft().contact,phone:'123'}},countries));});
test('disabled contact channels absent',()=>assert.equal(contactLinks({...draft(),contact:{...draft().contact,call:false}},countries).call,null));
test('country filter and currency isolated from user country',()=>{const a=pageListings(data.listings,{country:'SA'},countries);assert.ok(a.items.every(x=>x.country==='SA'));assert.equal(countries[a.items[0].country].currency,'SAR');});
test('search title/description/category/city/country',()=>{for(const search of ['تويوتا','تجريبي','السيارات','الذيد','Saudi Arabia'])assert.ok(pageListings(data.listings,{search},countries).total>0);});
test('category filters brand/model/year',()=>{assert.equal(pageListings(data.listings,{country:'AE',category:'cars',attributes:{brand:'تويوتا',model:'لاند',year:'2021'}},countries).total,1);assert.equal(pageListings(data.listings,{category:'cars',attributes:{brand:'not found'}},countries).total,0);});
test('min/max price filter',()=>assert.ok(pageListings(data.listings,{min:2000,max:4000},countries).items.every(a=>a.price>=2000&&a.price<=4000)));
test('bounded pagination',()=>{const p=pageListings(data.listings,{},countries);assert.equal(p.items.length,12);assert.ok(p.hasMore);assert.ok(!pageListings(data.listings,{},countries,2).items.some(a=>p.items.some(b=>a.id===b.id)));});
test('featured active only; future and expired normal',()=>{const a={...draft(),status:'active',featuredStatus:'approved',featuredStartAt:Date.now()-100,featuredEndAt:Date.now()+10000};assert.ok(featured(a));assert.ok(!featured({...a,featuredStartAt:Date.now()+10000}));assert.ok(!featured({...a,featuredEndAt:0}));assert.ok(!featured({...a,featuredStatus:'pending'}));});
test('featured first sorting',()=>{const p=pageListings(data.listings,{country:'AE'},countries);assert.ok(featured(p.items[0]));});
test('legacy auction hidden from public results',()=>assert.ok(pageListings(data.listings,{},countries).items.every(a=>a.saleType!=='auction')));
test('hero max 10, existing selection policy retained',()=>assert.equal(selectAds(data.ads,'hero').length,10));
for(const placement of ['hero_side_1','hero_side_2','hero_side_3','middle','footer_1','footer_5'])test('commercial placement '+placement,()=>assert.equal(selectAds(data.ads,placement).length,1));
const a=store.create(draft(),user);
test('owner create without buyer/seller accountType barrier',()=>assert.equal(a.status,'active'));
test('owner hide retains listing',()=>{store.transition(a.id,'hidden',user);assert.ok(store.state.listings.some(x=>x.id===a.id));assert.equal(pageListings(store.state.listings,{search:'Local listing'},countries).items.length,0);});
test('owner republish eligible',()=>{store.transition(a.id,'active',user);assert.equal(a.status,'active');});
test('owner edit retains protected fields',()=>{store.update(a.id,{title:'Changed locally'},user);assert.throws(()=>store.update(a.id,{ownerUid:'other'},user));});
test('different user edit/delete/hide blocked',()=>{for(const op of [()=>store.update(a.id,{title:'no'},other),()=>store.transition(a.id,'deleted',other),()=>store.transition(a.id,'hidden',other)])assert.throws(op);});
test('clean permanent local deletion removes inline bytes',()=>{store.transition(a.id,'deleted',user);assert.ok(!store.state.listings.some(x=>x.id===a.id));});
const linked=store.create(draft(),user);store.report(linked.id,'report',other);
test('linked listing permanent deletion blocked',()=>{assert.ok(!deletionEligibility(linked,user));assert.throws(()=>store.transition(linked.id,'deleted',user));});
test('legacy permanent deletion blocked',()=>assert.throws(()=>store.transition('legacy-sample','deleted',user)));
test('sold listing stays out of market and cannot republish',()=>{store.transition(linked.id,'sold',user);assert.throws(()=>store.transition(linked.id,'active',user));});
test('schema configuration cannot be edited by admin UI',()=>assert.throws(()=>store.configureCategory('cars',{fields:[]},owner)));
test('category toggle/order/featured/icon Super Admin only',()=>{assert.throws(()=>store.configureCategory('cars',{enabled:false},assistant));store.configureCategory('cars',{enabled:false,order:2,featured:true,icon:'car'},owner);assert.equal(store.state.categories.find(x=>x.id==='cars').enabled,false);});
test('disabled category cannot accept new listings via model',()=>assert.throws(()=>store.create(draft('AE','cars'),user)));
test('legacy read only for actual Super Admin role',()=>{assert.throws(()=>store.legacyRead('auctions',user));assert.throws(()=>store.legacyRead('auctions',assistant));const old=store.legacyRead('auctions',owner);old[0].status='changed';assert.equal(store.state.legacy.auctions[0].status,'preserved');});
test('email cannot grant Super Admin',()=>assert.equal(accessModel('x',{admin:true},{status:'active',email:'owner@test'},null,{enabled:true,superAdminUids:['real-owner']}).role,null));
test('assistant cannot approve services or change owners',()=>assert.throws(()=>store.approveService('unknown','reason',assistant)));
const service=store.create(draft(),user);store.requestService(service.id,'featured',user);
test('existing exceptional service concept remains free and audited locally',()=>{store.approveService(store.state.services[0].id,'Local exception',owner);assert.ok(featured(service));assert.ok(store.state.audit.some(a=>a.action==='exception-approval'));});
test('exceptional no-payment approval cannot be delegated to assistant',()=>assert.throws(()=>store.approveService('unknown','reason',{...assistant,permissions:['services_manage']})));
test('normal user cannot resolve reports',()=>assert.throws(()=>store.resolveReport(store.state.reports[0].id,'reason',user)));
test('Super Admin resolves local report',()=>{store.resolveReport(store.state.reports[0].id,'reviewed',owner);assert.equal(store.state.reports[0].status,'resolved');});
test('dashboard stats derived, never fabricated',()=>{const rows=store.state.listings.filter(a=>a.country==='AE'&&a.saleType!=='auction');assert.equal(store.statistics('AE').total,rows.length);});
test('all Production / legacy action flags disabled',()=>{for(const key of ['productionWrites','payments','analytics','auctions','messaging','purchaseRequests'])assert.equal(FLAGS[key],false);});
console.log(`SUMMARY | ${n}/${n} PASS`);
