const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const evidence=path.join(os.tmpdir(),'melkak-release-admin-ui-'+Date.now());fs.mkdirSync(evidence,{recursive:true});let count=0;const uiFailures=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const origin='https://iso9090.github.io';
 const entry=`import {startMarketplace} from './app.js';import {CATEGORIES,countryConfig} from './config.js';
 const countries=countryConfig(await (await fetch('./melkak/legacy-countries.json')).json());
 const owner={uid:'owner',name:'Real owner',role:'super_admin',status:'active',active:true,ready:true,permissions:[],protectedUids:['owner','protected']};
 const state={listings:[],categories:CATEGORIES.map((c,i)=>({...c,enabled:true,order:i})),users:[{uid:'owner',displayName:'Real owner',email:'owner@example.com',status:'active',country:'AE'},{uid:'protected',displayName:'Protected owner',status:'active',country:'AE'},{uid:'candidate',displayName:'Existing Google user',email:'candidate@example.com',status:'active',country:'AE'},{uid:'member',displayName:'Ordinary member',status:'active',country:'AE'}],legacy:{adminAccess:[]},settings:{enabledCountries:['AE','SA'],supportText:'Support text'},cities:[],ads:[],publicAds:[],services:[],reports:[],audit:[],version:0,capabilities:{}};
 const listeners=new Set();const auth={state:{status:'authenticated',user:{uid:'owner'},actor:owner},subscribe(fn){listeners.add(fn);fn(this.state);return()=>listeners.delete(fn)},emit(a){this.state={status:'authenticated',user:{uid:a.uid},actor:a};for(const fn of listeners)fn(this.state)},async signOut(){}};
 window.calls=[];window.testAuth=auth;window.testState=state;window.ownerActor=owner;
 const log=(name,args)=>window.calls.push({name,args});
 const store={state,subscribe(){return()=>{}},async loadOwn(){},async loadAdmin(){},async refreshPublic(){},async loadAdImages(){},statistics(){return {total:0,active:0,hidden:0,rejected:0,pending:0,archived:0,sold:0,featured:0,soon:0,reports:0,users:4}},async setUserStatus(...args){log('setUserStatus',args);state.users.find(u=>u.uid===args[0]).status=args[1]},async grantAssistant(...args){log('grantAssistant',args);state.legacy.adminAccess.push({id:args[0],role:'admin_assistant',adminStatus:'active',permissions:args[1]})},async updateAssistant(...args){log('updateAssistant',args);Object.assign(state.legacy.adminAccess.find(a=>a.id===args[0]),args[1])},async removeAssistant(...args){log('removeAssistant',args);Object.assign(state.legacy.adminAccess.find(a=>a.id===args[0]),{role:'removed',permissions:[],adminStatus:'suspended'})},async configureSettings(...args){log('configureSettings',args);state.settings=args[0]},async configureCity(...args){log('configureCity',args);state.cities=[{id:args[0],...args[1]}]}};
 await startMarketplace({config:{mode:'production',datasource:'production',authProvider:'firebase',writesEnabled:true},store,auth});`;
 await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!==origin)return route.abort();if(url.pathname==='/melkak/entry.js')return route.fulfill({contentType:'text/javascript',body:entry});const file=path.resolve('.'+url.pathname+(url.pathname==='/'?'index.html':''));if(!file.startsWith(process.cwd()+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(file),contentType:({'.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.webp':'image/webp','.ttf':'font/ttf'})[path.extname(file)]||'application/octet-stream'});});
 await page.goto(origin+'/#/admin/users');await page.waitForSelector('[data-action="admin-user-status"]');
 const navigate=async route=>{await page.evaluate(value=>location.hash=value,'#/admin/'+route);await page.waitForTimeout(60);};
 const last=()=>page.evaluate(()=>window.calls.at(-1));
 const finish=async reason=>{await page.locator('dialog[open] textarea[name=reason]').fill(reason);await page.locator('dialog[open] button[type=submit]').click();await page.waitForTimeout(50);};
 assert.equal(await page.locator('[data-action="admin-user-status"][data-id="owner"],[data-action="admin-user-status"][data-id="protected"]').count(),0);count++;
 await page.locator('[data-action="admin-user-status"][data-id="member"]').click();await page.locator('dialog[open] select[name=status]').selectOption('suspended');await finish('Reviewed member status');assert.deepEqual(await last(),{name:'setUserStatus',args:['member','suspended','Reviewed member status']});count++;
 await navigate('assistants');await page.locator('[data-action="admin-assistant-add"]').click();await page.locator('dialog[open] select[name=uid]').selectOption('candidate');await page.locator('dialog[open] input[value=listings_view]').check();await finish('Grant scoped access');assert.deepEqual(await last(),{name:'grantAssistant',args:['candidate',['listings_view'],'Grant scoped access']});count++;
 await page.locator('[data-action="admin-assistant-edit"][data-id=candidate]').click();await page.locator('dialog[open] input[value=listings_view]').uncheck();await page.locator('dialog[open] input[value=reports_view]').check();await finish('Update scoped access');assert.deepEqual(await last(),{name:'updateAssistant',args:['candidate',{permissions:['reports_view']},'Update scoped access']});count++;
 await page.locator('[data-action="admin-assistant-status"][data-id=candidate]').click();await finish('Suspend assistant');assert.deepEqual(await last(),{name:'updateAssistant',args:['candidate',{adminStatus:'suspended'},'Suspend assistant']});count++;
 await page.locator('[data-action="admin-assistant-status"][data-id=candidate]').click();await finish('Reactivate assistant');assert.equal((await last()).args[1].adminStatus,'active');count++;
 await page.locator('[data-action="admin-assistant-remove"][data-id=candidate]').click();await finish('Remove administrative role');assert.deepEqual(await last(),{name:'removeAssistant',args:['candidate','Remove administrative role']});count++;
 await navigate('settings');await page.locator('#marketplace-settings-form textarea[name=supportText]').fill('Reviewed support text');await page.locator('#marketplace-settings-form textarea[name=reason]').fill('Update support settings');await page.locator('#marketplace-settings-form button[type=submit]').click();await page.waitForTimeout(50);assert.deepEqual(await last(),{name:'configureSettings',args:[{enabledCountries:['AE','SA'],supportText:'Reviewed support text'},'Update support settings']});count++;
 for(const [name,value]of [['id','dubai'],['region','Dubai'],['name','Dubai'],['reason','Add approved city']])await page.locator('#marketplace-city-form [name='+name+']').fill(value);await page.locator('#marketplace-city-form select[name=country]').selectOption('AE');await page.locator('#marketplace-city-form button[type=submit]').click();await page.waitForTimeout(50);try{assert.deepEqual(await last(),{name:'configureCity',args:['dubai',{country:'AE',region:'Dubai',name:'Dubai',enabled:true},'Add approved city']});}catch(error){uiFailures.push('configureCity dispatch: '+error.message);}count++;
 for(const lang of ['ar','en']){
  if(await page.locator('html').getAttribute('lang')!==lang)await page.locator('[data-action=language]').first().click();
  for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:1000});for(const section of ['users','assistants','settings']){await navigate(section);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,lang+' '+width+' '+section);count++;}await page.screenshot({path:path.join(evidence,lang+'-'+width+'.png'),fullPage:true});}
 }
 await page.evaluate(()=>window.testAuth.emit({uid:'helper',name:'Scoped assistant',role:'admin_assistant',status:'active',active:true,ready:true,permissions:['dashboard_view','users_view','users_suspend','assistants_view'],protectedUids:['owner','protected']}));await navigate('users');await page.locator('[data-action="admin-user-status"][data-id=member]').click();assert.deepEqual(await page.locator('dialog[open] select[name=status] option').evaluateAll(nodes=>nodes.map(n=>n.value)),['suspended']);await page.evaluate(()=>document.querySelector('dialog[open]').close());count++;
 await navigate('assistants');assert.equal(await page.locator('[data-action="admin-assistant-add"],[data-action="admin-assistant-edit"],[data-action="admin-assistant-remove"]').count(),0);await navigate('settings');assert.equal(await page.locator('#marketplace-settings-form').count(),0);count++;
 assert.deepEqual(errors,[]);assert.deepEqual(uiFailures,[]);count++;console.log('SUMMARY | '+count+'/'+count+' PASS mock service UI integration; screenshots '+evidence);
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
