const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
const out=process.env.MELKAK_QA||path.join(require('os').tmpdir(),'melkak-final-ui');fs.mkdirSync(out,{recursive:true});let passed=0,failed=0;
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],remote=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});p.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8786/'))remote.push(r.url())});await require('./mock-neutral-moderation.cjs')(p);
await p.goto('http://127.0.0.1:8786/');await p.waitForFunction(()=>window.__melkak);await p.evaluate(()=>document.fonts.ready);
const pristineListings=await p.evaluate(()=>structuredClone(window.__melkak.store.state.listings));
const test=async(name,fn)=>{try{await fn();passed++;console.log('PASS | '+name)}catch(e){failed++;console.error('FAIL | '+name+' | '+e.message)}};
const nav=async route=>{await p.evaluate(r=>location.hash='#/'+r,route);await p.waitForTimeout(100)};
const shot=async name=>{await p.waitForFunction(()=>!document.querySelector('#toast').textContent);await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=550){scrollTo(0,y);await new Promise(r=>setTimeout(r,65))}scrollTo(0,0);document.activeElement?.blur()});await p.waitForTimeout(100);await p.screenshot({path:path.join(out,name),fullPage:true})};
await test('five featured cards occupy balanced desktop section at 5–8% emphasis',async()=>{const a=await p.locator('.featured-section .listing').first().boundingBox(),b=await p.locator('.latest-section .listing').first().boundingBox(),section=await p.locator('.featured-section').boundingBox(),main=await p.locator('.market-main').boundingBox();assert.ok(a.width/b.width>=1.05&&a.width/b.width<=1.08);assert.ok(section.width/main.width>=.65);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)});
await test('demo vehicles phones and livestock differ across countries',async()=>{const rows=await p.evaluate(()=>window.__melkak.store.state.listings.filter(a=>!a.legacy));for(const category of ['cars','phones','livestock']){const selected=rows.filter(a=>a.category===category&&a.id===a.country+'-'+category);assert.equal(new Set(selected.map(a=>a.title)).size,6)}});
await test('local livestock title and attributes agree',async()=>{const a=await p.evaluate(()=>window.__melkak.store.state.listings.find(a=>a.id==='SA-livestock'));assert.equal(a.attributes.gender,'male');assert.equal(a.attributes.age,'4 سنوات')});
await test('details hero is reduced without losing call actions',async()=>{await nav('listing/AE-cars');assert.ok((await p.locator('.detail-stage').boundingBox()).height<=430);for(const kind of ['call','whatsapp'])assert.ok((await p.locator('.detail-info [data-contact='+kind+']').boundingBox()).y<720)});
await test('mobile call and WhatsApp visible before the bottom navigation',async()=>{await p.setViewportSize({width:390,height:900});await nav('listing/AE-cars');const floor=(await p.locator('.bottom-nav').boundingBox()).y;for(const kind of ['call','whatsapp']){const b=await p.locator('.detail-info [data-contact='+kind+']').boundingBox();assert.ok(b.y+b.height<floor)}});
await test('manage listing is compact on mobile and desktop',async()=>{for(const [width,limit]of [[1440,2100],[390,3000]]){await p.setViewportSize({width,height:900});await nav('manage/AE-cars');assert.ok(await p.evaluate(limit=>document.documentElement.scrollHeight<limit,limit),String(width));assert.equal(await p.locator('#manage-form .manage-layout>.panel').count(),6)}});
await test('raw file input replaced by accessible Arabic add action and 1/3 count',async()=>{await nav('manage/AE-cars');assert.equal(await p.locator('#photo-picker').isVisible(),false);assert.equal(await p.getByRole('button',{name:'إضافة صور',exact:true}).count(),1);assert.match(await p.locator('.image-manager-count').innerText(),/1\s*\/\s*3/);assert.equal(await p.locator('[data-action=image-remove]').first().isDisabled(),true)});
if(failed===0){
const uploads=await p.evaluate(()=>[0,1,2,3].map(i=>{const c=document.createElement('canvas');c.width=480;c.height=320;const ctx=c.getContext('2d');ctx.fillStyle=['#4193ae','#c7a05b','#699579','#87779d'][i];ctx.fillRect(0,0,480,320);ctx.fillStyle='#fff';ctx.font='40px sans-serif';ctx.fillText('MELKAK '+(i+1),70,160);return c.toDataURL('image/png').split(',')[1]}));
const upload=i=>({name:'local-demo-'+i+'.png',mimeType:'image/png',buffer:Buffer.from(uploads[i],'base64')});
await nav('add');await p.evaluate(()=>{window.__melkak.state.step=3;window.__melkak.render()});
for(const i of [0,1,2])await test((i+1)+' image(s) via Arabic device picker and compressed preview',async()=>{const [chooser]=await Promise.all([p.waitForEvent('filechooser'),p.getByRole('button',{name:'إضافة صور',exact:true}).click()]);await chooser.setFiles(upload(i));await p.waitForFunction(n=>window.__melkak.state.draft.images.length===n&&!window.__melkak.state.busy,i+1);assert.match(await p.locator('.image-manager-count').innerText(),new RegExp((i+1)+'\\s*/\\s*3'));assert.equal(await p.locator('.photo-editor img').count(),i+1);assert.ok(await p.evaluate(()=>window.__melkak.state.draft.images.every(s=>s.startsWith('data:image/jpeg;base64,')&&s.length<210000)))});
await test('fourth image blocked and add disabled at capacity',async()=>{assert.ok(await p.getByRole('button',{name:'إضافة صور',exact:true}).isDisabled());await p.locator('#photo-picker').setInputFiles(upload(3));await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>window.__melkak.state.draft.images.length),3);assert.match(await p.locator('.error').innerText(),/3/)});
await test('replacement at 3/3 and setting main retain exactly three images',async()=>{const before=await p.evaluate(()=>window.__melkak.state.draft.images[1]);const [chooser]=await Promise.all([p.waitForEvent('filechooser'),p.locator('[data-action=image-replace]').nth(1).click()]);await chooser.setFiles(upload(3));await p.waitForFunction(()=>!window.__melkak.state.busy&&window.__melkak.state.replaceIndex==null);assert.notEqual(await p.evaluate(()=>window.__melkak.state.draft.images[1]),before);const replacement=await p.evaluate(()=>window.__melkak.state.draft.images[1]);await p.locator('[data-action=image-main]').nth(1).click();assert.equal(await p.evaluate(()=>window.__melkak.state.draft.images[0]),replacement);assert.equal(await p.locator('.photo-editor img').count(),3)});
await test('remove re-enables add and last published image stays protected',async()=>{await p.locator('[data-action=image-remove]').last().click();assert.ok(await p.getByRole('button',{name:'إضافة صور',exact:true}).isEnabled());await p.evaluate(()=>{const w=window.__melkak;w.store.state.listings.find(a=>a.id==='AE-cars').images=[w.state.draft.images[0]]});await nav('manage/AE-cars');assert.ok(await p.locator('[data-action=image-remove]').first().isDisabled());await p.evaluate(()=>{const el=document.querySelector('[data-action=image-remove]');el.disabled=false;el.click()});assert.equal(await p.evaluate(()=>window.__melkak.state.draft.images.length),1);assert.equal(await p.evaluate(()=>window.__melkak.store.state.listings.find(a=>a.id==='AE-cars').images.length),1)});
await test('delete remains outline and no primary class',async()=>{const b=p.locator('[data-next=deleted]');assert.equal(await b.count(),1);assert.ok(!(await b.getAttribute('class')).includes('primary'));const s=await b.evaluate(e=>{const s=getComputedStyle(e);return {color:s.color,bg:s.backgroundColor,border:s.borderTopColor}});assert.notEqual(s.bg,s.color);assert.notEqual(s.bg,s.border)});
for(const [country,currency]of Object.entries({AE:'AED',SA:'SAR',EG:'EGP',OM:'OMR',JO:'JOD',MA:'MAD'}))await test('currency '+currency+' follows listing country despite selected market',async()=>{await p.evaluate(()=>window.__melkak.state.country='AE');await nav('listing/'+country+'-cars');assert.match(await p.locator('.detail-info .price').innerText(),new RegExp(currency))});
await test('direct call and WhatsApp actions remain demo-safe',async()=>{await nav('listing/AE-cars');for(const kind of ['call','whatsapp']){await p.locator('.detail-info [data-contact='+kind+']').click();assert.match(await p.locator('#toast').innerText(),/تجريبي/)}});
await test('commercial labels and legacy UX exclusion',async()=>{await nav('home');assert.ok((await p.locator('.promo-block .tag').allTextContents()).every(x=>x==='إعلان ترويجي'));for(const route of ['home','listing/AE-cars','manage/AE-cars','my-listings']){await nav(route);assert.doesNotMatch(await p.locator('#main').innerText(),/مزادات|مزايدة|مزايداتي|طلبات شراء|شراء الآن|رسائل داخلية|مراسلة البائع/)}});
for(const width of [360,390,430,768,1024,1440])await test('responsive '+width+' including image manager and admin',async()=>{await p.setViewportSize({width,height:900});for(const route of ['home','listing/AE-cars','manage/AE-cars','admin']){if(route==='admin')await p.locator('#preview-role').selectOption('super_admin');await nav(route);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route)}});
await test('RTL LTR keyboard focus and image control accessible names',async()=>{await p.setViewportSize({width:390,height:900});await nav('manage/AE-cars');await p.getByRole('button',{name:'إضافة صور',exact:true}).focus();assert.ok(await p.getByRole('button',{name:'إضافة صور',exact:true}).evaluate(e=>e===document.activeElement));await p.locator('[data-action=language]').click();assert.equal(await p.locator('html').getAttribute('dir'),'ltr');assert.equal(await p.getByRole('button',{name:'Add photos',exact:true}).count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('[data-action=language]').click();assert.equal(await p.locator('html').getAttribute('dir'),'rtl')});
await p.evaluate(rows=>{window.__melkak.store.state.listings=rows;window.__melkak.state.editing=null},pristineListings);await p.setViewportSize({width:1440,height:900});await p.locator('#preview-role').selectOption('user');await nav('home');await shot('home-1440-final.png');await p.setViewportSize({width:390,height:900});await shot('home-390-final.png');await p.setViewportSize({width:1440,height:900});await nav('listing/AE-cars');await shot('listing-details-final.png');await nav('manage/AE-cars');await shot('manage-listing-final.png');await p.locator('#preview-role').selectOption('super_admin');await nav('admin');await shot('admin-home-final.png');
await test('no critical JavaScript errors or remote requests; disabled flags',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.equal(await p.evaluate(()=>window.__melkak.flags.productionWrites||window.__melkak.flags.analytics||window.__melkak.flags.payments),false)});
}
console.log('SUMMARY | '+passed+'/'+(passed+failed)+' PASS; failures='+failed);if(failed)process.exitCode=1;
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
