import test from 'node:test';
import assert from 'node:assert/strict';
import {createProductionDatasource} from '../melkak/production-datasource.js';
const jpeg='data:image/jpeg;base64,YQ==',now=Date.now();
function harness(actor={}) {
 const calls=[],data={marketplaceListings:Array.from({length:5},(_,i)=>({id:'l'+i,status:'active',ownerUid:'seller',country:i===4?'SA':'AE',category:'cars',updatedAt:100-i,createdAt:1})),marketplaceSettings:[{id:'public',siteName:'MELKAK'}],marketplaceCities:[{id:'city',country:'AE',name:'Dubai',enabled:true}],marketplaceCommercialAds:[{id:'ad',status:'approved',startAt:now-60000,endAt:now+60000,title:'Public'},{id:'future',status:'approved',startAt:now+60000,endAt:now+120000}],marketplaceRequests:[{id:'ad',type:'commercial',ownerUid:'seller',status:'approved',data:{image:jpeg,title:'Private',startAt:now-60000,endAt:now+60000}}],marketplaceCommercialImages:[{id:'ad',imageData:jpeg}]};
 let listener;const auth={state:{actor},subscribe(fn){listener=fn;fn();return()=>{};},set(value){this.state.actor=value;listener();}};
 const matches=(row,[key,op,value])=>op==='=='?row[key]===value:op==='in'?value.includes(row[key]):op==='>'?row[key]>value:op==='>='?row[key]>=value:op==='<'?row[key]<value:op==='<='?row[key]<=value:true;
 const evaluate=q=>{let rows=[...(data[q.name]||[])];for(const f of q.filters||[])if(f.where)rows=rows.filter(row=>matches(row,f.where));for(const f of q.filters||[])if(f.orderBy)rows.sort((a,b)=>(f.orderBy[1]==='desc'?-1:1)*(a[f.orderBy[0]]-b[f.orderBy[0]]));const cursor=q.filters?.find(f=>f.startAfter)?.startAfter;if(cursor)rows=rows.slice(rows.findIndex(row=>row.id===cursor.id)+1);const max=q.filters?.find(f=>f.limit)?.limit;if(max)rows=rows.slice(0,max);return rows;};
 const sdk={collection:(_,name)=>({name}),doc:(_,name,id)=>({name,id}),query:(ref,...filters)=>({...ref,filters}),where:(...where)=>({where}),orderBy:(...orderBy)=>({orderBy}),startAfter:startAfter=>({startAfter}),limit:limit=>({limit}),getDocs:async q=>{calls.push(q);return {docs:evaluate(q).map(row=>({id:row.id,data:()=>row}))};},getDoc:async ref=>{calls.push(ref);const row=data[ref.name]?.find(row=>row.id===ref.id);return {exists:()=>!!row,data:()=>row};},getCountFromServer:async q=>{calls.push({...q,count:true});return {data:()=>({count:evaluate(q).length})};}};
 return {sdk,db:{},auth,countries:{AE:{currency:'AED'},SA:{currency:'SAR'}},config:{modernCommercial:true,includeLegacy:false,readLimit:2},calls,data};
}
test('release config reads settings/cities without legacy access and paginates filtered listings',async()=>{const h=harness(),store=await createProductionDatasource(h);assert.equal(store.state.settings.siteName,'MELKAK');assert.equal(store.state.cities.length,1);assert.equal(store.state.listings.length,2);assert.equal(store.state.publicPage.hasMore,true);await store.loadMorePublic();assert.equal(store.state.listings.length,4);assert.ok(h.calls.some(q=>q.filters?.some(f=>f.startAfter)));await store.refreshPublic({country:'SA',category:'cars'});assert.deepEqual(store.state.listings.map(row=>row.sourceId),['l4']);assert.equal(store.state.publicPage.hasMore,false);assert.ok(!h.calls.some(q=>['animals','commercialAds','serviceRequests'].includes(q.name)));assert.ok(h.calls.filter(q=>q.filters).every(q=>q.filters.some(f=>f.limit<=100)));store.dispose();});
test('admin merge preserves private artwork and fetched artwork across refreshes; public never fetches future images',async()=>{const h=harness(),store=await createProductionDatasource(h);await store.loadAdImages(['future']);assert.ok(!h.calls.some(q=>q.name==='marketplaceCommercialImages'));h.auth.set({uid:'boss',role:'super_admin',ready:true,status:'active'});await store.loadAdmin();assert.equal(store.state.ads.find(row=>row.id==='ad').asset,jpeg);await store.loadAdImages(['ad']);await store.refreshPublic();await store.loadAdmin();assert.equal(store.state.ads.find(row=>row.id==='ad').imageData,jpeg);assert.equal(store.state.ads.find(row=>row.id==='ad').publicEligible,true);store.dispose();});
test('counts query only allowed collections, expose exact fields and never turn failures into totals',async()=>{const h=harness({uid:'boss',role:'super_admin',ready:true,status:'active'}),store=await createProductionDatasource(h);const counts=await store.loadCounts('AE');assert.equal(counts.total,4);assert.equal(store.statistics('AE').total,4);assert.equal(store.statistics('AE').exactFields.includes('total'),true);assert.equal(store.statistics('AE').bounded,true,'country reports require bounded join');assert.ok(h.calls.filter(q=>q.count).every(q=>!q.filters.some(f=>f.limit)));h.sdk.getCountFromServer=async()=>{throw Object.assign(Error('denied'),{code:'permission-denied'});};await store.loadCounts('AE');assert.equal(store.statistics('AE').exactFields.includes('total'),false);assert.equal(store.state.counts.AE.status,'partial');h.auth.set({uid:'assistant',role:'admin_assistant',ready:true,status:'active',permissions:['reports_view']});h.calls.length=0;await store.loadCounts();assert.ok(!h.calls.some(q=>q.count&&['users','marketplaceListings'].includes(q.name)));store.dispose();});
test('enabled admin cities enter shared validation config; disabling custom entries restores baseline only',async()=>{const h=harness();h.countries.AE={currency:'AED',dial:'971',regions:{Dubai:['Base city']}};h.data.marketplaceCities=[{id:'custom',country:'AE',region:'Dubai',name:'New city',enabled:true},{id:'base',country:'AE',region:'Dubai',name:'Base city',enabled:false}];const store=await createProductionDatasource(h);assert.deepEqual(h.countries.AE.regions.Dubai,['Base city','New city']);h.data.marketplaceCities[0].enabled=false;await store.refreshPublic();assert.deepEqual(h.countries.AE.regions.Dubai,['Base city']);assert.equal(h.countries.AE.currency,'AED');assert.equal(h.countries.AE.dial,'971');store.dispose();});
test('single deep links retrieve beyond-page records without querying all or exposing hidden outsiders',async()=>{const h=harness(),store=await createProductionDatasource(h);assert.equal(store.state.listings.some(a=>a.id==='marketplace-l4'),false);const row=await store.loadListing('marketplace-l4');assert.equal(row.id,'marketplace-l4');assert.ok(store.state.listings.some(a=>a.id===row.id));h.data.marketplaceListings.push({id:'hidden',status:'hidden',ownerUid:'other',country:'AE'});assert.equal(await store.loadListing('marketplace-hidden'),null);const count=h.calls.length;assert.equal(await store.loadListing('legacy-no'),null);assert.equal(await store.loadListing('../unsafe'),null);assert.equal(h.calls.length,count);store.dispose();});
test('own and permission scoped admin pages append unique rows and clear private pages on signout',async()=>{const h=harness({uid:'seller',status:'active'});h.data.marketplaceListings=h.data.marketplaceListings.map(a=>({...a,status:'hidden'}));const store=await createProductionDatasource(h);await store.loadOwn();assert.equal(store.state.listings.length,2);assert.equal(store.state.ownPages.listings.hasMore,true);await store.loadMoreOwn();assert.equal(store.state.listings.length,4);assert.ok(h.calls.filter(q=>q.name==='marketplaceListings'&&q.filters?.some(f=>f.startAfter)).every(q=>q.filters.some(f=>f.where?.[0]==='ownerUid')));h.auth.set({uid:'boss',role:'super_admin',ready:true,status:'active'});await store.loadAdmin();assert.equal(store.state.adminPages.listings.hasMore,true);await store.loadMoreAdmin('listings');assert.equal(store.state.listings.length,4);h.auth.set({uid:'assistant',role:'admin_assistant',ready:true,status:'active',permissions:['reports_view']});const count=h.calls.length;await store.loadMoreAdmin('listings');assert.equal(h.calls.length,count);assert.equal(store.state.listings.length,0);assert.deepEqual(store.state.adminPages,{});store.dispose();});
test('mutation refresh updates previously requested real count countries',async()=>{const h=harness({uid:'boss',role:'super_admin',ready:true,status:'active'}),store=await createProductionDatasource(h);await store.loadCounts('AE');assert.equal(store.statistics('AE').total,4);h.data.marketplaceListings.push({id:'new',status:'active',ownerUid:'seller',country:'AE',category:'cars',updatedAt:200});await store.refresh();assert.equal(store.statistics('AE').total,5);assert.ok(store.statistics('AE').exactFields.includes('total'));store.dispose();});
test('deep link results completing after signout cannot restore private records',async()=>{const h=harness({uid:'seller',status:'active'}),store=await createProductionDatasource(h);let resolve;h.sdk.getDoc=()=>new Promise(done=>resolve=done);const pending=store.loadListing('marketplace-private');h.auth.set({});resolve({exists:()=>true,data:()=>({ownerUid:'seller',status:'hidden',country:'AE'})});assert.equal(await pending,null);assert.equal(store.state.listings.some(row=>row.id==='marketplace-private'),false);store.dispose();});
test('campaign metadata revision invalidates cached artwork and refreshes replacement without stale overwrite',async()=>{const h=harness({uid:'boss',role:'super_admin',ready:true,status:'active'});h.data.marketplaceCommercialAds[0].updatedAt=1;const store=await createProductionDatasource(h);await store.loadAdmin();await store.loadAdImages(['ad']);assert.equal(store.state.ads.find(a=>a.id==='ad').asset,jpeg);const replacement='data:image/jpeg;base64,Yg==';h.data.marketplaceCommercialAds[0].updatedAt=2;h.data.marketplaceCommercialImages[0].imageData=replacement;h.data.marketplaceRequests[0].data.image=replacement;await store.refreshPublic();await store.loadAdmin();await store.loadAdImages(['ad']);assert.equal(store.state.publicAds.find(a=>a.id==='ad').asset,replacement);assert.equal(store.state.ads.find(a=>a.id==='ad').asset,replacement);assert.equal(h.calls.filter(q=>q.name==='marketplaceCommercialImages').length,2);store.dispose();});
test('new public metadata cannot fall back to old admin request artwork while awaiting image reload',async()=>{const h=harness({uid:'boss',role:'super_admin',ready:true,status:'active'});h.data.marketplaceCommercialAds[0].updatedAt=1;h.data.marketplaceRequests[0].updatedAt=1;const store=await createProductionDatasource(h);await store.loadAdmin();await store.loadAdImages(['ad']);h.data.marketplaceCommercialAds[0].updatedAt=2;await store.refreshPublic();assert.equal(store.state.ads.find(a=>a.id==='ad').asset,'');assert.equal(store.state.ads.find(a=>a.id==='ad').updatedAt,2);store.dispose();});
test('active featured records older than normal page are included while expired and other country promotions are excluded',async()=>{const h=harness(),promoted={status:'active',ownerUid:'seller',category:'cars',country:'AE',updatedAt:0,createdAt:0,featured:true,featuredStatus:'approved',featuredStartAt:now-60000,featuredEndAt:now+60000};h.data.marketplaceListings.push({...promoted,id:'old-featured'},{...promoted,id:'expired-featured',featuredEndAt:now-1000},{...promoted,id:'foreign-featured',country:'SA'});const store=await createProductionDatasource(h);await store.refreshPublic({country:'AE',category:'cars'});assert.ok(store.state.listings.some(row=>row.sourceId==='old-featured'));assert.equal(store.state.listings.some(row=>['expired-featured','foreign-featured'].includes(row.sourceId)),false);const q=h.calls.find(q=>q.name==='marketplaceListings'&&q.filters?.some(f=>f.where?.[0]==='featured'));assert.ok(q.filters.some(f=>f.limit<=20));assert.equal(q.filters.some(f=>f.where?.[0]==='category'),false);await store.loadMorePublic();assert.equal(store.state.listings.filter(row=>row.sourceId==='old-featured').length,1);store.dispose();});
