import assert from 'node:assert/strict';
import {attachProductionSettings,createSettingsView} from '../melkak/production-settings.js';
function setup(overrides={}){const records=new Map(),writes=[];const actor={uid:'owner',role:'super_admin',status:'active',ready:true,...overrides};let n=0;const sdk={doc:(base,name,id)=>id?{id,path:name+'/'+id}:{id:String(++n),path:base.path+'/'+n},collection:(_,path)=>({path}),serverTimestamp:()=>123,runTransaction:async(_,fn)=>{const staged=[];await fn({get:async ref=>({exists:()=>records.has(ref.path),data:()=>records.get(ref.path)}),set:(ref,data)=>staged.push([ref.path,data])});for(const row of staged){records.set(...row);writes.push(row);}}};const store={state:{settings:{},cities:[]},refresh:async()=>{}};attachProductionSettings(store,{sdk,db:{},auth:{state:{actor}},config:{writesEnabled:true}});return {store,records,writes,actor};}
const f=setup();await f.store.configureSettings({enabledCountries:['AE','SA'],supportText:'Hello'},'valid reason');assert.deepEqual(f.records.get('marketplaceSettings/public'),{enabledCountries:['AE','SA'],supportText:'Hello',auditId:'1',updatedAt:123});assert.equal(f.records.get('marketplaceAuditLogs/1').action,'settings-update');
await f.store.configureCity('dubai',{country:'AE',region:'Dubai',name:'Dubai',enabled:true},'valid reason');assert.equal(f.records.get('marketplaceCities/dubai').name,'Dubai');assert.equal(f.records.get('marketplaceAuditLogs/2').targetCollection,'marketplaceCities');
for(const enabledCountries of [[],['US'],['AE','AE']])await assert.rejects(()=>f.store.configureSettings({enabledCountries,supportText:''},'reason'),{code:'FIELDS'});
await assert.rejects(()=>f.store.configureSettings({enabledCountries:['AE'],supportText:'',analyticsEnabled:true},'reason'),{code:'FIELDS'});
await assert.rejects(()=>f.store.configureCity('../bad',{country:'AE',region:'x',name:'x',enabled:true},'reason'),{code:'FIELDS'});
await assert.rejects(()=>f.store.configureCity('city',{country:'AE',region:'x',name:'x',enabled:'true'},'reason'),{code:'FIELDS'});
await assert.rejects(()=>setup({role:'admin_assistant'}).store.configureSettings({enabledCountries:['AE'],supportText:''},'reason'),{code:'PERMISSION'});
await assert.rejects(()=>setup({status:'blocked'}).store.configureSettings({enabledCountries:['AE'],supportText:''},'reason'),{code:'ACCOUNT'});
const disabled={};attachProductionSettings(disabled,{config:{writesEnabled:false}});await assert.rejects(()=>disabled.configureSettings({},'reason'),{code:'WRITES_DISABLED'});
f.store.state.settings={supportText:'<script>',enabledCountries:['AE']};f.store.state.cities=[{id:'dubai',country:'AE',region:'Dubai',name:'<img>',enabled:true}];const view=createSettingsView({store:f.store,actor:()=>f.actor,t:(_,en)=>en,esc:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')});const html=view.render();assert.ok(html.includes('marketplace-settings-form'));assert.ok(html.includes('marketplace-city-form'));assert.ok(html.includes('&lt;script>'));assert.ok(!html.includes('<img>'));assert.ok(html.includes('required'));
console.log('PASS production settings validation, scoped writes, audit and escaped forms');
