import * as policy from '../melkak/model.js';
import fs from 'node:fs';import assert from 'node:assert/strict';import {countryConfig} from '../melkak/config.js';import {seed} from '../melkak/fixtures.js';import {createLocalStore} from '../melkak/model.js';import {attachLocalServices} from '../melkak/marketplace-services.js';
const countries=countryConfig(JSON.parse(fs.readFileSync(new URL('../melkak/legacy-countries.json',import.meta.url),'utf8'))),actor={uid:'demo-owner',role:'super_admin'},seller={uid:'demo-seller'},fresh=()=>attachLocalServices(createLocalStore(seed(countries)),countries);let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name)}catch(e){failed++;console.log('FAIL',name,e.message)}}
const draft=()=>{const s=fresh();return {...s.state.listings.find(a=>a.id==='AE-cars'),images:['data:image/jpeg;base64,/9j/AA==']}};
for(const status of ['suspended','blocked'])test(status+' profile cannot create even with stale active actor',()=>{const s=fresh();s.state.users.find(u=>u.uid===actor.uid).status=status;const before=JSON.stringify(s.state);assert.throws(()=>s.create(draft(),{...actor,status:'active'}),/ACCOUNT/);assert.equal(JSON.stringify(s.state),before)});
test('suspending user through reports prevents subsequent creation',()=>{const s=fresh(),r=s.reportUser(seller.uid,'evidence',actor);s.actOnReport(r.id,'suspend','confirmed',actor);const before=JSON.stringify(s.state);assert.throws(()=>s.create(draft(),seller),/ACCOUNT/);assert.equal(JSON.stringify(s.state),before)});
test('owner hide records provenance and eligible republish clears it',()=>{const s=fresh();s.transition('AE-cars','hidden',actor);assert.equal(s.state.listings.find(a=>a.id==='AE-cars').hiddenBy,'owner');s.transition('AE-cars','active',actor);assert.equal(s.state.listings.find(a=>a.id==='AE-cars').hiddenBy,'')});
for(const [name,extra]of Object.entries({admin:{hiddenBy:'admin'},locked:{hiddenBy:'owner',moderationLocked:true},rejected:{hiddenBy:'owner',moderationStatus:'rejected'},suspended:{hiddenBy:'owner',moderationStatus:'suspended'},needs_review:{hiddenBy:'owner',moderationStatus:'needs_review'},pending:{hiddenBy:'owner',moderationStatus:'pending'},review:{hiddenBy:'owner',requiresReview:true},unknown:{},unknown_provenance:{hiddenBy:'other'}}))test(name+' cannot owner republish',()=>{const s=fresh(),a=s.state.listings.find(a=>a.id==='AE-cars');Object.assign(a,{status:'hidden',...extra});const before=JSON.stringify(s.state);assert.throws(()=>s.transition(a.id,'active',actor),/STATE/);assert.equal(JSON.stringify(s.state),before)});
for(const status of ['suspended','blocked'])test(status+' profile cannot republish owner hidden listing',()=>{const s=fresh();Object.assign(s.state.listings.find(a=>a.id==='AE-cars'),{status:'hidden',hiddenBy:'owner'});s.state.users.find(u=>u.uid===actor.uid).status=status;const before=JSON.stringify(s.state);assert.throws(()=>s.transition('AE-cars','active',actor),/ACCOUNT/);assert.equal(JSON.stringify(s.state),before)});
for(const method of ['moderate','report'])test(method+' hide records admin provenance',()=>{const s=fresh();if(method==='moderate')s.moderate('AE-cars','hidden','reason',actor);else{s.report('AE-cars','reason',seller);s.actOnReport(s.state.reports[0].id,'hide','reason',actor)}assert.equal(s.state.listings.find(a=>a.id==='AE-cars').hiddenBy,'admin')});
test('missing stored profile cannot create using claimed active actor',()=>{const s=fresh();const before=JSON.stringify(s.state);assert.throws(()=>s.create(draft(),{uid:'unknown',status:'active'}),/ACCOUNT/);assert.equal(JSON.stringify(s.state),before)});
test('profile removed status cannot create',()=>{const s=fresh();delete s.state.users.find(u=>u.uid===actor.uid).status;assert.throws(()=>s.create(draft(),actor),/ACCOUNT/)});
test('UI republish policy requires active actor and owner provenance',()=>{const s=fresh(),a={...s.state.listings.find(a=>a.id==='AE-cars'),status:'hidden',hiddenBy:'owner'};assert.equal(policy.canRepublish(a,{...actor,status:'active'},s.state.categories),true);for(const status of [undefined,'suspended','blocked'])assert.equal(policy.canRepublish(a,{...actor,status},s.state.categories),false);assert.equal(policy.canRepublish({...a,hiddenBy:'admin'},{...actor,status:'active'},s.state.categories),false)});
console.log('SUMMARY | '+passed+'/'+(passed+failed)+' PASS');if(failed)process.exitCode=1;
