import test from 'node:test';import assert from 'node:assert/strict';import {classifyDecision,createImageModerator} from '../melkak/image-moderation.js';
const scores=(kind='Neutral',p=.99)=>['Porn','Hentai','Sexy','Neutral','Drawing'].map(className=>({className,probability:className===kind?p:(1-p)/4}));
test('stalled load times out without claiming success',async()=>{const m=createImageModerator({loadModel:()=>new Promise(()=>{}),timeoutMs:10});await assert.rejects(m.check('stalled'),/IMAGE_SCAN_FAILED/);assert.equal(m.isAllowed('stalled'),false);});
test('neutral and drawing pass; Sexy alone does not reject',()=>{for(const kind of ['Neutral','Drawing','Sexy'])assert.equal(classifyDecision(scores(kind)).status,'allow');});
test('clear explicit high confidence rejected; borderline requests different image',()=>{for(const kind of ['Porn','Hentai']){assert.equal(classifyDecision(scores(kind,.98)).status,'reject');assert.equal(classifyDecision(scores(kind,.7)).status,'borderline');assert.equal(classifyDecision(scores(kind,.3)).status,'allow');}});
test('malformed or incomplete predictions are not successful checks',()=>{for(const p of [[],scores().slice(0,3),scores().map(x=>({...x,probability:NaN}))])assert.throws(()=>classifyDecision(p),/IMAGE_SCAN_FAILED/);});
test('lazy singleton loads only when checking, caches allowed image and handles multiple',async()=>{let loads=0,calls=0;const m=createImageModerator({loadModel:async()=>{loads++;return {classify:async()=>{calls++;return scores();}}},decode:async x=>x});assert.equal(loads,0);await m.check('a');await m.check('a');await m.check('b');assert.equal(loads,1);assert.equal(calls,2);});
test('failure retry reloads and never caches unexamined image',async()=>{let loads=0;const m=createImageModerator({loadModel:async()=>{if(++loads===1)throw Error('offline');return {classify:async()=>scores()}},decode:async x=>x});await assert.rejects(m.check('a'),/IMAGE_SCAN_FAILED/);await m.check('a');assert.equal(loads,2);});
test('reject/borderline do not pass or cache as allowed',async()=>{for(const p of [.98,.7]){const m=createImageModerator({loadModel:async()=>({classify:async()=>scores('Porn',p)}),decode:async x=>x});await assert.rejects(m.check('a'),new RegExp(p>.9?'IMAGE_REJECTED':'IMAGE_BORDERLINE'));assert.equal(m.isAllowed('a'),false);}});

 test('needs_review has bilingual labels for listing and moderation UI',async()=>{const {STATUS}=await import('../melkak/config.js');assert.deepEqual(STATUS.needs_review,['يتطلب مراجعة','Needs review']);});
