import fs from 'node:fs';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import * as sdk from 'firebase/firestore';
import {attachProductionCommercial} from '../melkak/production-commercial.js';

// This suite cannot address a live Firebase project or an arbitrary host.
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080')throw Error('Use FIRESTORE_EMULATOR_HOST=127.0.0.1:8080 only');
const env=await initializeTestEnvironment({projectId:'demo-melkak-commercial-release',firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync(new URL('../melkak/firestore.proposed.rules',import.meta.url),'utf8')}});
const {doc,setDoc,getDoc,getDocs,collection,query,where,limit,serverTimestamp,writeBatch,updateDoc}=sdk;
const boss=env.authenticatedContext('boss',{admin:true}).firestore(),seller=env.authenticatedContext('seller').firestore(),other=env.authenticatedContext('other').firestore(),assistant=env.authenticatedContext('assistant').firestore(),anon=env.unauthenticatedContext().firestore();
const image='data:image/jpeg;base64,YQ==',now=Date.now();
const campaign=(patch={})=>({title:'Emulator campaign',advertiserName:'Local advertiser',description:'Only emulator test data',cta:'Visit',image,targetUrl:'https://example.com/campaign',countryTarget:'AE',placement:'hero',priority:10,startAt:now-120000,endAt:now+86400000,...patch});
const service=(db,uid,role='user')=>attachProductionCommercial({refresh:async()=>{}},{sdk,db,auth:{state:{actor:{uid,role,status:'active',ready:true}}},config:{writesEnabled:true}});
const sellerStore=service(seller,'seller'),bossStore=service(boss,'boss','super_admin');
const publicRef=(db,id)=>doc(db,'marketplaceCommercialAds',id),imageRef=(db,id)=>doc(db,'marketplaceCommercialImages',id),requestRef=(db,id)=>doc(db,'marketplaceRequests',id);
let passed=0,failed=0;const check=async(name,fn)=>{try{await fn();passed++;console.log('PASS | '+name);}catch(error){failed++;console.error('FAIL | '+name+' | '+error.message);}};
let approvedId;
try {
 await env.clearFirestore();
 await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();for(const uid of ['boss','seller','other','assistant'])await setDoc(doc(db,'users',uid),{status:'active',accountType:'buyer'});await setDoc(doc(db,'adminSecurity','config'),{enabled:true,superAdminUids:['boss']});await setDoc(doc(db,'adminAccess','assistant'),{role:'admin_assistant',adminStatus:'active',permissions:['services_view','services_manage']});for(const category of ['livestock','cars','phones','computers','appliances','furniture','tools','sports','children','other'])await setDoc(doc(db,'marketplaceCategories',category),{enabled:true});});
 await check('private pending request readable to its owner and hidden from outsider',async()=>{const {id}=await sellerStore.requestCommercial(campaign());approvedId=id;const row=await assertSucceeds(getDoc(requestRef(seller,id)));assert.equal(row.data().status,'pending');await assertFails(getDoc(requestRef(other,id)));await assertFails(getDoc(requestRef(anon,id)));});
 await check('real SDK approval atomically publishes metadata and separate image',async()=>{await bossStore.reviewCommercial(approvedId,'approved','Campaign reviewed');const meta=(await getDoc(publicRef(boss,approvedId))).data(),privateRow=(await getDoc(requestRef(boss,approvedId))).data();assert.equal(meta.status,'approved');assert.equal(meta.ownerUid,'seller');assert.equal(meta.requestId,approvedId);assert.equal(meta.auditId,privateRow.auditId);assert.equal('image' in meta,false);assert.equal('data' in meta,false);assert.equal((await getDoc(imageRef(boss,approvedId))).data().imageData,image);});
 await check('anonymous current query and current image read succeed',async()=>{const at=Date.now();const rows=await assertSucceeds(getDocs(query(collection(anon,'marketplaceCommercialAds'),where('status','==','approved'),where('startAt','<=',at-30000),where('endAt','>',at+30000),limit(100))));assert.ok(rows.docs.some(row=>row.id===approvedId));await assertSucceeds(getDoc(imageRef(anon,approvedId)));});
 await check('future campaign and image remain inaccessible publicly',async()=>{const {id}=await sellerStore.requestCommercial(campaign({startAt:now+86400000,endAt:now+2*86400000}));await bossStore.reviewCommercial(id,'approved','Schedule reviewed');await assertFails(getDoc(publicRef(anon,id)));await assertFails(getDoc(imageRef(anon,id)));});
 await check('expired metadata and image remain inaccessible publicly',async()=>{await env.withSecurityRulesDisabled(async context=>{const db=context.firestore(),{image:art,...metadata}=campaign({startAt:now-86400000,endAt:now-1000});await setDoc(publicRef(db,'expired'),{...metadata,status:'approved',ownerUid:'seller',requestId:'expired',updatedAt:serverTimestamp(),auditId:'seed'});await setDoc(imageRef(db,'expired'),{imageData:art,updatedAt:serverTimestamp()});});await assertFails(getDoc(publicRef(anon,'expired')));await assertFails(getDoc(imageRef(anon,'expired')));});
 await check('edit pause and reapproval preserve provenance and synchronize visibility',async()=>{const original=(await getDoc(requestRef(boss,approvedId))).data();await bossStore.editCommercial(approvedId,campaign({title:'Edited title',image:'data:image/jpeg;base64,Yg=='}),'Correct campaign');assert.equal((await getDoc(publicRef(anon,approvedId))).data().title,'Edited title');await bossStore.reviewCommercial(approvedId,'paused','Pause campaign');await assertFails(getDoc(publicRef(anon,approvedId)));await assertFails(getDoc(imageRef(anon,approvedId)));await bossStore.reviewCommercial(approvedId,'approved','Resume campaign');await assertSucceeds(getDoc(imageRef(anon,approvedId)));const row=(await getDoc(requestRef(boss,approvedId))).data();assert.equal(row.ownerUid,original.ownerUid);assert.ok(row.createdAt.isEqual(original.createdAt));});
 await check('ordinary users and assistants cannot directly publish metadata or images',async()=>{const body=(await getDoc(publicRef(boss,approvedId))).data();for(const db of [seller,assistant]){await assertFails(setDoc(publicRef(db,'forged'),{...body,requestId:'forged',updatedAt:serverTimestamp()}));await assertFails(setDoc(imageRef(db,'forged'),{imageData:image,updatedAt:serverTimestamp()}));}});
 await check('admin cannot publish without atomic approved request linkage',async()=>{const body=(await getDoc(publicRef(boss,approvedId))).data();await assertFails(setDoc(publicRef(boss,'missing-link'),{...body,requestId:'missing-link',updatedAt:serverTimestamp()}));const {id}=await sellerStore.requestCommercial(campaign());await assertFails(setDoc(publicRef(boss,id),{...body,requestId:id,updatedAt:serverTimestamp()}));});
 await check('blank reason is rejected by rules even when bypassing service validation',async()=>{const auditId='blank-reason',batch=writeBatch(boss);batch.update(requestRef(boss,approvedId),{status:'paused',auditId,updatedAt:serverTimestamp()});batch.update(publicRef(boss,approvedId),{status:'paused',auditId,updatedAt:serverTimestamp()});batch.set(doc(boss,'marketplaceAuditLogs',auditId),{actorUid:'boss',action:'commercial-paused',targetId:approvedId,targetCollection:'marketplaceRequests',reason:'',timestamp:serverTimestamp(),result:'paused'});await assertFails(batch.commit());assert.equal((await getDoc(requestRef(boss,approvedId))).data().status,'approved');});
 await check('rules reject oversized request and image payloads without client validation',async()=>{const oversized='data:image/jpeg;base64,'+'A'.repeat(110000);await assertFails(setDoc(requestRef(seller,'oversized'),{type:'commercial',ownerUid:'seller',status:'pending',createdAt:serverTimestamp(),data:campaign({image:oversized})}));await assertFails(setDoc(imageRef(boss,approvedId),{imageData:oversized,updatedAt:serverTimestamp()}));});
 await check('all Hero orders, side slots, middle and footer slots can publish',async()=>{const variants=[...Array.from({length:10},(_,i)=>({placement:'hero',priority:10-i})),...[1,2,3].map(i=>({placement:'hero_side_'+i})),{placement:'middle'},...[1,2,3,4,5].map(i=>({placement:'footer_'+i}))];for(const variant of variants){const {id}=await sellerStore.requestCommercial(campaign(variant));await bossStore.reviewCommercial(id,'approved','Placement reviewed');const row=(await assertSucceeds(getDoc(publicRef(anon,id)))).data();assert.equal(row.placement,variant.placement);assert.equal(row.priority,variant.priority??10);}});
 console.log(`SUMMARY | ${passed}/${passed+failed} PASS`);if(failed)process.exitCode=1;
} finally {await env.cleanup();}
