const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
const out=process.env.MELKAK_QA||path.join(require('os').tmpdir(),'melkak-v2-final');fs.mkdirSync(out,{recursive:true});let n=0;const pass=s=>{n++;console.log('PASS | '+s)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],remote=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8786/'))remote.push(r.url())});
await page.goto('http://127.0.0.1:8786/');await page.waitForFunction(()=>window.__melkak);await page.evaluate(()=>document.fonts.ready);
const nav=async route=>{await page.evaluate(r=>location.hash='#/'+r,route);await page.waitForTimeout(100)};
const shot=async name=>{await page.waitForFunction(()=>!document.querySelector('#toast').textContent);await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=600){scrollTo(0,y);await new Promise(r=>setTimeout(r,70))}scrollTo(0,0)});await page.evaluate(()=>document.activeElement?.blur());await page.waitForTimeout(150);await page.screenshot({path:path.join(out,name),fullPage:true})};
await page.locator('.skip').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#main').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.world-hero').count(),1);pass('skip link focuses content without changing route');
const original=await page.evaluate(()=>structuredClone(window.__melkak.store.state));
assert.equal(await page.locator('.world-countries button').count(),6);assert.equal(await page.locator('.home-categories .category').count(),10);assert.equal(await page.locator('.home-categories [href="#/market/livestock"]').count(),1);pass('six countries and ten unique categories');
const sections=await page.locator('.market-main>.home-section').evaluateAll(es=>es.map(e=>e.className));assert.deepEqual(sections,['home-section featured-section','home-section latest-section']);pass('home section order and bounded content');
for(const count of [1,2,5]){await page.evaluate(({listings,count})=>{const w=window.__melkak;w.store.state.listings=structuredClone(listings);w.store.state.listings.filter(a=>a.country==='AE').forEach((a,i)=>{a.featuredStatus=i<count?'approved':null;a.featuredEndAt=Date.now()+86400000});w.render()},{listings:original.listings,count});assert.equal(await page.locator('.featured-section .listing').count(),count);const box=await page.locator('.featured-section .listing').first().boundingBox(),normal=await page.locator('.latest-section .listing').first().boundingBox();assert.ok(box.width/normal.width>=1.05&&box.width/normal.width<=1.08,JSON.stringify({count,box,normal}));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('featured '+count+' items at 5–8% size and no page overflow')}
await page.evaluate(listings=>{window.__melkak.store.state.listings=listings;window.__melkak.render()},original.listings);await shot('home-1440-v2.png');
await page.setViewportSize({width:390,height:844});await nav('home');
const dimensions=await page.evaluate(()=>({height:document.documentElement.scrollHeight,hero:document.querySelector('.world-hero').clientHeight,featuredTop:document.querySelector('.featured-section').getBoundingClientRect().top}));assert.ok(dimensions.height<3200);assert.ok(dimensions.hero<=230);assert.ok(dimensions.featuredTop<620);fs.writeFileSync(path.join(out,'dimensions.json'),JSON.stringify({before:{height:4649,hero:338,featuredTop:780.1875},after:dimensions},null,2));pass('mobile page shortened and featured near first viewport');
assert.equal(await page.locator('.side-ads').isVisible(),false);assert.equal(await page.locator('.middle-promo .promo-block').count(),1);assert.equal(await page.locator('.footer-ads .promo-block').count(),1);assert.equal(await page.locator('.mobile-promos .promo-block').count(),3);pass('mobile displays three inline side ads plus middle and footer');
const lazy=await page.locator('.latest-section img[data-card-src]').count();assert.ok(lazy>0);const row=page.locator('.featured-section .cards');await row.focus();await page.keyboard.press('ArrowLeft');assert.ok(Math.abs(await row.evaluate(e=>e.scrollLeft))>0);pass('keyboard carousel and offscreen image deferral');
await page.locator('[data-action=filter-drawer]').click();assert.ok(await page.locator('#dialog').isVisible());await page.locator('#compact-filters [name=country]').selectOption('SA');await page.locator('#compact-filters [name=category]').selectOption('cars');await page.locator('#compact-filters [name=min]').fill('10');await page.locator('#compact-filters [name=max]').fill('200000');await page.locator('#compact-filters [name=sort]').selectOption('oldest');await page.locator('#compact-filters button').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.__melkak.state.country),'SA');assert.equal(await page.evaluate(()=>window.__melkak.state.sort),'oldest');assert.match(await page.locator('.listing .price').first().innerText(),/SAR/);pass('mobile filter modal country category price sort apply');
await page.locator('[data-action=filter-drawer]').click();assert.equal(await page.locator('#compact-filters [name=min]').inputValue(),'10');await page.keyboard.press('Escape');assert.equal(await page.locator('#dialog').isVisible(),false);pass('filter values persist Escape closes and restores focus');
await page.evaluate(()=>{const s=window.__melkak.state;Object.assign(s,{country:'AE',city:'',category:'',min:'',max:'',sort:'newest'});});await nav('home');await shot('home-390-v2.png');
await page.setViewportSize({width:1440,height:1000});await nav('listing/AE-livestock');await page.evaluate(()=>{const a=window.__melkak.store.state.listings.find(a=>a.id==='AE-livestock');a.images=Array(3).fill('./melkak/assets/livestock.svg');window.__melkak.render()});assert.equal(await page.locator('.thumbs button').count(),2);await page.locator('.thumbs button').first().click();assert.match(await page.locator('.detail-stage .photo-count').innerText(),/2 \/ 3/);pass('three-image gallery retained');await shot('listing-details-v2.png');await nav('my-listings');await shot('my-listings-v2.png');await nav('manage/AE-cars');await shot('manage-listing-v2.png');pass('details my listings manage screenshots with preserved actions');
await page.locator('#preview-role').selectOption('super_admin');await nav('admin');assert.equal(await page.locator('.stat').count(),7);await page.locator('#admin-country').selectOption('SA');assert.equal(await page.locator('[data-stat=users] strong').innerText(),'0');await nav('admin/users');assert.match(await page.locator('tbody').innerText(),/لا توجد/);await page.locator('#admin-country').selectOption('AE');assert.match(await page.locator('tbody').innerText(),/Super Admin/);pass('country filter affects counters and user list');
await nav('admin');await shot('admin-home-v2.png');await nav('admin/commercial');assert.equal(await page.locator('.hero-map .map-slot').count(),10);assert.equal(await page.locator('.side-map .map-slot').count(),3);assert.equal(await page.locator('.campaign-tabs button').count(),4);assert.equal(await page.locator('.campaign').count(),10);pass('map first ten Hero three side slots and request tabs');
await page.evaluate(()=>{const w=window.__melkak;const sample=w.store.state.ads[0];for(let i=0;i<13;i++)w.store.state.ads.push({...sample,id:'page-'+i,title:'طلب إضافي '+i});w.render()});assert.equal(await page.locator('.campaign').count(),10);await page.locator('[data-action=campaign-page][data-id="1"]').click();assert.equal(await page.locator('.campaign').count(),10);await page.locator('[data-action=campaign-page][data-id="1"]').click();assert.equal(await page.locator('.campaign').count(),3);assert.ok(await page.locator('[data-action=campaign-page][data-id="1"]').isDisabled());pass('23 requests paginated 10 10 3');
for(const state of ['active','expiring','expired']){await page.locator('[data-action=campaign-tab][data-id='+state+']').click();const expected=await page.evaluate(state=>window.__melkak.store.state.ads.filter(a=>state==='active'?a.status==='active':false).length,state);if(state==='active')assert.equal(await page.locator('.campaign').count(),Math.min(expected,10));else assert.equal(await page.locator('.campaign').count(),0);pass('campaign tab '+state)}
await page.evaluate(ads=>{const w=window.__melkak;w.store.state.ads=ads;w.state.commercialTab='pending';w.state.commercialPage=1;w.render()},original.ads);await shot('commercial-ads-map-v2.png');
await page.setViewportSize({width:390,height:844});await nav('admin');assert.equal(await page.locator('.admin-sidebar').isVisible(),false);await page.locator('[data-action=admin-drawer]').click();assert.ok(await page.locator('dialog.navigation-drawer').isVisible());assert.ok(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)));for(let i=0;i<18;i++){await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)))}await page.keyboard.press('Escape');assert.ok(await page.locator('[data-action=admin-drawer]').evaluate(e=>e===document.activeElement));pass('native admin drawer keyboard trap Escape and return focus');await shot('admin-mobile-v2.png');
for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:950});for(const route of ['home','listing/AE-cars','my-listings','manage/AE-cars','admin','admin/commercial']){await nav(route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' '+width)}pass('responsive RTL '+width)}
await page.setViewportSize({width:390,height:844});await nav('admin');await page.locator('#preview-role').selectOption('assistant');await page.locator('[data-action=admin-drawer]').click();assert.equal(await page.locator('#dialog a[href="#/admin/commercial"]').count(),0);assert.equal(await page.locator('#dialog a[href="#/admin/users"]').count(),0);await page.keyboard.press('Escape');pass('drawer preserves assistant menu permissions');await page.locator('#preview-role').selectOption('super_admin');
await page.evaluate(()=>{const w=window.__melkak;w.state.country='AE';const a=w.store.state.listings.find(a=>a.id==='AE-livestock');a.featuredEndAt=Date.now()-1000;});await nav('home');assert.equal(await page.locator('.featured-section [data-listing=AE-livestock]').count(),0);assert.ok(await page.evaluate(()=>window.__melkak.store.state.listings.find(a=>a.id==='AE-livestock').status==='active'));pass('expiry returns normal and preserves publication');
await page.evaluate(()=>{const w=window.__melkak;const a=w.store.state.listings.find(a=>a.id==='AE-livestock');a.featuredStartAt=Date.now()+86400000;a.featuredEndAt=Date.now()+172800000;w.render()});assert.equal(await page.locator('.featured-section [data-listing=AE-livestock]').count(),0);pass('future featured remains normal');
for(const route of ['home','listing/AE-cars','my-listings']){await nav(route);assert.doesNotMatch(await page.locator('#main').innerText(),/شراء الآن|طلب شراء|مراسلة|مزاد/)}pass('no auction purchase or internal messaging UX');
await nav('home');for(const kind of ['call','whatsapp']){await page.locator('[data-contact='+kind+']').first().click();assert.match(await page.locator('#toast').innerText(),/تجريبي/)}pass('call and WhatsApp preserved safely in demo');
const labels=await page.locator('.promo-block .tag').allTextContents();assert.ok(labels.every(s=>s==='إعلان ترويجي'));pass('all promotional placements clearly labeled');
for(const [country,currency]of Object.entries({AE:'AED',SA:'SAR',EG:'EGP',OM:'OMR',JO:'JOD',MA:'MAD'})){await page.evaluate(country=>window.__melkak.state.country=country,country);await nav('market');await page.evaluate(()=>window.__melkak.render());assert.match(await page.locator('.listing .price').first().innerText(),new RegExp(currency));pass('currency '+currency)}
await page.locator('[data-action=language]').click();for(const width of [390,1440]){await page.setViewportSize({width,height:950});await nav('home');assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('LTR '+width)}
for(const route of ['privacy','terms']){await nav(route);assert.ok(await page.locator('h1').innerText());pass('footer local '+route)}
assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);assert.equal(await page.evaluate(()=>window.__melkak.flags.productionWrites||window.__melkak.flags.analytics||window.__melkak.flags.payments),false);pass('0 JS errors 0 remote requests disabled flags');
console.log('SUMMARY | '+n+'/'+n+' PASS');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
