const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});let n=0;try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!=='http://127.0.0.1:8835')return route.abort();const name=url.pathname.slice(1)||'account-deletion.html';if(name==='melkak/auth-adapter.js')return route.fulfill({contentType:'text/javascript',body:`const user={uid:'mock-owner'},listeners=[];let state={user:null};export async function loadFirebaseSdk(){return {getApp:()=>({}),getFirestore:()=>({}),doc:(_d,c,id)=>({c,id}),getIdTokenResult:async()=>({authTime:new Date().toISOString()}),serverTimestamp:()=> 'SERVER',runTransaction:async(_db,fn)=>fn({get:async()=>({exists:()=>false}),set:()=>{window.requestCount=(window.requestCount||0)+1}})};}export async function createFirebaseAuthAdapter(){return {get state(){return state},subscribe(fn){listeners.push(fn);fn(state)},async signInGoogle(){state={user};listeners.forEach(fn=>fn(state))}}}`});
const f=path.resolve(name);if(!f.startsWith(process.cwd()+path.sep)||!fs.existsSync(f))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.ttf':'font/ttf'})[path.extname(f)]||'application/octet-stream'});});
for(const width of [360,390,430,768,1024,1440]){await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:8835/account-deletion.html');await page.getByRole('heading',{name:'حذف حسابي في مِلكك'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);n++;}
assert.equal(await page.evaluate(()=>window.requestCount||0),0);n++;
await page.getByRole('button',{name:'التحقق باستخدام Google'}).click();await page.locator('#deletion-confirm').waitFor();
await page.getByRole('button',{name:'إرسال طلب حذف حسابي'}).click();assert.equal(await page.evaluate(()=>window.requestCount||0),0);n++;
await page.locator('#deletion-confirm').check();await page.getByRole('button',{name:'إرسال طلب حذف حسابي'}).click();await page.getByRole('status').filter({hasText:'تم تسجيل الطلب'}).waitFor();assert.equal(await page.evaluate(()=>window.requestCount),1);n++;
assert.equal(await page.getByRole('button',{name:'إرسال طلب حذف حسابي'}).isDisabled(),true);n++;
await page.getByRole('button',{name:'العربية / English'}).click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');n++;
await page.goto('http://127.0.0.1:8835/melkak-privacy.html');assert.ok((await page.locator('body').innerText()).includes('18'));assert.ok(await page.locator('a[href="./account-deletion.html"]').count());n++;
assert.deepEqual(errors,[]);n++;console.log(`SUMMARY ${n}/${n} PASS; JavaScript errors 0; network restricted to local mocks`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
