import fs from 'node:fs';
import assert from 'node:assert/strict';
import {initializeTestEnvironment,assertFails} from '@firebase/rules-unit-testing';
import * as sdk from 'firebase/firestore';
import {normalizeProductionListing} from '../melkak/production-model.js';
import {attachProductionServices} from '../melkak/production-services.js';
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080')throw Error('Local emulator required');
sdk.setLogLevel('silent');
const rule=process.env.MODERATION_RULES||'firestore.proposed.rules';
const env=await initializeTestEnvironment({projectId:'demo-melkak-free-moderation',firestore:{rules:fs.readFileSync(new URL('../melkak/'+rule,import.meta.url),'utf8')}});
const img=n=>'data:image/jpeg;base64,'+['AAAA','BBBB','CCCC'][n];
const failures=[];let passed=0;
async function check(name,fn){try{await fn();passed++;console.log('PASS',name);}catch(e){failures.push(name);console.error('FAIL',name,e.stack||e.message);}}
const dbs=Object.fromEntries(['boss','seller','other','assistant'].map(uid=>[uid,env.authenticatedContext(uid,uid==='boss'?{admin:true}:{}).firestore()]));
const service=(uid,role=uid==='boss'?'super_admin':uid==='assistant'?'admin_assistant':'user')=>attachProductionServices({state:{listings:[],categories:[],settings:{enabledCountries:['AE']}},refresh:async()=>{}},{sdk,db:dbs[uid],auth:{state:{actor:{uid,role,status:'active',ready:true,permissions:uid==='assistant'?['listings_manage','reports_manage']:[]}}},config:{writesEnabled:true}});
const boss=service('boss');
async function read(id,collection='marketplaceListings'){let result;await env.withSecurityRulesDisabled(async c=>{const s=await sdk.getDoc(sdk.doc(c.firestore(),collection,id));result=s.exists()?s.data():undefined;});return result;}
async function seed(id,patch={}){await env.withSecurityRulesDisabled(c=>sdk.setDoc(sdk.doc(c.firestore(),'marketplaceListings',id),{schemaVersion:1,ownerUid:'seller',category:'cars',country:'AE',currency:'AED',region:'Dubai',city:'Dubai',title:'Local listing',description:'A local moderation test listing',price:1,attributes:{},contact:{phone:'+971500000000',consent:true,call:true,whatsapp:false,showNumber:false},images:[img(0),img(1),img(2)],status:'active',hasHistory:false,createdAt:sdk.Timestamp.fromMillis(1),updatedAt:sdk.Timestamp.fromMillis(1),...patch}));}
async function audited(db,id,patch,action,result,actorUid='boss'){const log=sdk.doc(sdk.collection(db,'marketplaceAuditLogs'));const b=sdk.writeBatch(db);b.update(sdk.doc(db,'marketplaceListings',id),{...patch,auditId:log.id,updatedAt:sdk.serverTimestamp()});b.set(log,{actorUid,action,targetCollection:'marketplaceListings',targetId:id,reason:'Reviewed by moderator',timestamp:sdk.serverTimestamp(),result});return b.commit();}
try{
 await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{for(const uid of Object.keys(dbs))await sdk.setDoc(sdk.doc(c.firestore(),'users',uid),{status:'active'});await sdk.setDoc(sdk.doc(c.firestore(),'adminSecurity','config'),{enabled:true,superAdminUids:['boss']});await sdk.setDoc(sdk.doc(c.firestore(),'adminAccess','assistant'),{role:'admin_assistant',adminStatus:'active',permissions:['listings_manage','reports_manage']});await sdk.setDoc(sdk.doc(c.firestore(),'marketplaceCategories','cars'),{enabled:true});});
 await check('needs_review locks owner and audited admin can republish',async()=>{await seed('review');await boss.moderate('review','needs_review','Needs manual review');let d=await read('review');assert.equal(d.status,'needs_review');assert.equal(d.moderationLocked,true);assert.equal((await read(d.auditId,'marketplaceAuditLogs')).action,'moderate-needs_review');await assertFails(sdk.updateDoc(sdk.doc(dbs.seller,'marketplaceListings','review'),{status:'active',moderationLocked:false,updatedAt:sdk.serverTimestamp()}));await boss.moderate('review','active','Review complete');assert.equal((await read('review')).status,'active');});
 await check('specific image removal preserves other images, last image cannot republish',async()=>{await seed('images');await boss.removeListingImage('images',img(1),'Remove offending photo');let d=await read('images');assert.deepEqual(d.images,[img(0),img(2)]);assert.equal(d.status,'needs_review');assert.equal((await read(d.auditId,'marketplaceAuditLogs')).action,'listing-image-removed');await assert.rejects(()=>boss.removeListingImage('images',img(1),'Stale image removal'));await boss.removeListingImage('images',img(0),'Remove offending photo');await boss.removeListingImage('images',img(2),'Remove final offending photo');assert.deepEqual((await read('images')).images,[]);await assert.rejects(()=>boss.moderate('images','active','Invalid empty publish'));await assertFails(audited(dbs.boss,'images',{status:'active',hiddenBy:'',moderationLocked:false,hasHistory:true},'moderate-active','active'));});
 await check('historical removal is atomic permanent archive preserving reference',async()=>{await seed('history',{hasHistory:true});const r=await boss.adminDeleteListing('history','Remove historical listing');assert.equal(r.archived,true);const d=await read('history');assert.equal(d.removed,true);assert.equal(d.status,'archived');assert.equal(d.moderationLocked,true);assert.equal((await read(d.auditId,'marketplaceAuditLogs')).action,'listing-removed');await assert.rejects(()=>boss.moderate('history','active','Must remain removed'));await assertFails(audited(dbs.boss,'history',{status:'active',hiddenBy:'',moderationLocked:false,hasHistory:true},'moderate-active','active'));await assert.rejects(()=>service('assistant').adminDeleteListing('history','Assistant forbidden'));});
 await check('report needs_review links listing and two audits atomically',async()=>{await seed('reported');await env.withSecurityRulesDisabled(c=>sdk.setDoc(sdk.doc(c.firestore(),'marketplaceRequests','report'),{type:'report',ownerUid:'other',listingId:'reported',status:'open',reason:'Offending listing',createdAt:sdk.Timestamp.fromMillis(1)}));await boss.actOnReport('report','needs_review','Review reported photo');const d=await read('reported'),r=await read('report','marketplaceRequests');assert.equal(d.status,'needs_review');assert.equal(r.status,'reviewing');assert.notEqual(d.auditId,r.auditId);});
 await check('normal/forged actor, orphan audit, blank reason, multiple/remixed image writes denied',async()=>{await seed('denied');await assert.rejects(()=>service('other').removeListingImage('denied',img(0),'Forbidden owner'));await assert.rejects(()=>service('other','super_admin').removeListingImage('denied',img(0),'Forged role'));await assert.rejects(()=>boss.removeListingImage('denied',img(0),'  '));await assertFails(audited(dbs.boss,'denied',{images:[img(0)],status:'needs_review',moderationLocked:true,hiddenBy:'',hasHistory:true},'listing-image-removed','needs_review'));await assertFails(audited(dbs.boss,'denied',{images:[img(0),'data:image/jpeg;base64,DDDD'],status:'needs_review',moderationLocked:true,hiddenBy:'',hasHistory:true},'listing-image-removed','needs_review'));await assertFails(sdk.setDoc(sdk.doc(dbs.boss,'marketplaceAuditLogs','orphan'),{actorUid:'boss',action:'listing-image-removed',targetCollection:'marketplaceListings',targetId:'denied',reason:'Orphan audit',timestamp:sdk.serverTimestamp(),result:'needs_review'}));await assertFails(audited(dbs.boss,'denied',{status:'needs_review',moderationLocked:true,hiddenBy:'',hasHistory:true},'moderate-needs_review','needs_review','seller'));});
 await check('assistant authorized review works but permanent removal denied by Rules',async()=>{await seed('assist');await service('assistant').moderate('assist','needs_review','Assistant reviewed');await service('assistant').removeListingImage('assist',img(1),'Assistant remove photo');await assertFails(audited(dbs.assistant,'assist',{removed:true,status:'archived',hiddenBy:'',moderationLocked:true,hasHistory:true},'listing-removed','archived','assistant'));});
 await check('owner direct moderation and missing audit denied; assistant cannot forge permissions',async()=>{await seed('direct');const patch={status:'needs_review',hiddenBy:'',moderationLocked:true,hasHistory:true};await assertFails(audited(dbs.seller,'direct',patch,'moderate-needs_review','needs_review','seller'));await assertFails(sdk.updateDoc(sdk.doc(dbs.boss,'marketplaceListings','direct'),{...patch,updatedAt:sdk.serverTimestamp()}));await env.withSecurityRulesDisabled(c=>sdk.updateDoc(sdk.doc(c.firestore(),'adminAccess','assistant'),{permissions:['reports_manage']}));await assert.rejects(()=>service('assistant').removeListingImage('direct',img(0),'Forged cached permissions'));await assert.rejects(()=>service('assistant').moderate('direct','needs_review','Forged cached permissions'));assert.equal((await read('direct')).status,'active');});
 await check('permanent archive cannot strip tombstone, images or hard-delete',async()=>{const ref=sdk.doc(dbs.boss,'marketplaceListings','history');await assertFails(audited(dbs.boss,'history',{removed:false,status:'active',hiddenBy:'',moderationLocked:false,hasHistory:true},'moderate-active','active'));await assertFails(sdk.deleteDoc(ref));await assert.rejects(()=>boss.removeListingImage('history',img(0),'Cannot mutate removed listing'));assert.equal((await read('history')).removed,true);});
 await check('empty review and removed archive remain private and normalize without fake images',async()=>{const anonymous=env.unauthenticatedContext().firestore();for(const id of ['images','history']){await assertFails(sdk.getDoc(sdk.doc(anonymous,'marketplaceListings',id)));const data=await read(id),row=normalizeProductionListing(id,data,{AE:{currency:'AED'}});assert.equal(row.status,data.status);assert.deepEqual(row.images,data.images);if(id==='history')assert.equal(row.removed,true);else assert.deepEqual(row.images,[]);}});
 await check('normal users publish direct active with 1-3 images; zero/four and forged moderation fields denied',async()=>{const base=await read('direct'),make=images=>({...base,images,status:'active',hasHistory:false,createdAt:sdk.serverTimestamp(),updatedAt:sdk.serverTimestamp()});for(const count of [1,2,3]){const ref=sdk.doc(dbs.seller,'marketplaceListings','new-'+count);await sdk.setDoc(ref,make([img(0),img(1),img(2)].slice(0,count)));assert.equal((await sdk.getDoc(ref)).data().status,'active');}for(const [id,patch]of Object.entries({empty:{images:[]},four:{images:[img(0),img(1),img(2),'data:image/jpeg;base64,DDDD']},locked:{moderationLocked:false},removed:{removed:false},review:{requiresReview:false},audit:{auditId:'fake'},classifier:{moderationStatus:'approved'}}))await assertFails(sdk.setDoc(sdk.doc(dbs.seller,'marketplaceListings','bad-'+id),{...make([img(0)]),...patch}));});
 console.log(`${rule}: ${passed} passed, ${failures.length} failed`);if(failures.length)process.exitCode=1;
}finally{await env.cleanup();}
