const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/asus/AppData/Local/OpenAI/Codex/runtimes/cua_node/b58ca2eaa616c2da/bin/node_modules/playwright-core');
const base=process.env.MELKAK_TEST_URL||'http://127.0.0.1:8786/';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});let failed=0,passed=0;try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],writes=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))writes.push(r.url());if(new URL(r.url()).origin!==new URL(base).origin)external.push(r.url())});
await page.goto(base);await page.waitForFunction(()=>window.__melkak);await page.evaluate(()=>document.fonts.ready);
const check=async(name,fn)=>{try{await fn();passed++;console.log('PASS '+name)}catch(e){failed++;console.error('FAIL '+name+': '+e.message)}};
await check('five diverse featured demo listings',async()=>{assert.equal(await page.locator('.featured-section .listing').count(),5);assert.equal(await page.evaluate(()=>new Set(window.__melkak.store.state.listings.filter(a=>a.country==='AE'&&a.featuredStatus==='approved').map(a=>a.category)).size),5)});
await check('wide desktop main and right commercial sidebar',async()=>{const layout=await page.locator('.market-layout').boundingBox(),main=await page.locator('.market-main').boundingBox(),side=await page.locator('.side-ads').boundingBox();assert.ok(layout.width>=1340);assert.ok(side.x>main.x);assert.ok(main.width>1000);assert.ok(side.width>=190)});
await check('featured full width horizontal composition',async()=>{const s=await page.locator('.featured-section').boundingBox(),m=await page.locator('.market-main').boundingBox(),boxes=await page.locator('.featured-section .listing').evaluateAll(es=>es.map(e=>({y:e.getBoundingClientRect().y,w:e.getBoundingClientRect().width})));assert.ok(s.width/m.width>.97);assert.ok(boxes.every(b=>Math.abs(b.y-boxes[0].y)<2));const normal=await page.locator('.latest-section .listing').first().boundingBox();assert.ok(boxes[0].w/normal.width>=1.05&&boxes[0].w/normal.width<=1.09)});
for(let i=1;i<=3;i++)await check('side ad '+i+' image label title CTA',async()=>{const a=page.locator('.side-ads [data-commercial="hero_side_'+i+'"]');assert.ok(await a.isVisible());assert.equal(await a.locator('.tag').innerText(),'إعلان ترويجي');assert.ok(await a.locator('h3').innerText());assert.ok(await a.locator('.button').isVisible());await a.locator('img').scrollIntoViewIfNeeded();await page.waitForFunction(id=>{const i=document.querySelector('.side-ads [data-commercial="'+id+'"] img');return i.complete&&i.naturalWidth>=600},'hero_side_'+i)});
await check('latest listings and single livestock category',async()=>{assert.ok(await page.locator('.latest-section .listing').count()>=5);assert.equal(await page.locator('.home-categories a[href="#/market/livestock"]').count(),1)});
await check('realistic local demo images in six categories',async()=>{const images=await page.evaluate(()=>['livestock','cars','phones','furniture','tools','appliances'].map(k=>window.__melkak.store.state.listings.find(a=>a.id==='AE-'+k).images[0]));for(const src of images){assert.match(src,/\.webp$/);const r=await page.request.get(new URL(src,base).href);assert.equal(r.status(),200);assert.ok((await r.body()).length<180000)}});
for(const width of [360,390,430,768,1024,1440])await check('responsive '+width,async()=>{await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width<=800){assert.equal(await page.locator('.side-ads').isVisible(),false);for(let i=1;i<=3;i++)assert.ok(await page.locator('.mobile-promos [data-commercial="hero_side_'+i+'"]').isVisible());}else assert.ok(await page.locator('.side-ads').isVisible())});
await check('LTR keyboard and labelled featured controls',async()=>{await page.locator('[data-action=language]').click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('.featured-section .cards').focus();assert.ok(await page.locator('.featured-section .cards').evaluate(e=>e===document.activeElement));await page.locator('[data-action=language]').click()});
await check('demo isolation and zero writes/errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);assert.deepEqual(external,[]);assert.equal(await page.evaluate(()=>window.__melkak.flags.productionWrites||window.__melkak.flags.analytics||window.__melkak.flags.payments),false)});
if(process.env.MELKAK_QA){fs.mkdirSync(process.env.MELKAK_QA,{recursive:true});for(const width of [1440,390]){await page.setViewportSize({width,height:1000});await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=600){scrollTo(0,y);await new Promise(r=>setTimeout(r,100))}scrollTo(0,0);document.activeElement?.blur()});await page.waitForTimeout(300);await page.screenshot({path:path.join(process.env.MELKAK_QA,'home-match-'+width+'.png'),fullPage:true})}}
console.log(`SUMMARY ${passed}/${passed+failed} PASS`);if(failed)process.exitCode=1;
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
