import assert from 'node:assert/strict';
import {createAdminManagementViews} from '../melkak/admin-management-view.js';
const calls=[];let dialog='',role='super_admin';
const escape=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const store={state:{users:[{uid:'owner',displayName:'Owner',status:'active'},{uid:'user',displayName:'<script>',email:'a@example.com',status:'active'}],legacy:{adminAccess:[]}},setUserStatus:async(...a)=>calls.push(['status',...a]),grantAssistant:async(...a)=>calls.push(['grant',...a]),updateAssistant:async(...a)=>calls.push(['update',...a]),removeAssistant:async(...a)=>calls.push(['remove',...a])};
const view=createAdminManagementViews({store,actor:()=>({uid:'owner',role,ready:true,status:'active',protectedUids:['owner'],permissions:[]}),t:(_,en)=>en,esc:escape,button:(text,action,attr='')=>`<button data-action="${action}" ${attr}>${text}</button>`,table:(heads,rows)=>JSON.stringify({heads,rows}),openDialog:(_,body)=>{dialog=body;},toast:()=>{},render:()=>{},preview:false,writable:true});
assert.ok(view.users('').includes('&lt;script>'));assert.ok(view.users('').includes('Protected'));
assert.ok(view.assistants().includes('Google'));
assert.equal(await view.handleClick({dataset:{action:'other'}}),false);
await view.handleClick({dataset:{action:'admin-user-status',id:'user'}});assert.ok(dialog.includes('required'));assert.ok(dialog.includes('blocked'));
const form=(kind,id,values)=>({dataset:{adminManagementForm:kind,id},elements:{namedItem:key=>({value:values[key]})},querySelectorAll:()=>values.permissions?.map(value=>({value}))||[]});
await view.handleSubmit(form('user-status','user',{status:'suspended',reason:'valid reason'}));assert.deepEqual(calls.pop(),['status','user','suspended','valid reason']);
await view.handleSubmit(form('assistant-grant','',{uid:'user',permissions:['listings_view'],reason:'valid reason'}));assert.deepEqual(calls.pop(),['grant','user',['listings_view'],'valid reason']);
store.state.legacy.adminAccess=[{id:'user',role:'admin_assistant',adminStatus:'active',permissions:['listings_view']}];
await view.handleSubmit(form('assistant-status','user',{adminStatus:'suspended',reason:'valid reason'}));assert.deepEqual(calls.pop(),['update','user',{adminStatus:'suspended'},'valid reason']);
await view.handleClick({dataset:{action:'admin-assistant-edit',id:'user'}});assert.ok(dialog.includes('listings_view'));assert.ok(!dialog.includes('auctions_manage'));
await view.handleSubmit(form('assistant-edit','user',{permissions:['reports_view'],reason:'valid reason'}));assert.deepEqual(calls.pop(),['update','user',{permissions:['reports_view']},'valid reason']);
await view.handleSubmit(form('assistant-remove','user',{reason:'valid reason'}));assert.deepEqual(calls.pop(),['remove','user','valid reason']);
await assert.rejects(()=>view.handleSubmit(form('user-status','user',{status:'blocked',reason:'   '})),{code:'REASON'});
assert.equal(await view.handleSubmit({dataset:{}}),false);
await assert.rejects(()=>view.handleSubmit(form('user-status','owner',{status:'blocked',reason:'valid reason'})),{code:'PROTECTED'});
role='admin_assistant';assert.ok(!view.assistants().includes('data-action="admin-assistant-add"'));await assert.rejects(()=>view.handleSubmit(form('assistant-grant','',{uid:'user',permissions:[],reason:'reason'})),{code:'PERMISSION'});
console.log('PASS admin management escaped views, protected controls, dialogs and service dispatch');
