import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../app.js', import.meta.url),'utf8').replace(/\r\n/g, '\n');
const html=fs.readFileSync(new URL('../index.html', import.meta.url),'utf8').replace(/\r\n/g, '\n');
const results=[];
function test(name, condition){if(!condition) throw new Error('FAIL | '+name); results.push(name); console.log('PASS | '+name);}
function extractFunction(name){
  const start=source.indexOf('function '+name); if(start<0) throw new Error('missing '+name);
  const brace=source.indexOf('{',source.indexOf(')',start)); let depth=0;
  for(let i=brace;i<source.length;i++){if(source[i]==='{')depth++; else if(source[i]==='}'&&--depth===0)return source.slice(start,i+1);}
  throw new Error('unclosed '+name);
}
const config=source.slice(source.indexOf('const COUNTRIES ='),source.indexOf('window.getSelectedListingCurrency'));
const filterFns=['timestampToDate','timestampToMillis','getAnimalLocationInfo','getMarketFilters','animalMatchesMarketFilters'].map(extractFunction).join('\n');
const values={};
const context={window:{},document:{addEventListener(){},getElementById(id){return values[id]?{value:values[id]}:null;}},console};
vm.createContext(context);
vm.runInContext('let activeMarketCountry=null;\n'+config+'\n'+filterFns+'\nglobalThis.api={COUNTRIES,SERVICES,effectiveCountry,money,normalizePhoneNumber,getAnimalLocationInfo,animalMatchesMarketFilters,isServiceApproved,isFeaturedListing,isBumpedListing,isVerifiedListing,marketplaceSort,setCountry:(v)=>activeMarketCountry=v};',context);
const a=context.api;
const activeBlock=source.slice(source.indexOf('const ACTIVE_MARKET_COUNTRY_KEY'),source.indexOf('const COUNTRIES'));
function storedCountry(saved){const c={localStorage:{getItem(){return saved;}},console};vm.createContext(c);vm.runInContext(activeBlock+'\nglobalThis.result=activeMarketCountry;',c);return c.result;}
test('first visit has no active country',storedCountry(null)===null);
test('saved AE survives reload',storedCountry('AE')==='AE');
test('saved EG survives reload',storedCountry('EG')==='EG');
test('invalid saved country is rejected',storedCountry('ALL')===null);
test('legacy document defaults to AE',a.effectiveCountry({})==='AE');
test('AE money uses AED',a.money(120,'AE')==='120 AED');
test('EG money uses EGP',a.money(120,'EG')==='120 EGP');
test('AE phone normalization',a.normalizePhoneNumber('0501234567','AE')==='+971501234567');
test('EG phone normalization',a.normalizePhoneNumber('01012345678','EG')==='+201012345678');
test('invalid UAE phone rejected',a.normalizePhoneNumber('05123','AE')===null);
test('invalid Egyptian prefix rejected',a.normalizePhoneNumber('01412345678','EG')===null);
function filters(country,region='all',city='all'){a.setCountry(country);Object.assign(values,{marketRegionFilter:region,marketCityFilter:city,marketAnimalFilter:'all',marketSaleTypeFilter:'all'});}
const legacy={saleType:'direct',location:'الذيد - الشارقة'};
const ae={country:'AE',region:'الشارقة',city:'الذيد',saleType:'direct'};
const eg={country:'EG',region:'القاهرة',city:'القاهرة',saleType:'direct'};
filters('AE'); test('AE filter includes legacy AE',a.animalMatchesMarketFilters(legacy)); test('AE filter excludes EG',!a.animalMatchesMarketFilters(eg));
filters('EG','القاهرة','القاهرة'); test('EG region/city filter includes EG',a.animalMatchesMarketFilters(eg)); test('EG filter excludes AE',!a.animalMatchesMarketFilters(ae));
filters('EG'); test('all regions/cities remain inside active EG market',a.animalMatchesMarketFilters(eg)&&!a.animalMatchesMarketFilters(ae)&&!a.animalMatchesMarketFilters(legacy));
test('listing form has country/region/city selectors',html.includes('id="animalCountry"')&&html.includes('id="animalRegion"')&&html.includes('id="animalCity"'));
test('first visit is blocked until country selection',source.includes('if (!activeMarketCountry) {\n    updateMarketCountryIndicator();\n    window.openMarketCountrySelector();\n    return;'));
test('country selector persists only to localStorage',source.includes('localStorage.setItem(ACTIVE_MARKET_COUNTRY_KEY, country)')&&!source.includes('souqActiveCountry:'));
test('market filters have no all-countries selector',!source.includes('id="marketCountryFilter"')&&!source.includes('جميع الدول'));
test('country switch reloads market immediately',source.includes('marketArea.remove()')&&source.includes('await loadMarket()'));
test('listing defaults to active country',source.includes('countrySelect.value = activeMarketCountry || "AE"'));
test('public auctions are constrained by active country',source.includes('.filter(auction => effectiveCountry(auction) === activeMarketCountry)'));
test('auction documents store country',/batch\.set\(auctionRef, \{\s*animalId: animalRef\.id,\s*country,/s.test(source));
test('offer rendering uses conversation country',source.includes('money(message.offerAmount, conversationCountry)'));
test('accepted/rejected offer logic remains present',source.includes('decision !== "accepted" && decision !== "rejected"')&&source.includes('contactStatus: "unlocked"'));
test('paid subscription gate is fully removed',!source.includes('SELLER_SUBSCRIPTION_PRICE_AED')&&!source.includes('FREE_LAUNCH_END')&&!source.includes('hasActiveSellerSubscription'));
test('expired or inactive subscription data cannot block selling',!source.includes('profile.subscriptionStatus')&&!source.includes('profile.subscriptionEnd'));
test('seller account type protection remains',source.includes('profile.accountType !== "seller" && profile.accountType !== "both"'));
test('account page shows the free plan',source.includes('الباقة المجانية')&&source.includes('يمكنك البيع وإضافة الحلال والمشاركة في السوق مجانًا'));
test('professional seller is future-only without payment UI',source.includes('البائع المحترف — قريبًا')&&!source.includes('100 EGP')&&!source.includes('100 AED'));
test('central AE service prices are correct',a.SERVICES.featured.AE.price===15&&a.SERVICES.bump.AE.price===7&&a.SERVICES.verification.AE.price===25);
test('central EG service prices are correct',a.SERVICES.featured.EG.price===200&&a.SERVICES.bump.EG.price===100&&a.SERVICES.verification.EG.price===350);
test('pending service is not approved or featured',!a.isServiceApproved({status:'pending'})&&!a.isFeaturedListing({}));
test('approved service state is recognized',a.isServiceApproved({status:'approved'}));
test('active featured listing is featured',a.isFeaturedListing({featuredUntil:new Date(Date.now()+86400000)}));
test('expired featured listing is not featured',!a.isFeaturedListing({featuredUntil:new Date(Date.now()-1000)}));
const featured={featuredUntil:new Date(Date.now()+86400000),featuredAt:new Date(),createdAt:new Date(1)};
const bumped={bumpedAt:new Date(),createdAt:new Date(2)};
const normal={createdAt:new Date(3)};
test('featured sorts before bumped and normal',[featured,bumped,normal].sort(a.marketplaceSort)[0]===featured);
test('bumped sorts before normal',[normal,bumped].sort(a.marketplaceSort)[0]===bumped);
test('duplicate pending uses deterministic request id',source.includes('serviceRequestId(user.uid, serviceType, target.targetType, target.targetId)'));
const sellerServiceBlock=source.slice(source.indexOf('window.submitListingService'),source.indexOf('async function requireAdminClaim'));
test('ordinary seller flow never writes approved service status',!sellerServiceBlock.includes('status: "approved"'));
test('services page and cancellation UI exist',source.includes('window.showMyServices')&&source.includes('window.cancelServiceRequest'));
test('listing management loads owned service requests with authorized query',source.includes('async function getUserServiceRequests(userId)')&&source.includes('where("userId", "==", userId)'));
test('listing management no longer gets missing service documents directly',!source.includes('getDoc(doc(db, "serviceRequests", requestId))'));
test('listing management renders all three service actions',source.includes('Object.keys(SERVICES).map')&&source.includes('const servicesHtml = await listingServicesHtml(animal, user.uid)'));
test('non-owner listing management guard remains',source.includes('if (animal.sellerId !== user.uid)'));
test('admin UI trusts only Firebase custom claim',source.includes('tokenResult.claims.admin === true')&&!source.includes('adminUid')&&!source.includes('adminPhone'));
test('non-admin admin button starts hidden',html.includes('id="adminPanelButton"')&&html.includes('id="adminPanelButton" type="button" onclick="openAdminPanel()"'));
test('admin panel exposes status country and service filters',source.includes('adminServiceStatusFilter')&&source.includes('adminServiceCountryFilter')&&source.includes('adminServiceTypeFilter'));
test('admin approval uses transaction and trusted target fields',source.includes('window.decideServiceRequest')&&source.includes('await runTransaction')&&source.includes('targetUpdate.featuredUntil')&&source.includes('targetUpdate.bumpedAt')&&source.includes('targetUpdate.verificationStatus = "verified"'));
test('admin rejection supports optional bounded note',source.includes('ملاحظة الرفض — اختيارية')&&source.includes('adminNote.trim().slice(0, 1000)'));
test('cancelled requests have no admin action buttons',source.includes('request.status === "pending" ?'));
test('new service requests start unpaid',source.includes('paymentStatus: "unpaid"'));
test('unpaid UI is explicit',source.includes('return "غير مدفوع"'));
test('normal unpaid approval is disabled',source.includes('effectivePaymentStatus(request) !== "paid" ? "disabled"'));
test('admin-only panel exposes separate override action',source.includes("'approved_override'")&&source.includes('اعتماد بدون دفع'));
test('override requires confirmation and allowed reason',source.includes('سيتم تفعيل الخدمة دون تسجيل دفعة مالية')&&source.includes('allowedOverrideReasons.includes(paymentOverrideReason)'));
test('override audit fields are written',source.includes('approval.paymentOverride = true')&&source.includes('approval.paymentOverrideBy = auth.currentUser.uid')&&source.includes('approval.paymentOverrideAt = serverTimestamp()'));
test('override result is labelled without faking payment',source.includes('معتمد استثنائيًا بدون دفع'));
test('paid approval remains separate',source.includes('SERVICE_PAYMENT_REQUIRED')&&source.includes('تم اعتماد الطلب المدفوع'));
vm.runInContext(['escapeHtml','safeImageData','inlineArgument','demoPaymentLink'].map(extractFunction).join('\n')+';globalThis.security={escapeHtml,safeImageData,inlineArgument,demoPaymentLink};',context);
const security=context.security;
test('image attributes reject quote injection',security.safeImageData('data:image/jpeg;base64,abc" onerror="alert(1)')==='');
test('jpeg compressed data remains accepted',security.safeImageData('data:image/jpeg;base64,YWJj')==='data:image/jpeg;base64,YWJj');
test('HTML user text is escaped',security.escapeHtml('<img onerror="x">').includes('&lt;'));
test('demo link only for missing or unpaid pending',!!security.demoPaymentLink({status:'pending'})&&!!security.demoPaymentLink({status:'pending',paymentStatus:'unpaid'})&&!security.demoPaymentLink({status:'pending',paymentStatus:'paid'})&&!security.demoPaymentLink({status:'approved',paymentStatus:'unpaid'})&&!security.demoPaymentLink({status:'pending',paymentStatus:null}));
console.log(`SUMMARY | ${results.length}/${results.length} passed`);
