import assert from 'node:assert/strict';
import {createVisitorRecorder,category,summarizeEvents,readWindow,readCounts} from '../visitor-analytics.js';
let n=0;const test=async(name,fn)=>{await fn();n++;console.log('PASS | '+name);};let time=Date.parse('2026-09-13T10:00:00+04:00'),seq=0,saved=null;const writes=[],opts={storage:{getItem:()=>saved,setItem:(_,s)=>saved=s},now:()=>time,random:()=>String(++seq).padStart(32,'a'),write:async e=>writes.push(e)};
const r=createVisitorRecorder(opts);
await test('anonymous visit',async()=>{assert.equal(r.record('page','home'),true);await r.flush();assert.equal(writes.length,1);});
await test('duplicate render/hash/listener prevented',()=>{for(let i=0;i<5;i++)assert.equal(r.record('page','home'),false);});
await test('real navigation',async()=>{assert.equal(r.record('page','market'),true);await r.flush();assert.equal(writes.length,2);});
await test('refresh dedupe',()=>assert.equal(createVisitorRecorder(opts).record('page','market'),false));
await test('30 minute idle new session',()=>{const old=r.state.id;time+=1800000;r.record('page','market');assert.notEqual(r.state.id,old);});await r.flush();
await test('midnight UAE reset',()=>{time=Date.parse('2026-09-13T23:59:59+04:00');r.record('page','home');const id=r.state.id;time+=1000;r.record('page','home');assert.notEqual(r.state.id,id);});await r.flush();
await test('admin category excluded',()=>assert.equal(r.record('page','admin'),false));
await test('invalid category rejected',()=>assert.equal(r.record('page','email=private'),false));
await test('disabled zero writes',async()=>{let count=0;const off=createVisitorRecorder({...opts,blocked:true,write:async()=>count++});off.record('page','home');await off.flush();assert.equal(count,0);});
await test('privacy event schema',()=>assert.deepEqual(Object.keys(writes[0]).sort(),['adId','category','kind','sequence','sessionId','sessionStartedAt'].sort()));
for(const [h,c]of [['#direct-sales','market'],['#auction-list','auctions'],['#sell','sell'],['#contact?token=secret','contact'],['#account','account'],['#admin',null]])await test('classification '+c,()=>assert.equal(category('/',h),c));
await test('about path',()=>assert.equal(category('/souq-alhalal/about.html'),'about'));
const events=[0,1,6,7,29,30].map((d,i)=>({sessionId:String(i),sequence:0,kind:'page',category:'home',occurredAt:new Date(time-d*86400000)}));const summary=summarizeEvents(events,time);
for(const [k,v]of Object.entries({today:1,seven:3,thirty:5,pageViews:5}))await test(k,()=>assert.equal(summary[k],v));
await test('top pages',()=>assert.equal(summary.pages.home,5));
await test('bounded dashboard query and truncation',async()=>{const api={db:{},collection:(_,n)=>n,where:(...x)=>x,orderBy:(...x)=>x,limit:n=>({limit:n}),query:(...x)=>x,getDocs:async q=>{assert.equal(q.at(-1).limit,1001);return {size:1001,docs:Array.from({length:1001},()=>({data:()=>({})}))}}};const result=await readWindow(api,time);assert.equal(result.events.length,1000);assert.equal(result.partial,true);});
await test('100 event session bound',()=>{for(let i=0;i<150;i++){r.record('page',i%2?'home':'market');}assert.ok(r.state.sequence<=100);assert.ok(r.state.pending.length<=10);});
await test('server count queries do not download event documents',async()=>{let calls=0;const api={db:{},collection:(_,n)=>n,where:(...x)=>x,query:(...x)=>x,getCountFromServer:async q=>{calls++;assert.equal(q[0],'analyticsEvents');return {data:()=>({count:7})}}};const out=await readCounts(api,time);assert.equal(calls,14);assert.equal(out.thirty,7);assert.equal(out.pages.listing_details,7);});
await test('ad event cannot start orphan session',()=>{const fresh=createVisitorRecorder({...opts,storage:{getItem:()=>null,setItem:()=>{}}});assert.equal(fresh.record('views','ad1'),false);assert.equal(fresh.record('page','home'),true);});
console.log(`SUMMARY | ${n}/${n} PASS`);
