const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {installMock,seedMock}=require('./user-seller-fixture.cjs');
const root=path.resolve(__dirname,'..'),shots=path.join(require('os').tmpdir(),'souq-featured-visual');fs.mkdirSync(shots,{recursive:true});
const names=[...fs.readFileSync(path.join(root,'app.js'),'utf8').matchAll(/import\s*\{([^}]+)\}/g)].flatMap(m=>m[1].split(',').map(s=>s.trim()));
let enable=false;let count=0;const pass=n=>{count++;console.log('PASS | '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(installMock);
await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='www.gstatic.com')return route.fulfill({contentType:'text/javascript',body:names.map(n=>`export const ${n}=window.__mock.api.${n};`).join('\n')});if(u.hostname!=='ux.test')return route.abort();const file=path.resolve(root,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain',body:enable&&file.endsWith("commercial-model.js")?fs.readFileSync(file,"utf8").replace("ANALYTICS_RELEASE_ENABLED=false","ANALYTICS_RELEASE_ENABLED=true"):fs.readFileSync(file)});});
await page.goto('https://ux.test/');await page.waitForFunction(()=>typeof window.selectMarketCountry==='function');await page.evaluate(seedMock);
await page.evaluate(async()=>{const m=window.__mock;m.admin=true;m.docs.set('adminSecurity/config',{enabled:true,superAdminUids:['owner']});m.docs.set('adminAccess/owner',{role:'super_admin',adminStatus:'active'});await m.setUser({uid:'owner',displayName:'مالك تجريبي'});m.reads.length=0;await window.openAdminSection('visitorAnalytics');});
assert.match(await page.locator('.commercial-admin').innerText(),/جمع الإحصاءات غير مفعّل حاليًا/);assert.match(await page.locator('.commercial-admin').innerText(),/ليست أشخاصًا فريدين/);pass('disabled and sessions explanation');assert.equal(await page.evaluate(()=>window.__mock.reads.some(x=>String(x).includes('analyticsEvents'))),false);pass('disabled zero event reads');
for(const width of [1366,768,360]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('responsive '+width);await page.screenshot({path:path.join(shots,'analytics-disabled-'+width+'.png'),fullPage:true});}
const result=await page.evaluate(async()=>{const V=await import('/visitor-analytics.js');let value=null,writes=[];const r=V.createVisitorRecorder({storage:{getItem:()=>value,setItem:(_,v)=>value=v},random:()=>crypto.randomUUID().replaceAll('-',''),write:async e=>writes.push(e)});r.record('page','home');r.record('page','home');r.record('page',V.category('/','#direct-sales'));await r.flush();const again=V.createVisitorRecorder({storage:{getItem:()=>value,setItem:(_,v)=>value=v},random:()=>crypto.randomUUID().replaceAll('-',''),write:async e=>writes.push(e)});again.record('page','market');await again.flush();return writes.map(e=>e.category);});assert.deepEqual(result,['home','market']);pass('browser repeated listener and refresh dedupe');enable=true;await page.addInitScript(()=>{window.__mock.api.getCountFromServer=async q=>{const list=[...window.__mock.docs].filter(([k,d])=>k.startsWith(q.path+'/')&&(q.filters||[]).filter(Array.isArray).every(([f,op,v])=>op==='=='?d[f]===v:op==='>='?d[f]>=v:op==='<='?d[f]<=v:true));return {data:()=>({count:list.length})};};});await page.reload();await page.waitForFunction(()=>!!window.openAdminSection);await page.evaluate(seedMock);await page.evaluate(async()=>{const m=window.__mock;m.admin=true;m.docs.set('adminSecurity/config',{enabled:true,superAdminUids:['owner']});m.docs.set('adminAccess/owner',{role:'super_admin',adminStatus:'active'});m.docs.set('platformTelemetry/config',{enabled:true});m.docs.set('analyticsEvents/sample',{sessionId:'fixture',sequence:0,kind:'page',category:'home',occurredAt:new Date(Date.now()-1000)});await m.setUser({uid:'owner',displayName:'مالك تجريبي'});await window.openAdminSection('visitorAnalytics');});assert.equal(await page.locator('.commercial-admin .admin-stats strong').last().innerText(),'1');pass('enabled fixture count cards use server aggregation');assert.match(await page.locator('.commercial-admin table').innerText(),/الرئيسية/);pass('fixed category top pages');await page.screenshot({path:path.join(shots,'analytics-enabled-fixture.png'),fullPage:true});
const installed=await page.evaluate(async()=>{const P=await import('/commercial-public.js'),api={...window.__mock.api,db:{}};const a=await P.installCommercialPublic(api),b=await P.installCommercialPublic(api);window.dispatchEvent(new CustomEvent('souq-pageview',{detail:'home'}));window.dispatchEvent(new CustomEvent('souq-pageview',{detail:'home'}));window.dispatchEvent(new CustomEvent('souq-pageview',{detail:'market'}));await a.recorder.flush();return {same:a.recorder===b.recorder,events:[...window.__mock.docs].filter(([k])=>k.startsWith('analyticsEvents/')&&k!=='analyticsEvents/sample').map(([,v])=>v.category)};});assert.equal(installed.same,true);assert.deepEqual(installed.events,['home','market']);pass('repeated installation uses one listener and immutable event writer');
assert.deepEqual(errors,[]);pass('zero JavaScript errors');console.log('SUMMARY | '+count+'/'+count+' PASS');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
