import fs from 'node:fs';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,updateDoc,deleteDoc,getDocs,collection,serverTimestamp,getCountFromServer,query,where} from 'firebase/firestore';
if(!/^127\.0\.0\.1:\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST||''))throw Error('Local emulator only');
const env=await initializeTestEnvironment({projectId:'demo-visitor-v2',firestore:{rules:fs.readFileSync(new URL('../firestore.rules',import.meta.url),'utf8').replace('return false && exists','return true && exists')}});
let n=0;const test=async(name,fn)=>{await fn();n++;console.log('PASS | '+name);};const guest=env.unauthenticatedContext().firestore(),user=env.authenticatedContext('user').firestore(),owner=env.authenticatedContext('owner',{admin:true}).firestore(),helper=env.authenticatedContext('helper').firestore();
const id='a'.repeat(32),start=new Date(),event={sessionId:id,sequence:0,sessionStartedAt:start,occurredAt:serverTimestamp(),kind:'page',category:'home',adId:''};
const put=(db,e,key=e.sessionId+'_'+e.sequence)=>setDoc(doc(db,'analyticsEvents',key),e);
try{await env.clearFirestore();await env.withSecurityRulesDisabled(async c=>{for(const uid of ['owner','helper','user'])await setDoc(doc(c.firestore(),'users',uid),{status:'active'});await setDoc(doc(c.firestore(),'adminSecurity/config'),{enabled:true,superAdminUids:['owner']});await setDoc(doc(c.firestore(),'adminAccess/helper'),{role:'admin_assistant',adminStatus:'active',permissions:['reports_view']});});
await test('disabled zero accepted writes',()=>assertFails(put(guest,event)));
await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'platformTelemetry/config'),{enabled:true}));
await test('anonymous first event',()=>assertSucceeds(put(guest,event)));
await test('logged-in event no UID needed',()=>assertSucceeds(put(user,{...event,sessionId:'b'.repeat(32)})));
await test('duplicate create blocked',()=>assertFails(put(guest,event)));
await test('other session update blocked',()=>assertFails(updateDoc(doc(user,'analyticsEvents',id+'_0'),{category:'market'})));
await test('deletion blocked',()=>assertFails(deleteDoc(doc(owner,'analyticsEvents',id+'_0'))));
await test('duplicate page blocked',()=>assertFails(put(guest,{...event,sequence:1})));
await test('real navigation accepted',()=>assertSucceeds(put(guest,{...event,sequence:1,category:'market'})));
for(const patch of [{sequence:100},{sequence:-1},{category:'admin'},{category:'email=secret'},{pageViews:999999},{pageViews:-1},{uid:'user'},{ip:'1.2.3.4'},{occurredAt:new Date(0)},{sessionStartedAt:new Date(Date.now()+60000)}])await test('invalid '+Object.keys(patch)[0],()=>assertFails(put(guest,{...event,sequence:2,...patch})));
await test('forged sequence without predecessor',()=>assertFails(put(guest,{...event,sequence:9})));
await test('Super Admin read',()=>assertSucceeds(getDocs(collection(owner,'analyticsEvents'))));
await test('assistant no analytics permission',()=>assertFails(getDocs(collection(helper,'analyticsEvents'))));
await test('owner count allowed',()=>assertSucceeds(getCountFromServer(query(collection(owner,'analyticsEvents'),where('kind','==','page')))));
await test('normal count denied',()=>assertFails(getCountFromServer(collection(user,'analyticsEvents'))));
await test('normal admin-read blocked',()=>assertFails(getDocs(collection(user,'analyticsEvents'))));
await test('arbitrary daily aggregates blocked',()=>assertFails(setDoc(doc(guest,'analyticsDaily/2026-09-13'),{sessions:9999})));
await test('legacy counter update blocked',()=>assertFails(setDoc(doc(guest,'analyticsSessions',id),{pageViews:9999})));
await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),'analyticsEvents',id+'_2'),{...event,sequence:2,occurredAt:new Date(Date.now()-1800001)}));
await test('30 minute server bound',()=>assertFails(put(guest,{...event,sequence:3,category:'sell'})));
console.log(`SUMMARY | ${n}/${n} PASS`);
}finally{await env.cleanup();}
