import {CATEGORIES,iconPaths} from './config.js';
import {normalizeLegacy} from './model.js';
export function seed(countries){const now=Date.now(),titles={livestock:['ناقة محلية بصحة ممتازة','Healthy local camel'],cars:['تويوتا لاند كروزر 2021','Toyota Land Cruiser 2021'],phones:['iPhone 15 Pro · 256 GB','iPhone 15 Pro · 256 GB'],computers:['MacBook Air M2 بحالة ممتازة','MacBook Air M2'],appliances:['غسالة أوتوماتيك 8 كجم','8 kg washing machine'],furniture:['أريكة عصرية بثلاثة مقاعد','Modern three-seat sofa'],tools:['عدة أدوات متكاملة','Complete tool kit'],sports:['دراجة جبلية خفيفة','Lightweight mountain bike'],children:['عربة أطفال قابلة للطي','Foldable stroller'],other:['مقتنيات منزلية مميزة','Selected home accessories']},prices=[89000,165000,2900,3300,850,1200,450,780,350,220];
// Fictional local review inventory. IDs, access roles and scenario states are preserved.
const demoVariants={
 cars:[['تويوتا لاند كروزر 2021','Toyota Land Cruiser 2021',165000,'تويوتا','لاند كروزر','2021'],['نيسان باترول 2020','Nissan Patrol 2020',132000,'نيسان','باترول','2020'],['هيونداي إلنترا 2019','Hyundai Elantra 2019',640000,'هيونداي','إلنترا','2019'],['تويوتا يارس 2022','Toyota Yaris 2022',4200,'تويوتا','يارس','2022'],['كيا سبورتاج 2018','Kia Sportage 2018',12500,'كيا','سبورتاج','2018'],['داسيا سانديرو 2023','Dacia Sandero 2023',138000,'داسيا','سانديرو','2023']],
 phones:[['iPhone 15 Pro · 256 GB','iPhone 15 Pro · 256 GB',2900],['Samsung Galaxy S24 · 128 GB','Samsung Galaxy S24 · 128 GB',2150],['Xiaomi Redmi Note 13','Xiaomi Redmi Note 13',8700],['iPhone 13 mini · 128 GB','iPhone 13 mini · 128 GB',145],['Google Pixel 8 · 128 GB','Google Pixel 8 · 128 GB',290],['Samsung Galaxy A55 · 256 GB','Samsung Galaxy A55 · 256 GB',3300]],
 livestock:[['ناقة محلية بصحة ممتازة','Healthy local camel',89000],['جمل وضح بعمر أربع سنوات','Four-year-old white camel',35000],['قعود بلدي هادئ','Calm young local camel',76000],['ناقة عُمانية بعمر ست سنوات','Six-year-old Omani camel',4800],['حوار مع أمه','Camel calf with its mother',6200],['جمل صحراوي مروّض','Trained desert camel',47000]]
};
const livestockDetails={AE:['female','5 سنوات','ناقة'],SA:['male','4 سنوات','جمل'],EG:['male','سنتان','قعود'],OM:['female','6 سنوات','ناقة'],JO:['male','6 أشهر','حوار'],MA:['male','5 سنوات','جمل']};
const listings=[];for(const [country,config]of Object.entries(countries)){CATEGORIES.forEach((c,i)=>{const region=Object.keys(config.regions)[0],city=config.regions[region][0],variant=demoVariants[c.id]?.[Object.keys(countries).indexOf(country)];listings.push({id:country+'-'+c.id,title:variant?.[0]||titles[c.id][0],titleEn:variant?.[1]||titles[c.id][1],description:'إعلان محلي تجريبي لمراجعة التصميم وتجربة الأقسام. هذه ليست بيانات منشورة أو عرضًا حقيقيًا للبيع.',category:c.id,price:variant?.[2]||prices[i],country,region,city,images:['./melkak/assets/'+c.id+'.svg'],attributes:Object.fromEntries(c.fields.map((f,j)=>[f.id,c.id==='livestock'&&['gender','age','type'].includes(f.id)?livestockDetails[country][{gender:0,age:1,type:2}[f.id]]:c.id==='cars'&&['brand','model','year'].includes(f.id)?variant[{brand:3,model:4,year:5}[f.id]]:f.options.length?f.options[0][0]:f.type==='number'?String(j===2?2021:45000):c.id==='cars'&&f.id==='brand'?'تويوتا':c.id==='cars'&&f.id==='model'?'لاند كروزر':'حالة ممتازة'])),ownerUid:i<3?'demo-owner':'demo-seller',sellerName:i<3?'سامي':'بائع تجريبي',status:i===8?'sold':'active',saleType:'direct',createdAt:now-(i+1)*3600000,contact:{phone:'+'+config.dial+'500000000',consent:true,call:true,whatsapp:true,showNumber:false},demo:true,history:i===0,featuredStatus:i===0||i===2?'approved':null,featuredStartAt:now-86400000,featuredEndAt:now+(i===0?86400000:5*86400000)});});}
const old={sellerId:'demo-owner',sellerName:'سامي',name:'ناقة — إعلان قديم محفوظ',country:'AE',region:'الشارقة',city:'الذيد',price:89000,type:'ناقة',saleType:'direct',status:'active',images:['./melkak/assets/livestock.svg'],createdAt:now-7*86400000,moderationLocked:true,sellerPhone:'+971512345678'};listings.push(normalizeLegacy('sample',old));listings.push(normalizeLegacy('auction',{...old,saleType:'auction'}));
const placements=['hero',...['hero_side_1','hero_side_2','hero_side_3','middle','footer_1','footer_2','footer_3','footer_4','footer_5']];const ads=[...Array.from({length:10},(_,i)=>({id:'hero-'+i,placement:'hero',priority:10-i,title:['مساحة جديدة لكل ما تملكه','بيعها اليوم. ابدأ حكاية جديدة.','اختيارات أقرب إليك'][i%3],description:'اكتشف الإعلانات وتواصل مع البائع مباشرة',asset:'./melkak/assets/'+CATEGORIES[(i+1)%CATEGORIES.length].id+'.svg'})),...placements.slice(1).map((placement,i)=>({id:placement,placement,priority:1,title:['لبيتك… قطعة تستحق','تقنية تناسب يومك','كل ما يحتاجه حلالك'][i%3],asset:'./melkak/assets/'+['furniture','phones','livestock'][i%3]+'.svg'}))].map(a=>({...a,advertiserName:'MELKAK Demo',countryTarget:'ALL',cityTarget:'',cta:'اكتشف الآن',status:'active',startAt:now-86400000,endAt:now+86400000*30,targetUrl:'https://example.test/',demo:true}));return {countries,listings,ads,users:[{uid:'demo-owner',name:'سامي',role:'super_admin',country:'AE'},{uid:'demo-seller',name:'بائع تجريبي',role:'user',country:'AE'},{uid:'demo-assistant',name:'مساعد تجريبي',role:'admin_assistant',country:'AE'}],legacy:{auctions:[{id:'old-auction',status:'preserved'}],purchaseRequests:[{id:'old-purchase',status:'preserved'}],conversations:[{id:'old-conversation',status:'preserved'}],messages:[{id:'old-message',status:'preserved'}]}};
}
