import {CATEGORIES,PAGE_SIZE} from './config.js';
import {can} from '../admin-permissions.js';
const fail=code=>{throw Object.assign(new Error(code),{code})};
export const millis=v=>v?.toMillis?.()??(v?.seconds?v.seconds*1000:new Date(v).getTime());
export const featured=(a,now=Date.now())=>a.status==='active'&&a.featuredStatus==='approved'&&Number.isFinite(millis(a.featuredEndAt))&&millis(a.featuredStartAt)<=now&&millis(a.featuredEndAt)>now;
export function normalizeLegacy(id,a){return {id:'legacy-'+id,sourceId:id,legacy:true,history:true,ownerUid:a.sellerId,category:'livestock',title:a.name||a.type||'حلال',country:a.country||'AE',region:a.region||'',city:a.city||a.location||'',price:Number(a.price)||0,description:a.description||'',images:(a.images||[]).slice(0,3),status:a.status==='unpublished'?'hidden':a.status==='not_approved'?'rejected':a.status||'active',saleType:a.saleType||'direct',sellerName:a.sellerName||'',attributes:{type:a.type||'',breed:a.breed||'',age:a.age||'',gender:a.gender||'',health:a.vaccinationStatus||''},contact:null,createdAt:millis(a.createdAt)||0,moderationLocked:!!a.moderationLocked,featuredStatus:a.featuredUntil?'approved':null,featuredStartAt:a.featuredAt,featuredEndAt:a.featuredUntil};}
export const normalizeSearch=value=>String(value??'').normalize('NFKC').toLowerCase().replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').trim();
export function matches(a,f,countries,now=Date.now()){
 if(a.saleType==='auction'||a.status!=='active'||(f.country&&a.country!==f.country)||(f.city&&a.city!==f.city)||(f.category&&a.category!==f.category))return false;
 if(f.min!==''&&f.min!=null&&a.price<Number(f.min))return false;if(f.max!==''&&f.max!=null&&a.price>Number(f.max))return false;
 const category=CATEGORIES.find(c=>c.id===a.category);const text=normalizeSearch([a.title,a.description,a.city,a.country,countries[a.country]?.name,countries[a.country]?.english,...(category?.name||[])].join(' '));
 if(normalizeSearch(f.search).split(/\s+/).filter(Boolean).some(t=>!text.includes(t)))return false;
 return Object.entries(f.attributes||{}).every(([k,v])=>!v||normalizeSearch(a.attributes[k]).includes(normalizeSearch(v)));
}
export function pageListings(items,f,countries,page=1,now=Date.now()){
 const rows=items.filter(a=>matches(a,f,countries,now)).sort((a,b)=>Number(featured(b,now))-Number(featured(a,now))||(f.sort==='oldest'?a.createdAt-b.createdAt:(b.bumpedAt||b.createdAt)-(a.bumpedAt||a.createdAt))||a.id.localeCompare(b.id));return {total:rows.length,items:rows.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),hasMore:rows.length>page*PAGE_SIZE};
}
export function phoneNumber(raw,country,countries){let n=String(raw||'').replace(/[\s()-]/g,'');if(n.startsWith('00'))n='+'+n.slice(2);if(!n.startsWith('+'))n='+'+countries[country].dial+n.replace(/^0/,'');return /^\+[1-9]\d{7,14}$/.test(n)?n:'';}
export function contactLinks(a,countries){const c=a.contact;if(!c?.consent)return {};const n=phoneNumber(c.phone,a.country,countries);if(!n)return {};return {call:c.call?'tel:'+n:null,whatsapp:c.whatsapp?'https://wa.me/'+n.slice(1):null,text:c.showNumber?n:null};}
export function validate(a,countries,{allowAssetImages=false}={}){
 const category=CATEGORIES.find(c=>c.id===a.category);if(!category)fail('CATEGORY');if(!countries[a.country]||!countries[a.country].regions[a.region]?.includes(a.city))fail('LOCATION');
 if(typeof a.title!=='string'||a.title.trim().length<3||a.title.length>100||typeof a.description!=='string'||a.description.trim().length<10||a.description.length>2000)fail('DETAILS');
 if(!Number.isFinite(Number(a.price))||Number(a.price)<0||Number(a.price)>1e10)fail('PRICE');
 if(!Array.isArray(a.images)||a.images.length<1||a.images.length>3||new Set(a.images).size!==a.images.length)fail('IMAGES');
 if(a.images.some(x=>typeof x!=='string'||x.length>210000||!(/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(x)||(allowAssetImages&&/^\.\/melkak\/assets\/[a-z-]+\.svg$/.test(x))))||a.images.join('').length>650000)fail('IMAGES');
 if(!a.contact?.consent||(!a.contact.call&&!a.contact.whatsapp)||!phoneNumber(a.contact.phone,a.country,countries))fail('CONSENT');
 if(Object.keys(a.attributes||{}).some(k=>!category.fields.some(f=>f.id===k))||Object.values(a.attributes||{}).some(v=>typeof v!=='string'||v.length>300))fail('FIELDS');return true;
}
export function deletionEligibility(a,actor){return a&&a.ownerUid===actor.uid&&!a.legacy&&!a.history&&!a.moderationLocked&&!['sold','archived'].includes(a.status);}
export function createLocalStore({listings=[],ads=[],countries,users=[],legacy={}}){
 // This port has no Firebase SDK, fetch, cloud keys, subscriptions or Production writer.
 const state={listings:structuredClone(listings),ads:structuredClone(ads),users:structuredClone(users),legacy:structuredClone(legacy),reports:[],services:[],audit:[],categories:CATEGORIES.map((c,i)=>({...c,enabled:true,order:i,featured:i<3})),version:0};let sequence=0;
 const audit=(actor,action,id)=>{state.audit.unshift({id:'audit-'+(++sequence),actor:actor.uid,action,target:id,at:Date.now(),result:'success'});state.version++;};
 const own=(id,actor)=>{const a=state.listings.find(x=>x.id===id);if(!a)fail('MISSING');if(a.ownerUid!==actor.uid)fail('OWNER');return a;};
 const service={state,create(data,actor){if(!actor?.uid)fail('AUTH');if(!state.categories.some(c=>c.id===data.category&&c.enabled))fail('CATEGORY');validate(data,countries);const a={...structuredClone(data),id:'local-'+(++sequence),ownerUid:actor.uid,sellerName:actor.name,createdAt:Date.now(),status:'active',saleType:'direct',history:false,legacy:false};state.listings.unshift(a);audit(actor,'create',a.id);return a;},
 update(id,data,actor){const a=own(id,actor);if(a.legacy)fail('LEGACY');if(a.moderationLocked)fail('MODERATED');const allowed=['title','price','description','country','region','city','contact','attributes','images'];if(Object.keys(data).some(k=>!allowed.includes(k)))fail('FIELDS');validate({...a,...data},countries,{allowAssetImages:true});Object.assign(a,structuredClone(data));audit(actor,'update',id);},
 transition(id,next,actor){const a=own(id,actor);if(next==='deleted'){if(!deletionEligibility(a,actor))fail('HISTORY');state.listings.splice(state.listings.indexOf(a),1);audit(actor,'delete',id);return;}if(next==='hidden'&&a.status==='active'){a.status='hidden';}else if(next==='active'&&a.status==='hidden'&&!a.moderationLocked&&a.saleType!=='auction'&&state.categories.some(c=>c.id===a.category&&c.enabled)){a.status='active';}else if(next==='sold'&&a.status==='active'){a.status='sold';}else fail('STATE');audit(actor,next,id);},
 report(id,reason,actor){if(!actor?.uid)fail('AUTH');if(!reason?.trim())fail('REASON');const a=state.listings.find(x=>x.id===id);if(!a)fail('MISSING');a.history=true;const report={id:'report-'+(++sequence),listingId:id,reason:reason.slice(0,500),status:'open',createdAt:Date.now()};state.reports.unshift(report);audit(actor,'report',id);},
 requestService(id,type,actor){const a=own(id,actor);if(!['featured','bump','verification'].includes(type)||a.status!=='active')fail('STATE');if(type==='verification'&&!['livestock','cars'].includes(a.category))fail('CATEGORY');if(state.services.some(s=>s.listingId===id&&s.type===type&&s.status==='pending'))fail('DUPLICATE');a.history=true;state.services.unshift({id:'service-'+(++sequence),listingId:id,type,status:'pending',createdAt:Date.now()});audit(actor,'service-request',id);},
 approveService(id,reason,actor){if(actor.role!=='super_admin')fail('PERMISSION');if(!reason?.trim())fail('REASON');const s=state.services.find(x=>x.id===id);if(!s||s.status!=='pending')fail('STATE');const a=state.listings.find(x=>x.id===s.listingId);s.status='approved';if(s.type==='featured')Object.assign(a,{featuredStatus:'approved',featuredStartAt:Date.now(),featuredEndAt:Date.now()+7*86400000});if(s.type==='bump')a.bumpedAt=Date.now();if(s.type==='verification')a.verified=true;audit(actor,'exception-approval',id);},
 configureCategory(id,patch,actor){if(actor.role!=='super_admin')fail('PERMISSION');if(Object.keys(patch).some(k=>!['enabled','order','featured','icon'].includes(k)))fail('FIELDS');if(typeof patch.order!=='undefined'&&(!Number.isInteger(patch.order)||patch.order<0||patch.order>99))fail('FIELDS');if(patch.icon&&!['car','phone','computer','appliance','sofa','tool','bike','baby','grid','camel'].includes(patch.icon))fail('FIELDS');Object.assign(state.categories.find(c=>c.id===id),patch);audit(actor,'category-update',id);},
 resolveReport(id,actor){if(!can(actor,'reports_manage'))fail('PERMISSION');const r=state.reports.find(x=>x.id===id);if(!r)fail('MISSING');r.status='resolved';audit(actor,'report-resolved',id);},
 moderate(id,status,reason,actor){if(!can(actor,'listings_manage'))fail('PERMISSION');if(!reason.trim())fail('REASON');const a=state.listings.find(x=>x.id===id);if(!a||a.legacy||!['active','hidden','rejected','archived'].includes(status))fail('STATE');a.status=status;a.moderationLocked=status!=='active';a.history=true;audit(actor,'moderate-'+status,id);},
 legacyRead(kind,actor){if(actor.role!=='super_admin')fail('PERMISSION');return structuredClone(state.legacy[kind]||[]);},
 statistics(country=''){const rows=state.listings.filter(x=>x.saleType!=='auction'&&(!country||x.country===country));return {total:rows.length,...Object.fromEntries(['active','sold','hidden','rejected','pending','archived'].map(s=>[s,rows.filter(x=>x.status===s).length])),featured:rows.filter(x=>featured(x)).length,soon:rows.filter(x=>featured(x)&&millis(x.featuredEndAt)-Date.now()<48*3600000).length,reports:state.reports.filter(x=>x.status==='open'&&rows.some(a=>a.id===x.listingId)).length,users:state.users.filter(u=>!country||u.country===country).length};}};return service;
}
