import {countryAds,commercialState,featuredState,safeTarget} from './marketplace-services.js';
import {heroSlots,PLACEMENTS,LABELS} from '../commercial-model.js';

export function phase1Views(c) {
  const {s,store,countries,t,esc,icon,link,button,cards,categories,searchbar,actor,can,date,render,openDialog,toast,listingImageData}=c;
  const $=q=>document.querySelector(q);
  const country=id=>id==='ALL'?t('كل الدول','All countries'):s.lang==='en'?countries[id]?.english:countries[id]?.name;
  const stateText=id=>({active:['نشط','Active'],expiring:['ينتهي قريبًا','Expiring'],expired:['منتهي','Expired'],pending:['بانتظار الاعتماد','Pending'],approved:['لم يبدأ','Scheduled'],future:['لم يبدأ','Scheduled'],rejected:['مرفوض','Rejected'],paused:['موقوف','Paused'],unspecified:['مدة التمييز غير محددة','Duration unspecified'],none:['عادي','Normal']}[id]?.[s.lang==='en'?1:0]||id);
  const chip=(status)=>`<span class="state-chip state-${esc(status)}">${esc(stateText(status))}</span>`;
  const dt=value=>new Date(value-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16);
  const shortDate=value=>Number.isFinite(value)?esc(date(value)):'—';
  const adImage=a=>c.asset(a.asset);
  const commercialLink=(a,body,cls='')=>`<a class="${cls}" data-commercial="${esc(a.id)}" href="${esc(safeTarget(a.targetUrl)||'#/commercial-request')}" target="_blank" rel="noopener noreferrer">${body}</a>`;
  let upload=null,busy=false;
  function adBlock(placement) {
    const a=countryAds(store.state.ads,placement,s.country,Date.now(),s.city)[0];if(!a)return '';
    return commercialLink(a,`<span class="tag">${t('إعلان ترويجي','Promotional ad')}</span><h3>${esc(a.title)}</h3><p>${esc(a.description||t('اكتشف فرصًا جديدة','Discover new opportunities'))}</p><img src="${adImage(a)}" alt="${esc(a.advertiserName||a.title)}" loading="lazy" width="280" height="210"><span class="button gold">${esc(a.cta||t('اكتشف الآن','Discover now'))}</span><small>${t('محاكاة محلية','Local demo')}</small>`,'promo-block small-ad');
  }
  function hero() {
    const ads=countryAds(store.state.ads,'hero',s.country,Date.now(),s.city),a=ads.length?ads[s.hero%ads.length]:null;
    const names={AE:['الإمارات','UAE'],SA:['السعودية','Saudi Arabia'],EG:['مصر','Egypt'],OM:['عُمان','Oman'],JO:['الأردن','Jordan'],MA:['المغرب','Morocco']};
    const banner=a?`<section class="world-hero campaign-hero" aria-label="${t('إعلان ترويجي Hero','Hero promotional ad')}"><img class="campaign-art" src="${adImage(a)}" alt="${esc(a.title)}" width="1100" height="370" fetchpriority="high"><div class="campaign-hero-copy"><span class="tag">${t('إعلان ترويجي','Promotional ad')}</span><h1>${esc(a.title)}</h1><p>${esc(a.description||'')}</p><small>${esc(a.advertiserName||'MELKAK Demo')} · ${esc(country(a.countryTarget||'ALL'))}</small>${commercialLink(a,esc(a.cta||t('اكتشف الآن','Discover now')),'button gold')}</div></section>`:`<section class="world-hero" aria-label="${t('مِلكك في ست دول','MELKAK across six countries')}"><img class="world-art" src="./melkak/assets/world-hero.webp" alt="${t('مناظر مستوحاة من الدول الست','Landscapes inspired by the six countries')}" width="1536" height="512" fetchpriority="high"><div class="world-copy"><p>${t('من كل مكان .. فرصتك أكثر','More places. More possibilities.')}</p><h1>مِلكك<span>MELKAK</span></h1><h2>${t('بيع واشتري مباشرة','Buy and sell directly')}</h2><div class="world-countries">${Object.entries(names).map(([id,n])=>button(n[s.lang==='en'?1:0],'world-country',`data-id="${id}" aria-pressed="${s.country===id}"`)).join('')}</div></div></section>`;
    return `${banner}<div class="hero-search">${searchbar()}</div>${a?`<section class="commercial-slider" aria-label="${t('الإعلانات التجارية','Commercial ads')}">${commercialLink(a,`<img class="hero-art" src="${adImage(a)}" width="180" height="100" alt="${esc(a.title)}"><div><span class="tag">${t('إعلان ترويجي','Promotional ad')}</span><strong>${esc(a.title)}</strong><small>${esc(a.advertiserName||'MELKAK Demo')} · ${esc(country(a.countryTarget||'ALL'))}</small></div><span class="button gold">${esc(a.cta||t('اكتشف الآن','Discover now'))}</span>`,'sponsor-link')}<div class="hero-controls">${button('‹','hero-prev',`aria-label="${t('الإعلان السابق','Previous ad')}"`)}<span dir="ltr" aria-live="polite">${s.hero%ads.length+1} / ${ads.length}</span>${button('›','hero-next',`aria-label="${t('الإعلان التالي','Next ad')}"`)}</div></section>`:`<p class="default-hero-note">${t('مِلكك يجمع فرصًا جديدة في ست دول — بدون عمولة','Six countries. New opportunities. No commission.')}</p>`}`;
  }
  function home() {
    const data=c.pageListings(c.publicRows(),{country:s.country,city:s.city,category:'',sort:'newest'},countries),featured=data.items.filter(a=>c.featured(a)),normal=data.items.filter(a=>!c.featured(a));
    return `<div class="market-layout"><div class="market-main">${hero()}<section class="featured-section"><div class="section-head"><h2>★ ${t('الإعلانات المميزة','Featured listings')}</h2>${link(t('عرض الكل','View all'),'featured','text-link')}</div>${cards(featured)}</section><section><div class="section-head"><h2>${icon('grid')}${t('تصفح الأقسام','Browse categories')}</h2>${link(t('جميع الأقسام','All categories'),'categories','text-link')}</div>${categories()}</section><div class="mobile-promos">${adBlock('hero_side_1')}</div><div class="section-head"><h2>${icon('clock')}${t('أحدث الإعلانات','Latest listings')}</h2>${link(t('عرض الكل','View all'),'market','text-link')}</div>${cards(normal.slice(0,6))}<div class="middle-promo">${adBlock('middle')}</div><div class="mobile-promos">${adBlock('hero_side_2')}</div>${cards(normal.slice(6,10))}<div class="mobile-promos">${adBlock('hero_side_3')}</div><div class="footer-ads">${[1,2,3,4,5].map(i=>adBlock('footer_'+i)).join('')}</div><p class="promo-invitation">${link(t('أعلن عن نشاطك في مِلكك','Promote your business on MELKAK'),'commercial-request','button gold')}</p></div><aside class="side-ads" aria-label="${t('إعلانات ترويجية جانبية','Side promotional ads')}">${[1,2,3].map(i=>adBlock('hero_side_'+i)).join('')}</aside></div>`;
  }
  function timingFields() {return `<div class="form-grid"><label>${t('مدة التمييز','Featured duration')}<select name="days" id="duration-days"><option value="7">7 ${t('أيام','days')}</option><option value="15">15 ${t('يومًا','days')}</option><option value="30">30 ${t('يومًا','days')}</option><option value="custom">${t('مدة مخصصة','Custom')}</option></select></label><label id="custom-duration" hidden>${t('عدد الأيام (1–365)','Days (1–365)')}<input name="customDays" type="number" min="1" max="365" value="7"></label><label>${t('بداية التمييز','Featured start')}<input name="startAt" type="datetime-local" value="${dt(Date.now())}" required></label></div>`;}
  function serviceDialog(id,type) {openDialog(t('طلب خدمة الإعلان','Listing service request'),`<form id="service-request-form" data-id="${esc(id)}" data-type="${esc(type)}">${type==='featured'?timingFields():`<p>${t('رفع الإعلان يحسن ترتيبه دون تغيير تاريخ نشره الأصلي.','Bump improves ordering without changing the original publication date.')}</p>`}<p class="notice">${t('مجاني في المعاينة. لا دفع ولا كتابة إلى الموقع الحقيقي.','Free local preview. No payments or live-site writes.')}</p><button type="submit" class="gold">${t('إرسال الطلب محليًا','Submit locally')}</button></form>`);}
  function metrics(rows) {
    const ads=store.state.ads.filter(a=>!s.adminCountry||a.countryTarget==='ALL'||a.countryTarget===s.adminCountry||!a.countryTarget);
    return `<div class="metric-strip">${[['active','مميز نشط','Active featured'],['expiring','مميز ينتهي قريبًا','Expiring featured'],['expired','مميز منتهي','Expired featured']].map(([k,ar,en])=>`<div><small>${t(ar,en)}</small><strong>${rows.filter(a=>k==='active'?['active','expiring'].includes(featuredState(a)):featuredState(a)===k).length}</strong></div>`).join('')}</div><div class="metric-strip">${['pending','active','expiring','expired'].map(k=>`<div><small>${t('ترويجي','Commercial')} · ${stateText(k)}</small><strong>${ads.filter(a=>k==='active'?['active','expiring'].includes(commercialState(a)):commercialState(a)===k).length}</strong></div>`).join('')}</div>`;
  }
  function featuredManagement(rows) {
    return `${metrics(rows)}<p class="notice">${t('ينتهي قريبًا: أقل من 48 ساعة. الدفع معطّل. يبدأ الاعتماد من الآن أو الموعد المستقبلي المختار، ولا يعتمد على تاريخ الطلب القديم.','Expiring: under 48 hours. Payments disabled. Approval starts now or at the chosen future date, never from an old request date.')}</p><div class="campaign-list">${rows.filter(a=>a.featuredStatus).map(a=>{const st=featuredState(a);return `<article class="campaign"><h3>${esc(a.title)}</h3>${chip(st)}<dl><div><dt>${t('البداية','Start')}</dt><dd>${shortDate(a.featuredStartAt)}</dd></div><div><dt>${t('النهاية','End')}</dt><dd>${shortDate(a.featuredEndAt)}</dd></div><div><dt>${t('المتبقي','Remaining')}</dt><dd>${Number.isFinite(a.featuredEndAt)?Math.max(0,Math.ceil((a.featuredEndAt-Date.now())/86400000))+' '+t('يوم','days'):t('مدة التمييز غير محددة','Duration unspecified')}</dd></div></dl></article>`;}).join('')}</div><div class="section-head"><h2>${t('طلبات الخدمات','Service requests')}</h2></div><div class="campaign-list">${store.state.services.filter(r=>rows.some(a=>a.id===r.listingId)).map(r=>`<article class="campaign"><h3>${esc(store.state.listings.find(a=>a.id===r.listingId)?.title)}</h3><p>${esc(r.type)} · ${r.featuredDurationDays||'—'} ${t('يوم','days')}</p>${chip(r.status)}${r.status==='pending'&&actor().role==='super_admin'?`<div class="manage-actions">${button(t('اعتماد بدون دفع','Approve without payment'),'approve-service',`data-id="${r.id}"`,'gold')}${button(t('رفض','Reject'),'reject-service',`data-id="${r.id}"`,'danger')}</div>`:''}</article>`).join('')||c.noData(t('لا توجد طلبات خدمات محلية','No local service requests'))}</div>`;
  }
  function commercialMap() {
    const ads=store.state.ads.filter(a=>!s.adminCountry||!a.countryTarget||a.countryTarget==='ALL'||a.countryTarget===s.adminCountry);
    const slots=heroSlots(ads),slot=(name,ad)=>`<div class="map-slot state-${ad?commercialState(ad):'empty'}"><strong>${esc(name)}</strong>${ad?`<span>${esc(ad.advertiserName||ad.title)}</span><small>${esc(country(ad.countryTarget||'ALL'))}</small>${chip(commercialState(ad))}<small>${shortDate(ad.startAt)} → ${shortDate(ad.endAt)}</small>`:`<small>${t('متاح','Available')}</small>`}</div>`;
    return `${metrics([])}<div class="section-head"><div><h2>${t('خريطة الإعلانات التجارية','Commercial ads map')}</h2><p class="muted">${t('معاينة مواضع العرض. كل إعلان ترويجي مستقل عن إعلانات السلع.','Placement preview. Promotions are separate from item listings.')}</p></div>${link(t('طلب إعلان ترويجي','Request a promotion'),'commercial-request','button gold')}</div><div class="placement-map"><div class="map-section">Header · MELKAK</div><div class="hero-map">${Array.from({length:10},(_,i)=>slot('Hero '+(i+1),slots[i]?.ad)).join('')}</div><div class="side-map">${[1,2,3].map(i=>slot('Side '+i,ads.find(a=>a.placement==='hero_side_'+i))).join('')}</div><div class="map-section">${t('الإعلانات المميزة','Featured listings')}</div>${slot(t('إعلان وسط الصفحة','Middle ad'),ads.find(a=>a.placement==='middle'))}<div class="map-section">${t('أحدث الإعلانات','Latest listings')}</div><div class="footer-map">${[1,2,3,4,5].map(i=>slot('Footer '+i,ads.find(a=>a.placement==='footer_'+i))).join('')}</div></div><div class="section-head"><h2>${t('إدارة الطلبات والحملات','Requests & campaigns')}</h2></div><div class="campaign-list">${ads.map(a=>`<article class="campaign"><h3>${esc(a.title)}</h3><p>${esc(a.advertiserName||'MELKAK Demo')} · ${esc(country(a.countryTarget||'ALL'))}</p>${chip(commercialState(a))}<small>${shortDate(a.startAt)} → ${shortDate(a.endAt)}</small>${actor().role==='super_admin'?`<div class="manage-actions">${(a.status==='pending'?['approved','rejected']:['active','approved'].includes(a.status)?['paused']:a.status==='paused'?['approved']:[]).map(k=>button(t(k==='approved'?'اعتماد':k==='paused'?'إيقاف':'رفض',k==='approved'?'Approve':k==='paused'?'Pause':'Reject'),'review-commercial',`data-id="${a.id}" data-next="${k}"`,k==='rejected'?'danger':k==='approved'?'primary':'gold')).join('')}</div>`:''}</article>`).join('')}</div>`;
  }
  function requestCommercial() {
    if(!s.signedIn)return c.previewLogin();
    return `<div class="page-head"><div><h1>${t('طلب إعلان ترويجي','Request a promotional ad')}</h1><p class="muted">${t('عرّف بنشاطك في المكان المناسب','Put your business in the right place')}</p></div></div><form id="commercial-request-form" class="panel"><div class="form-grid"><label>${t('موضع الإعلان','Placement')}<select name="placement">${PLACEMENTS.map(k=>`<option value="${k}">${esc(s.lang==='en'?k:LABELS[k])}</option>`).join('')}</select></label><label>${t('الدولة المستهدفة','Country target')}<select name="countryTarget"><option value="ALL">${country('ALL')}</option>${Object.keys(countries).map(k=>`<option value="${k}">${esc(country(k))}</option>`).join('')}</select></label><label>${t('اسم المعلن','Advertiser')}<input name="advertiserName" required maxlength="100"></label><label>${t('عنوان الإعلان','Ad title')}<input name="title" required maxlength="100"></label><label>${t('نص الزر','CTA')}<input name="cta" required maxlength="50" value="${t('اكتشف الآن','Discover now')}"></label><label>${t('رابط الوجهة HTTPS','HTTPS destination')}<input name="targetUrl" type="url" placeholder="https://" required></label><label>${t('البداية','Start')}<input type="datetime-local" name="startAt" required value="${dt(Date.now())}"></label><label>${t('النهاية','End')}<input type="datetime-local" name="endAt" required value="${dt(Date.now()+7*86400000)}"></label><label>${t('ترتيب Hero / الأولوية','Hero order / priority')}<select name="priority">${Array.from({length:10},(_,i)=>`<option value="${10-i}">Hero ${i+1}</option>`).join('')}</select></label><label class="full">${t('الوصف','Description')}<textarea name="description" maxlength="500"></textarea></label><label class="full">${t('صورة الإعلان — JPG / PNG / WebP','Ad image — JPG / PNG / WebP')}<input id="commercial-image-picker" type="file" accept="image/jpeg,image/png,image/webp"></label><div id="commercial-preview" class="full" role="status"></div></div><p class="notice">${t('طلب محلي فقط · الدفع معطّل · يحتاج اعتماد المدير قبل العرض. الصورة مضغوطة ولا تُرفع إلى Production.','Local request only · Payments disabled · Admin approval required. Compressed image never uploaded to Production.')}</p><button type="submit" class="gold" id="commercial-save" disabled>${t('إرسال الطلب محليًا','Submit locally')}</button></form>`;
  }
  function reports() {
    return `<div class="campaign-list">${store.state.reports.map(r=>`<article class="campaign"><h3>${esc(r.reason)}</h3><p>${esc(r.targetUid||r.listingId)}</p><span class="state-chip">${esc(r.status)}</span>${can(actor(),'reports_manage')?`<div class="manage-actions">${button(t('تمت المعالجة','Resolve'),'resolve-report',`data-id="${r.id}"`)}${button(t('مراجعة وإجراءات','Review & actions'),'report-actions',`data-id="${r.id}"`)}</div>`:''}</article>`).join('')||c.noData(t('لا توجد بلاغات محلية','No local reports'))}</div>`;
  }
  function info(kind) {return `<section class="panel info-page"><div class="eyebrow">MELKAK</div><h1>${kind==='about'?t('من كل مكان .. فرصتك أكثر','More places. More possibilities.'):t('تواصل معنا','Contact us')}</h1><p>${kind==='about'?t('مِلكك منصة إعلانات مبوبة للبيع والشراء المباشر في ست دول. انشر سلعتك وتواصل بالاتصال أو واتساب، بدون عمولة.','MELKAK is a six-country marketplace for direct classifieds. List your item and connect by call or WhatsApp, without commission.'):t('قناة الدعم الرسمية ستُحدد قبل الإطلاق. لا نعرض رقمًا أو بريدًا غير معتمد. يمكنك تجربة إرسال طلب إعلان ترويجي محليًا.','The official support channel will be set before launch. No unapproved phone or email is displayed. You can preview submitting a local promotion request.')}</p>${link(t('طلب إعلان ترويجي','Request a promotion'),'commercial-request','button gold')}</section>`;}
  function bind() {
    document.addEventListener('click',e=>{const ad=e.target.closest('[data-commercial]');if(ad&&store.state.ads.find(a=>a.id===ad.dataset.commercial)?.demo){e.preventDefault();toast(t('رابط ترويجي تجريبي — لم يُفتح موقع خارجي','Demo promotion — no external website opened'));return;}const el=e.target.closest('[data-action]');if(!el)return;const {action,id,next}=el.dataset;
      if(action==='world-country'){s.country=id;s.city='';s.hero=0;render();}
      if(action==='commercial-remove'){upload=null;$('#commercial-preview').innerHTML='';$('#commercial-image-picker').value='';$('#commercial-save').disabled=true;}
      if(action==='reject-service'||action==='review-commercial')openDialog(t('تأكيد المراجعة المحلية','Confirm local review'),`<form id="${action==='reject-service'?'reject-service-form':'commercial-review-form'}" data-id="${esc(id)}" data-next="${esc(next||'')}"><label>${t('السبب','Reason')}<textarea name="reason" required maxlength="500"></textarea></label><button type="submit" class="gold">${t('تأكيد','Confirm')}</button></form>`);
      if(action==='report-user')openDialog(t('الإبلاغ عن المستخدم','Report user'),`<form id="user-report-form" data-id="${esc(id)}"><label>${t('السبب','Reason')}<textarea name="reason" required maxlength="500"></textarea></label><button type="submit" class="danger">${t('إرسال البلاغ محليًا','Submit locally')}</button></form>`);
      if(action==='report-actions')openDialog(t('إجراءات البلاغ','Report actions'),`<form id="report-action-form" data-id="${esc(id)}"><label>${t('الإجراء','Action')}<select name="action"><option value="review">${t('مراجعة','Review')}</option><option value="dismiss">${t('استبعاد','Dismiss')}</option>${can(actor(),'listings_manage')?`<option value="hide">${t('إخفاء الإعلان','Hide listing')}</option>`:''}${can(actor(),'users_suspend')?`<option value="suspend">${t('تعليق المستخدم','Suspend user')}</option>`:''}<option value="escalate">${t('تصعيد','Escalate')}</option></select></label><label>${t('السبب','Reason')}<textarea name="reason" required maxlength="500"></textarea></label><button type="submit">${t('تأكيد','Confirm')}</button></form>`);
    });
    document.addEventListener('change',async e=>{if(e.target.id==='duration-days')$('#custom-duration').hidden=e.target.value!=='custom';if(e.target.id!=='commercial-image-picker')return;const file=e.target.files[0];upload=null;$('#commercial-save').disabled=true;$('#commercial-preview').innerHTML='';if(!file)return;busy=true;try{const [image]=await listingImageData([file],{uid:actor().uid});if(image.length>210000)throw Error('IMAGES');const img=new Image();img.src=image;await img.decode();upload=image;$('#commercial-preview').innerHTML=`<img src="${image}" alt="${t('معاينة الإعلان','Ad preview')}" width="480" height="260"><p>${esc(file.name)} · ${Math.ceil(image.length/1024)} KB · ${img.naturalWidth} × ${img.naturalHeight}</p>${button(t('إزالة الصورة','Remove image'),'commercial-remove')}`;$('#commercial-save').disabled=false;}catch(err){toast(c.errorText(err));}finally{busy=false;}});
    document.addEventListener('submit',e=>{const form=e.target,fd=new FormData(form);if(!['service-request-form','reject-service-form','commercial-request-form','commercial-review-form','user-report-form','report-action-form'].includes(form.id))return;e.preventDefault();try{
      if(form.id==='service-request-form')store.requestService(form.dataset.id,form.dataset.type,actor(),{days:fd.get('days')==='custom'?Number(fd.get('customDays')):Number(fd.get('days')||7),startAt:fd.get('startAt')?Date.parse(fd.get('startAt')):Date.now()});
      if(form.id==='reject-service-form')store.rejectService(form.dataset.id,String(fd.get('reason')),actor());
      if(form.id==='commercial-request-form'){if(busy||!upload)throw Error('IMAGES');store.requestCommercial({...Object.fromEntries(fd),image:upload},actor());upload=null;location.hash='#/account';}
      if(form.id==='commercial-review-form')store.reviewCommercial(form.dataset.id,form.dataset.next,String(fd.get('reason')),actor());
      if(form.id==='user-report-form')store.reportUser(form.dataset.id,String(fd.get('reason')),actor());
      if(form.id==='report-action-form')store.actOnReport(form.dataset.id,String(fd.get('action')),String(fd.get('reason')),actor());
      if($('#dialog').open)$('#dialog').close();render();toast(t('تم حفظ الطلب محليًا فقط','Saved locally only'));
    }catch(err){toast(c.errorText(err));}});
  }
  return {home,hero,adBlock,featuredManagement,commercialMap,requestCommercial,serviceDialog,metrics,reports,info,bind};
}
